### PR TITLE
Updated data dictionaries

### LINKED ISSUE #1816: Update definitions in download spreadsheets
Update definitions in download files to match the download pages. 
C:\Users\goldstel\nrrd\database\static\csv\data_dictionary

### PR DESCRIPTION
**Pull request by lpgoldstein**
Fixes #1816

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/datadictionary/)

Changes proposed in this pull request:
- updates all data dictionaries to match the download pages

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@Baymatt This one is also fixed and ready for your review.

**Comment by lpgoldstein** [comment]
@mojobnichols something looks wrong on the file title in the production monthly downloads page 
image

**Comment by jlouis-onrr** [comment]
@lpgoldstein, I resolved the conflict with dev which a issue with bad chars in the csv.  The preview is available with the updated link.

**Comment by Maroyafaied** [comment]
@jlouis-onrr you're awesome, thank you!! @lpgoldstein @Baymatt please review the data dictionary files.

**Comment by lpgoldstein** [comment]
@jlouis-onrr If I want to make a tiny change to the disbursement file is it going to break everything?

**Comment by jlouis-onrr** [comment]
@lpgoldstein, depends on how the csv gets saved/formatted.  If there is a discrepancy or issue with the file there should be conflict with this fixed version that can be resolved.

**Comment by lpgoldstein** [comment]
@jlouis-onrr Thanks - I don't think it was an issue with the disbursements file last time so I'll try and see what happens

**Comment by lpgoldstein** [comment]
@Maroyafaied @baymatt looks good to me. I was able to make the small change without breaking it.

**Pull request merged**
