### PR TITLE
Links and Spelling

### LINKED ISSUE #1877: Fix broken link in reclamation page
This link is broken, we received an email about it in the nrrd mailbox and I don't believe it was caught in the content audit. 

https://revenuedata.doi.gov/how-revenue-works/reclamation/

### LINKED ISSUE #1883: Fix Misspellings in Glossary & change Geothermal term "Utilization" to "Use"
image
image
image
image
 
In the glossary, for some some terms we say "Direct Utilization' and for others we say "Direct Use" (in red) , please change al terms to say direct use and fix spellings ( in yellow).

### PR DESCRIPTION
**Pull request by daniel-coleman-1**
- [x] Fixes #1883

- [x] Fixes #1877

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/content-updates/)

Changes proposed in this pull request:

-fixes broken link in Reclamation page
-corrects spelling in Glossary

### CODE REVIEW

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 here is one mispelling
image

**Comment by daniel-coleman-1** [comment]
Thanks @lpgoldstein, nice catch. 

Also wanted to mention I left "nonfossil" as is, I understand that to be correct and the dictionary agrees:
https://www.merriam-webster.com/dictionary/nonfossil

But Lindsay since you have more of a technical knowledge of the terms, do you think we should split "nonfossil" into "non fossil" or "non-fossil"?

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 I've never heard anyone use that term at all so I'm sure the dictionary is fine.

**Comment by daniel-coleman-1** [comment]
@lpgoldstein I think we can merge this PR now

**Review by lpgoldstein — APPROVED** [review]

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 Let's save for Maroya to merge on Monday. But it looks good!

**Pull request merged**
