### PR TITLE
1107 query tool fixes

### LINKED ISSUE #1107: Company field label doesn't display outside the field like other field labels
For query data > federal revenue by company

### PR DESCRIPTION
**Pull request by master12**
Fixes #1107 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1107-query-tool-fixes/)

Changes proposed in this pull request:

- 1106 - Revenue by company clear all fixed
- 1048 relabel columns to Column 1 Column 2
- 1049 - Source and Doc link to data file page
- 1045 - combine more filters into main tab
- 1107 - Company label to outside the field
- 956 - Fix fluid image issue - Added detailed logging and empty return

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@master12 The calendar year text overlaps with the arrow. Also, for the company field, is it possible to have a select all option like the other filters?

**Comment by mcharg** [comment]
@master12 I agree with Maroya's suggestions on Revenue by Company.

Is there a reason there's so much space between the drop-downs on the right, particularly for disbursements and production?
image
image

**Review by mcharg — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@master12 there's some overlapping when selecting revenue that I highlighted in the pic below. Also, I checked the data for revenue by company and by default we do show data for All companies before selecting any filters. So I think we should "All" inside the filter box and give the option to chose more than one company at a time. 
image

image

**Comment by mcharg** [comment]
@Maroyafaied The problem with putting "All" in the drop-down is that it doesn't make it clear that you can search for a company.  I think the ability to search is more valuable than being able to select multiple, since the list is so long.

**Comment by Maroyafaied** [comment]
@mcharg ok, I didn't realize it would take the search ability away. It's fine the way it is then. Everything looked good except the overlapping highlighted in the pic above.

**Comment by Maroyafaied** [comment]
@master12 if you can fix this overlapping issue today, we can merge this with the release. Thanks! 
image

**Comment by mcharg** [comment]
@Maroyafaied I'm not seeing that issue even when I make my window smaller.
image

**Comment by master12** [comment]
@mcharg and @Maroyafaied I see it

**Comment by Maroyafaied** [comment]
@mcharg @master12 this is how disbursements looks like for me, is it only me? 
image

**Comment by mcharg** [comment]
@Maroyafaied It's not just you.  Maybe related to the database issue messing up the homepage on dev?

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
