### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:
## Updated monthly production (January 2021)
Homepage - Yearly Breakdown
- [x] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- [x] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Source File
- [x] Check source file links are correct.

Query Data
- [x] One Land Type filter
- [x] One State
- [x] One Offshore Region
- [x] One to three Product
- [x] Downloads matches filtered data
- [x] Monthly data is correct

Download Page
- [x] Dates and file size are correct for csv and excel

Fact sheet
- [x] Production numbers are correct

## Updated monthly disbursements (March 2021)
Homepage - Yearly Breakdown
- [x] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Breakout - Source 
- [x] Breakout - Recipient
 
Homepage - Monthly Breakdown
- [x] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data
- [x] Monthly data

Download Page
- [x] Dates and file size are correct for csv and excel
- [x] Download file matches original file.

Fact Sheet
- [x] Monthly disbursements numbers are correct

## Updated monthly revenue (April 2021)
Homepage - Yearly Breakdown
- [x] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout - Commodity
 
Homepage - Monthly Breakdown
- [x] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout Commodity
 
Homepage - Source File
- [x] Check source file links are correct.
 
Explore Data - Map and Detail Card
- [x] Select a year and select a state with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [x] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected
 
- [x] Select a year and select a county with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [x] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected.
 
- [x] Select a year and select an offshore area, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [x] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected.
 
- [x] Select a state and county without data and verify the expected information is displayed.
- [x] Add Nationwide Federal Card and verify the expected information is displayed.
- [x] Add Native American Card and verify the expected information is displayed.

Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- [x] Verify breakdowns by revenue type and source are correct as well nationwide locations for the conditions below.
    - [x] Not current Calendar Year
    - [x] Current Calendar Year
    - [x] Not current Fiscal Year
    - [x] Current Fiscal Year

Query Data
- [x] With a selected fiscal or calendar  year range, verify the data is correct and then for the conditions below. 
- [x] One Land Type filter
- [x] One Revenue Type filter
- [x] One State
- [x] One Offshore Region
- [x] One to three Commodities
- [x] Clear All and change grouping
- [x] Downloads matches filtered data
- [x] Monthly numbers are correct

Download Page
- [x] Dates and file size are correct for csv and excel

Fact Sheet
- [x] Revenue numbers are correct
## Check Browsers

- [x] Chrome
- [x] Internet Explorer
- [x] Safari
- [x] Firefox
- [x] Edge

## Other changes

- [x] ** Added blog post about stakeholders buy in**
- [x] ** Added glossary page**
- [x] ** Added glossary to stacked bar chars**
- [x] ** Added data dictionary to downloads**
- [x] ** Added message more than 4 cards selected**
- [x] ** Fix bugs ( scroll to top on homepage, add commas to circle charts, remove extra column)**

### CODE REVIEW

**Review by mojobnichols — APPROVED** [review]

**Comment by mcharg** [comment]
@mojobnichols I'm getting an error in the query tool when I try to pick a third filter.  I'm in Disbursements > Monthly > U.S. Treasury > GOMESA and every time I try to pick a state it crashes.
image

**Comment by Maroyafaied** [comment]
@jlouis-onrr do you happen to know how to fix the monthly fact sheet to show the data for these revenue types like it does on the homepage? 
image

**Comment by mcharg** [comment]
@mojobnichols I'm still getting a blank checkbox in the state menu.  Is that supposed to be fixed in this?
image

**Comment by Maroyafaied** [comment]
> @mojobnichols I'm getting an error in the query tool when I try to pick a third filter. I'm in Disbursements > Monthly > U.S. Treasury > GOMESA and every time I try to pick a state it crashes.
> image

@mcharg @mojobnichols looks like this is happening on the live site as well so it's not anything with recent changes. @mcharg can you make an issue for it?

**Comment by Maroyafaied** [comment]
> @mojobnichols I'm still getting a blank checkbox in the state menu. Is that supposed to be fixed in this?
> image

@mcharg no it's not supposed to be fixed in this release, it's also a bug on the live site currently. I have an issue for this one. https://github.com/ONRR/nrrd/issues/1565

**Review by daniel-coleman-1 — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@jlouis-onrr data doesn't show up when I'm in production, monthly, then select CY 2020 
image

**Review by mcharg — APPROVED** [review]
Disbursements data and blog post look good.  I didn't check anything else.

**Pull request merged**
