### PR TITLE
Units not showing properly in TotalProduction

### PR DESCRIPTION
**Pull request by jlouis-onrr**
fix for units not showing in Total Production

### CODE REVIEW

**Comment by cthomasONRR** [comment]
@jlouis-onrr is there a preview link?

**Comment by jlouis-onrr** [comment]
[Preview](https://nrrd-preview.app.cloud.gov/sites/ProdCharts)

**Review by cthomasONRR — APPROVED** [review]
I clicked through all the production chart options, and it all looks good to me! Thanks for fixing this so quickly!!

**Review by lpgoldstein — APPROVED** [review]

**Comment by lpgoldstein** [comment]
Looks great, thank you!

**Review by mcharg — APPROVED** [review]

**Pull request merged**
