### PR TITLE
224 update download files

### LINKED ISSUE #224: Update text (date, file size) for download links using database
Using a graphql query, get the file size of the file that is in the link and append the info to the link text. 

This should be done in the new Link component

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #224 , #1464 , #1405

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/224-updateDownloadFiles)

Changes proposed in this pull request:

csv files for individual data sets
xlsx that combines data sets

Revenue

- [x]  FY and CY csv files are blank, even in the combined excel sheet

- [x]  For csv and excel , make offshore region blank for anything with Land Class as onshore or not tied to a lease

- [x] In combined excel file, the "Date" column in monthly tab needs to be formatted and add 0 in front of FIPS code. Take off ".csv" from title in tabs.

- [x] Order columns in the following order for all files (Date, Land Class, Land Category, State, County, FIPS, Revenue Type, Mineral Lease Type, Commodity, Product, Revenue)

- [x] Ensure Mineral lease type is lining up correctly with the correct data. 

- [x] Format date correctly in combined excel file for monthly revenue tab, and take out the "Date" column for fiscal year and calendar year tab.

- [x] Take "Date" column out in csv files for both fiscal and calendar year

Production

- [x] Take off monthly csv file and from the tab in the combined excel file ( monthly production data will still have it's own download page)

- [x] In combined excel file, Take off ".csv" from titles, and it should only have two tabs for CY and FY

- [x] Add 0 in front of FIPS in the combined excel file.  [Not fixing because it depends on how excel opens file, file has zero in front of it and is quoted]

- [x] Generate monthly download files in the Production by Month download page

- [x] Take "Date" column out in combined excel sheet for both Fiscal year and calendar year tabs.  

- [x] Take "Date" column out in csv files for both fiscal and calendar year

Disbursements

- [x] Take off monthly csv file (monthly disbursements will still have it's own page)

- [x] The combined excel file will only have FY tab , so title it the same as the csv file.

- [x] Generate monthly download files in the Disbursement by Month download page

- [x]  Take "Date" column out in csv files for fiscal year 

Revenue by Company

- [x] Will need the file generated as well from the database.

-
-
-

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@Mojo the monthly files need to be formatted, there is a lot of unnecessary columns. I've formatted the monthly one for an example. 
1. Erase the following columns (A, C, E, F, H, M, N, S)
2. Please rename the remaining columns as I have them in the example spreadsheet.
3.  Delete any FIPS codes (leave empty) if land category is offshore or not tied to a lease, or if land class is Native American
4.  Delete anything in offshore region (leave empty) for anything that's federal onshore, Native American or Not tied to a lease 

I've done all the following in this spreadsheet as an example. I'll give this spreadsheet to Matt and DORC team to start reviewing data.  Also the production and disbursement files don't seem to have the latest data I uploaded last week. 
[Formatted monthly revenue.xlsx](https://github.com/ONRR/nrrd/files/6144845/Formatted.monthly.revenue.xlsx)

**Comment by Maroyafaied** [comment]
@mojobnichols Also the dates are wrong 
image

**Comment by Maroyafaied** [comment]
@mojobnichols this is the changes for the CY file.

**Comment by Maroyafaied** [comment]
@mojobnichols Here's what I found for revenue
1. FY and CY csv files are blank, even in the combined excel sheet
2. For csv and excel , make offshore region blank for anything with Land Class as onshore or not tied to a lease

**Comment by Maroyafaied** [comment]
@mojobnichols For production yearly download page , we don't want to put the monthly file in that page. We are keeping it in its own page since it has different fields.

**Comment by Maroyafaied** [comment]
@mojobnichols For all the combined excel sheets, can you ) in front of the FIPS codes and can you take the ".csv" off from the titles in tab. Also take the monthly tab off for disbursement and production.

**Comment by mojobnichols** [comment]
Okay you can have another look.

**Comment by Maroyafaied** [comment]
@mojobnichols These items are still an issue for  revenue


- [ ]  For csv and excel revenue files , make offshore region blank for anything with Land Class as onshore or not tied to a lease

- [ ] In combined excel revenue file, the "Date" column in monthly tab needs to be formatted . and take out "Date" from FY and CY tabs

- [ ] Order columns in the following order for all revenue files (Date, Land Class, Land Category, State, County, FIPS, Revenue Type, Mineral Lease Type, Commodity, Product, Revenue)

- [ ] Take "Date" column out in csv files for both fiscal and calendar year and combined excel sheets for revenue and production

**Comment by Baymatt** [comment]
@mojobnichols For the monthly production files, the new ones should not have both a commodity and product column. Please delete the commodity column and relabel the product one as "Commodity" to match the previous format.

Screen Shot 2021-04-06 at 11 51 00 AM

**Pull request merged**
