### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

New homepage trends & comparison design

Updated land ownership data

Updated monthly revenue data January 2021
Homepage 
- [x] Monthly bar charts (most recent 12 months, FY & CY)
- [x] CY bar charts
- [x] FY bar charts
- [x] Check Breakouts (Source & Revenue type, commodity)
- [x] Check year over year comparison
- [x] Check month over month comparison
- [x] Source file links
Download 
- [x] xls and csv files updated with correct dates and file size

Updated monthly production data October 2020
Homepage
- [x] Monthly bar charts (most recent 12 months, FY & CY)
- [x] CY bar charts
- [x] FY bar charts
- [x] Check all commodities
- [x] Check year over year comparison
- [x] Check month over month comparison
- [x] Source file links
Query Data 
- [x] Land type filter 
- [x] Commodity filter 
- [x] Grouping 
- [x] Change between fiscal and calendar year and change years 
- [x] Download matches selected data 
Download 
- [x] xls and csv files updated with correct dates and file size

Updated monthly disbursements data December 2020

Homepage	
- [x] Monthly bar charts (most recent 12 months, FY & CY)
- [x] CY bar charts
- [x] FY bar charts
- [x] Check Breakouts (Source & Recipient)
- [x] Check year over year comparison
- [x] Check month over month comparison
- [x] Source file links
Query Data 
- [x] Recipient Filter 
- [x] Source Filter 
- [x] State/offshore region filter 
- [x] Grouping 
- [x] Download matches selected data 
Download 
- [x] xls and csv files updated with correct dates and file size 

Updated annual production data FY 2020
Explore Data  
- [x] Switch between state and county 
- [x] Show offshore 
- [x] Switch between FY and CY 
- [x] Choose different commodities 
- [x] Add Nationwide federal card 
- [x] Add Native American Card 
- [x] Select different commodities 
- [x] Select different years, correct FY or CY displaying 
- [x] Summary Cards: correct state title, correct county & state title, trendline, accurate year, correct abbreviation for commodity selected 
- [x] Nationwide Federal Card:  % of federal land, total production for specified year,  trendline, accurate year, production over time trendline data, top locations data 
- [x] Detailed state cards: % of federal land, total production for specified year, correct state title, trendline, total production for specified year, top county data, counties map 
- [x] Detailed county cards: correct county & state title, total production for specified year, trendline, accurate year, production overtimes trendline 
- [x] Native American card: total production for specified year, trendline, accurate year, production overtime trendline 
- [x] Offshore card: total production for specified year, trendline, accurate year, production overtime trendline 
- [x] Check cards for states with no data 
- [x] Production over time trend line data 
- [x] Top Nationwide locations data 
Query Data 
- [x] Land type filter 
- [x] Commodity filter 
- [x] State/offshore region
- [x] Grouping 
- [x] Change between fiscal and calendar year and change years 
- [x] Download matches selected data 
Download  
- [x] xls and csv files updated with correct dates and file size

Updated Coal Excise Tax

Blog post about trends design studio

Added commodity for monthly disbursement query

Enhancements to query tool

Enhancement to pattern library

Enhanced loading status

Fixed horizontal nav menu

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@mojobnichols 
image

**Comment by Maroyafaied** [comment]
image

**Comment by lpgoldstein** [comment]
This is a little weird - I don't seem to be able to query for North Slope Borough in Alaska but can choose it from the map 
image

**Comment by mcharg** [comment]
@mojobnichols Can you take out the median line on the sparklines, since they're not showing up for disbursements? And it looks like they may just be connecting the start and end points and may not actually be the median.
image

**Comment by Maroyafaied** [comment]
@master12 @mojobnichols  Can you look into this issue Jennifer found in the query tool. Thanks
image

**Comment by mcharg** [comment]
@jlouis-onrr In Firefox, monthly FY, it's pulling Dec 2020 instead of Dec 2019.
image

It's also putting Dec in the wrong spot in the CY monthly view.
image

**Comment by mcharg** [comment]
IE doesn't even show the months.
image

**Comment by Maroyafaied** [comment]
@master12 can you default to 2020 for FY production in the query tool/ 
image

**Comment by mcharg** [comment]
@jlouis Safari also isn't showing the months or the comparison.
image

**Comment by jennmalcolm** [comment]
Revenue data that I've checked is looking good in Chrome, but since there are issues with other browsers I'll wait to check those before checking off.

**Comment by Maroyafaied** [comment]
@mcharg @jlouis-onrr Firefox looks good now

**Review by lpgoldstein — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@jlouis-onrr I just checked IE and it looks like everything @mcharg mentioned is fixed. The only thing I'm seeing is the comparison table is not aligned right when you're on the FY so far view. 
image

**Comment by jlouis-onrr** [comment]
@Maroyafaied, the labels in IE have been fixed and the errors that were being thrown.  There are still comparison issues in IE when comparing monthly.  Seems to be the way IE is slicing the substrings.

**Review by jennmalcolm — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@jlouis-onrr I'm not seeing comparison issues in IE when I compare monthly.  Can someone else check?
image

**Comment by lpgoldstein** [comment]
@Maroyafaied It looks fine to me in IE as well

**Pull request merged**
