### PR TITLE
Site audit for load time performance

### LINKED ISSUE #1101: Load time performance
Test load time with lighthouse when push a branch and push to production. Establish the baseline and then decide on appropriate % improve on needed pages. This will be tracked quarterly.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #1101
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1101-LoadTimePerformance)

Changes proposed in this pull request:

- updates jest lighthouse testing scripts
- creates lighthouse artifact in CircleCI that includes performance testing
- tests against your preview branch if exists otherwise tests against dev

### CODE REVIEW

**Comment by jlouis-onrr** [comment]
@mojobnichols, @Maroyafaied, You can now see the reports in CircleCiI under 1101-LoadTimePerformance

**Comment by mcharg** [comment]
@jlouis-onrr Does this still need to be reviewed?  If so, what should I look for?

**Comment by mcharg** [comment]
@jlouis-onrr Every page is listed twice in the report.  Do you know why?

**Review by mcharg — APPROVED** [review]

**Comment by jlouis-onrr** [comment]
@mcharg, check out the latest version (__audits__/lighthouse/lhreport__20210812.csv)

[audits/lighthouse/lhreport__20210812.csv](https://app.circleci.com/pipelines/github/ONRR/nrrd/3552/workflows/a5326ec3-2742-4aac-a59d-18cef8a78c16/jobs/10442/artifacts)

**Comment by mcharg** [comment]
@mcharg It looks good.

**Comment by Maroyafaied** [comment]
@mcharg I like how you tagged yourself in your last comment :) lol

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@mojobnichols can you please review this PR? @mcharg can you show @lpgoldstein how to pull the report from CircleCI so she can save it. Thanks

**Comment by mcharg** [comment]
@Maroyafaied Will do.

**Pull request merged**
