### PR TITLE
Apply new data query tool

### LINKED ISSUE #425: Need to update what happens when there is no data
Only display rows when there is data for at least one year the user has selected.

If there are years with no data in the user's selection, but numbers for at least one other visible year, the years with no data get a dash.

### PR DESCRIPTION
**Pull request by master12**
Fixes #425 #465 #356 #478 #462

[:sunglasses: PREVIEW](https://apply-new-data-query-tool.app.cloud.gov/query-data)

Changes proposed in this pull request:

- Updated queries with new DB tables
- Added county option
- Fixed styling issues

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@master12 is production data supposed to show? I'm not able to see any production data.

**Comment by Maroyafaied** [comment]
When you hit filter data, the dates show up in opposite order 
image

**Comment by Maroyafaied** [comment]
production does not have a header for total. 
image

**Comment by Maroyafaied** [comment]
@master12 when I filter for production data, it does not produce any results. I also tried with disbursement and I got "something went wrong" error.

**Comment by lpgoldstein** [comment]
overall disbursements annual summary numbers look good.

**Comment by lpgoldstein** [comment]
@master12 agree that the filter option by state doesn't seem to change the data in the table. Also is there supposed to be county data?

**Comment by mcharg** [comment]
We shouldn't be using ... to cut off labels.
image

**Comment by mcharg** [comment]
Clear Selected shouldn't be an option on the period drop-down.  If you select it, it still has years showing, but it's not clear whether they're fiscal or calendar. 
image

**Comment by mcharg** [comment]
For disbursements, the default grouping should be by recipient and then source, since state doesn't apply to all recipients.

**Comment by lpgoldstein** [comment]
LWCF listed twice 
image

**Comment by lpgoldstein** [comment]
"County" listed as a recipient without "State" is confusing since we don't do this anywhere else. We should list "State" as the overarching category and then county as a subcategory or breakout. 
image

**Comment by jennmalcolm** [comment]
Looks like the LWCF GOMESA is listed twice due to the difference in capitalization in the data, that's not a P1 in my mind as long as the data is right.

**Comment by jennmalcolm** [comment]
In disbursements filters "recipient" and "source" give the same options. We should use the options from the current query tool. As an example GOMESA should be a source, and LWCF should be a recipient, but  they are showing up together for both dropdowns.

image

image

I haven't tested the filtering for revenue yet, but it looks like production and disbursements are having problems, so maybe we can just take the filter out for the soft launch? We can discuss at sync up.

**Comment by jennmalcolm** [comment]
Here's the pivot table for the default revenue view
[revenue commodity pivot.xlsx](https://github.com/ONRR/nrrd/files/4718955/revenue.commodity.pivot.xlsx)

**Comment by jennmalcolm** [comment]
The revenue summary data is looking good.

**Comment by Maroyafaied** [comment]
Production data is looking good, my only suggestion is that we should add units to the commodities either at the list of commodities when filtering or in the table.

**Comment by Maroyafaied** [comment]
When filtering for revenue Native American, it blocks out the options of selecting State and county but gives you the option to select offshore region. That should blocked out as well. 
image

**Comment by lpgoldstein** [comment]
@master12 there are still some issues with disbursements and the state/county labels - county should read as state 
image

**Comment by lpgoldstein** [comment]
Here counties are listed without a state attached 
image

**Comment by lpgoldstein** [comment]
Cameron county and Cameron parish are being added together and they are different locations 
image
image

**Comment by jennmalcolm** [comment]
I checked revenue data include states with various filters and breakouts. Everything I checked looks good.

**Comment by mcharg** [comment]
The data's not showing up for me in the query tool this morning.
image

**Comment by mcharg** [comment]
And the old breakouts are in the filter drawer.
image

**Comment by mcharg** [comment]
And ctrl + f5 doesn't fix it.

**Comment by mcharg** [comment]
I also thought we were combining state and offshore region into one location filter like we have in the current tool, but can't check that with the bug noted above.

**Comment by jennmalcolm** [comment]
@mcharg you need to use the preview link in this PR because it's not in dev yet.

**Comment by mcharg** [comment]
@jennmalcolm Thank you.  It's early.

**Comment by jennmalcolm** [comment]
@master12 this branch has conflicts now.

**Comment by master12** [comment]
ok added a new county name column that combines, State Name, County and District Type, this will result in Virginia, Arlington County. This should also fix the aggregated sums issue where multiple counties have the same name in different states.

**Comment by master12** [comment]
Ok query tool pointed back at hasura-onrr, merge when ready

**Pull request merged**
