### PR TITLE
672 update query tool

### LINKED ISSUE #672: Update query tool toolbar
To match Explore Data styling:

### PR DESCRIPTION
**Pull request by master12**
Fixes #672 #681 #682

[:sunglasses: PREVIEW](https://672-update-query-tool.app.cloud.gov/query-data)

Changes proposed in this pull request:

- New design for query toolbar implemented
- Added error handling dialog
- Added new base slider for year range selections

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 The link styling isn't consistent on the download tab.  They should all be underlined like the last one.
image

Otherwise, looks good.

**Comment by mcharg** [comment]
Just got the network error. @master12 Do we have control over what the error says?
image

**Comment by mcharg** [comment]
@master12 It's displaying the error every time I change the years in the slider.  Should it be showing that frequently?  It's bringing back numbers most of the time.
image

**Comment by master12** [comment]
@mcharg Glad you saw the error msg, I need to clear the message. So I will fix that issue and underline the downloads

**Comment by mcharg** [comment]
@jennmalcolm Thoughts on the error message copy?

Something like: "We encountered an error retrieving the data."?

**Comment by master12** [comment]
@mcharg @jennmalcolm Also for the error message we could add, check your internet connection and refresh the browser to try again. Something like that...

**Comment by mcharg** [comment]
"We encountered a connection error retrieving the data. Check your internet connection and refresh your browser to try again."

**Comment by mcharg** [comment]
@master12 The slider is quirky if you pick a single year.  I slid both sliders to 2019 and now I only have a single slider that won't let me pick any year.
image

**Pull request merged**
