### PR TITLE
1468 query tool bug

### LINKED ISSUE #1642: Bug: Query tool displays no data when you click "clear all"
@CM805 found this issue when reviewing data, if you choose filters then click clear all, you get this 
image

### LINKED ISSUE #1648: Oil & gas (pre-production) missing in query tool for revenue FY
The "Oil &Gas (pre-production) is not on the list of commodities for revenue fiscal year but it's there for CY and monthly. 

image

image

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #1648
Also Fixes #1642
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1468-QueryToolBug/)

Changes proposed in this pull request:

Oil & gas (pre-production) had same commodity order as Oil shale added separate order for each as the graphql query would loose track of one.   

Clear all was error in the case of period and fiscal year causing no data to return due to the aggregation not being set correctly.   Modified so aggregation gets set correctly for period and fiscal year

-
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@mojobnichols Not sure if this is specific to this PR, but after applying filters, the months are showing up as numbers.
image

**Review by mcharg — APPROVED** [review]
Looks good.

**Review by cthomasONRR — APPROVED** [review]
Looks good!

**Comment by cthomasONRR** [comment]
@mojobnichols 

I'm re-checking like you asked and got the grey screen again. I filtered to the parameters below:
image

The switched from Production to Revenue, and that caused they grey screen again:
image

I haven't been able to replicate the Month-Numbers bug though!

**Pull request merged**
