### PR TITLE
Production Tab Performance 

### LINKED ISSUE #1547: Homepage Production Aggregation

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #1547

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1547-HomepageProductionAggregation)

Changes proposed in this pull request:

Six queries reduced to one cause performance boost to production tab.  

-
-
-

### CODE REVIEW

**Comment by mojobnichols** [comment]
@jlouis-onrr Can you look at the alignment issue on comparision to chart?

**Comment by mcharg** [comment]
@mojobnichols Getting a graphql error on the Production tab.

**Review by mcharg — APPROVED** [review]

**Review by jlouis-onrr — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@mojobnichols @jlouis-onrr The monthly fiscal year 2020 view is not displaying the correct months, it should be showing Oct 2019 to Sep 2020. 
image

**Comment by Maroyafaied** [comment]
@mojobnichols @jlouis-onrr Also, the comparison table is not lining up correctly when I choose coal. 
image

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
