### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- [x] Updated color in glossary page to be accessible 
- [x] Added glossary terms for query table state/offshore labels
- [x] Published [blog post about homepage graphics redesign](https://dev-blog-nrrd.app.cloud.gov/homepage-graphic/)
- [x] Published [blog post about contacts design for onrr.gov](https://dev-blog-nrrd.app.cloud.gov/contacts/)

**Published monthly revenue data** 	

- [x] Make sure the downloaded data matches the raw data. [Raw data ](https://teams.microsoft.com/l/file/0AC26312-0696-44D9-A1FF-5AF7C83AEE0B?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FRevenue%2FFY%202021%2FJuly%202021%20Revenue%20for%20Portal.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout Commodity
 
Homepage - Source File
- [x] Check source file links are correct.
 
Query Data
- With a selected fiscal or calendar year range, verify the data is correct and then for the conditions below. 
   - [x] One Land Type filter
   - [x] One Revenue Type filter
   - [x] One State (for Yearly data only)
   - [x] One Offshore Region
   - [x] One to three Commodities
   - [x] Clear All and change grouping
   - [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**Published monthly disbursements data**

- [x] Make sure the downloaded data matches the raw data. [Raw data](https://teams.microsoft.com/l/file/C7F9B142-34EF-4ECB-B116-B8A6D88612F2?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FDisbursements%2FFY21%2FQ3%20Total%20Web%20Data%20(Jun).xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)
- [x] Check Treasury Fund column is deleted
- [x] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [x] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- [x] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Breakout - Source 
- [x] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

 **Published monthly production data** 

- [x] Make sure the downloaded data matches the raw data. [Raw data ](https://teams.microsoft.com/l/file/0CCC699F-6A92-41BC-9969-E5C778C174FA?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FProduction%2FFY%202021%2FProduction%20Volumes%20as%20of%208-3-2021.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Source File
- [x] Check source file links are correct.

Query Data
- [x] One Land Type filter
- [x] One State
- [x] One Offshore Region
- [x] One to three Products
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

### CODE REVIEW

**Comment by mcharg** [comment]
@Maroyafaied The new blog posts aren't showing up.  Are you going to merge those before merging this?

**Comment by Maroyafaied** [comment]
@mcharg Yes, I'll merge at them at the same time as the release. I added the links to them in the checklist. We probably should change the date on both to match the release data. Do you have time to do that?

**Comment by mcharg** [comment]
@Maroyafaied Yes, I can update the dates on the blogs.

**Review by cthomasONRR — APPROVED** [review]
I reviewed:

- [x] Updated color in glossary page to be accessible
- [x] Added glossary terms for query table state/offshore labels
- [ ] Published blog post about homepage graphics redesign
- [ ] Published blog post about contacts design for onrr.gov
- [ ] Published monthly revenue data

Everything looks great! I approve :)

**Review by mcharg — APPROVED** [review]
Disbursements data looks good.

**Review by meshanw — APPROVED** [review]

**Review by Baymatt — APPROVED** [review]
Production data looks good

**Pull request merged**
