### PR TITLE
Left nav

### LINKED ISSUE #369: Wrong section highlighting in left nav
The Accountability section should be highlighting instead of resources to revenuw - I clicked on the accountability link in the intro text at the top of the page.

### PR DESCRIPTION
**Pull request by mcharg**
Fixes #369

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/left-nav/how-revenue-works)

Changes proposed in this pull request:

- Adds breaks to the bottom of the page, so the left nav highlights the right section
- Rewords title for how datasets fit section
- Adds Oxford commas to Ownership and Revenue cards

### CODE REVIEW

**Comment by mcharg** [comment]
The breaks help a little bit, but the left nav is still a little wonky and not always highlighting the right item.

**Review by cthomasONRR — APPROVED** [review]
Looks good!

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@jlouis-onrr can you please review this PR? Thanks

**Comment by jlouis-onrr** [comment]
@mcharg, Looks good.  I did notice that the header tag has a alt attribute assigned to it.  This is symmetrically incorrect and should not be included inside of the header tag.  alt attributes should only be assigned to image tags.

See:
`<h2 alt='Our data'>How our data fits together</h2>`

**Comment by mcharg** [comment]
@jlouis-onrr I think that's how Jeff assigned different text to appear in the left nav from what's in the section title.

**Comment by jlouis-onrr** [comment]
@mcharg, I'm going to look at how the side nav is grabbing the titles.  It shouldnt be using alt tags.

**Review by jlouis-onrr — APPROVED** [review]
@mcharg, looks like it is grabbing by alt tag.  Instead it should be grabbing by id.  Which should get addressed in #1687

**Pull request merged**
