### PR TITLE
FY 21 production & CY 21 revenue by company

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/new-data/)

Changes proposed in this pull request:

- FY 21 production 
- CY 21 revenue by company
-

### CODE REVIEW

**Comment by cthomasONRR** [comment]
**Production Calendar Year or Fiscal Year**
	
- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Explore Data - Map and Detail Card 
- Select a year and select a state with data, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected
 
- Select a year and select a county with data, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected.
 
- Select a year and select an offshore area, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected.
 
- [ ] Select a state and county without data and verify the expected information is displayed.
- [ ] Add Nationwide Federal Card and verify the expected information is displayed.
- [ ] Add Native American Card and verify the expected information is displayed.

Explore Data - Nationwide Production Summary and Top Nationwide Locations
- Verify breakdowns by production type and source are correct as well nationwide locations for the conditions below.
    - [ ] Not current Calendar Year
    - [ ] Current Calendar Year
    - [ ] Not current Fiscal Year
    - [ ] Current Fiscal Year

Query Data, in the 'Period' category, filter to either 'Calendar Year' or 'Fiscal Year' and check the following:
- [ ] One Land Type filter
- [ ] One State
- [ ] One Offshore Region
- [ ] One to three Product
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by cthomasONRR** [comment]
**Revenue by Company**

Download Page
- [ ] Dates and file size are correct for csv and excel
- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Explore Data - Click on the "Federal revenue by company" link below the map
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
  - [ ]  One to three Companies
  - [ ]  Revenue Types within a Company
  - [ ]  One to three Commodities
  - [ ]  Check the Top 10 Companies (highest revenue) to ensure revenue sums and their percent of total is correct
  - [ ]  Check "Other Companies" to ensure that the revenue sum and percent of total is correct

Query Data - In the "Data Type" category, filter to "Federal revenue by company"
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
  - [ ]  One to three Companies
  - [ ]  One to three Revenue Types
  - [ ]  One to three Commodities
  - [ ]  Clear All and change grouping
  - [ ]  Download matches filtered data

**Comment by cthomasONRR** [comment]
@Maroyafaied All the data look good!!!!

**Comment by cthomasONRR** [comment]
@lpgoldstein If you have time, want to do a second review? Everything should be working and data should be correct!

**Comment by Maroyafaied** [comment]
@mojobnichols for revenue by company in the query tool, under revenue type, this shows up twice. Is this an easy fix to do now before we release or should I make a bug issue for it to be fixed later? 
image

**Comment by cthomasONRR** [comment]
@Maroyafaied Interesting, I don't see it duplicated: 
image

**Comment by Maroyafaied** [comment]
@cthomasONRR I see it when I have the filter for years 2017-2021, but it doesn't happen if you're only on year 2021. I'm going to merge this PR to dev and create an issue for Mojo to look at this later. @lpgoldstein you can review data once it's in dev.

**Pull request merged**
