### PR TITLE
Release changes v6.2.2

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release-changes-v6.2.2/)

Changes proposed in this pull request:

- what's new

### CODE REVIEW

**Comment by mcharg** [comment]
@Maroyafaied Should the link to the new how it works page go directly to that page instead of the main how revenue works page?

**Comment by mcharg** [comment]
Otherwise, looks good.

**Review by mcharg — APPROVED** [review]

**Comment by mcharg** [comment]
I'm actually not even seeing the new page listed on the main how revenue works page.

**Comment by Maroyafaied** [comment]
@mcharg the page is listed in dev site , it's not live yet that's why it doesn't show.

**Pull request merged**
