### PR TITLE
Cleaned up console.debug statements; Got offshore Pacific Region to d…

### LINKED ISSUE #511: Offshore cards not working
This is related to #410 since it's an offshore issue. The offshore data is showing on the map for revenue, but the cards do not come up when an area is clicked or searched. Also the offshore options in the search box still show the planning areas. We should include only the offshore region.

### PR DESCRIPTION
**Pull request by mojobnichols**
…isplay

Fixes #511

[:sunglasses: PREVIEW](https://511-OffshoreCards.app.cloud.gov/explore/)

Changes proposed in this pull request:
Offshore region now opens cards with data about that region. 

-
-
-

### CODE REVIEW

**Comment by Maroyafaied** [comment]
Pacific offshore region production data is accurate. I'm not sure if this abbreviation was meant to be in the heading title? 
image

**Comment by mojobnichols** [comment]
Let's create a new issue for that - I started to fix it but it's not really the same component or problem.   It's happening in both Revenue and Production.

**Comment by jennmalcolm** [comment]
I checked revenue data, and its looking good. 

The revenue type part of the offshore cards isn't working. image
Also, the offshore area icons are showing up like this. I think we can get rid of the icons for the offshore areas, like we do for the counties. image

The nationwide map is showing up on the bottom of the detailed cards for everything except Pacific (not sure if that's what the comment about only Pacific working means).

Do you want separate issues about these items or to fix them here @mojobnichols?

**Comment by Maroyafaied** [comment]
I checked production data for all the regions and they are accurate. The production over time trend chart is not showing up and we should be consisted with labeling. For example, on the card it says "Gulf of Mexico" but on the top location table it says "Offshore Gulf".
image

image
image

**Comment by mojobnichols** [comment]
Should top locations be on offshore card - On state card it is the top locations of the state (top counties).   On offshore its all the top locations.

**Comment by Maroyafaied** [comment]
@mojobnichols the data and the trendlines look good. I personally don't think top locations should be on the offshore cards since it's very repetitive and the same information as the top nationwide chart below.  To stay consistent, the label in the nationwide card should be "Gulf of Mexico" instead of "Offshore Gulf".  
image
****
image

**Comment by mojobnichols** [comment]
Closing pull request as branch is broken on rendering Footer. f

**Pull request closed without merging**
