### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

## Updated monthly production (Dec 2020)
Homepage - Yearly Breakdown
- [x] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- [x] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Source File
- [x] Check source file links are correct.

Query Data
- [x] One Land Type filter
- [x] One State
- [x] One Offshore Region
- [x] One to three Product
- [x] Downloads matches filtered data
- [x] Monthly data is correct

Download Page
- [x] Dates and file size are correct for csv and excel

Fact sheet
- [x] Production numbers are correct

## Updated monthly disbursements (Feb 2021)
Homepage - Yearly Breakdown
- [x] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Breakout - Source 
- [x] Breakout - Recipient
 
Homepage - Monthly Breakdown
- [x] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data
- [x] Monthly data

Download Page
- [x] Dates and file size are correct for csv and excel
- [x] Download file matches original file.

Fact Sheet
- [x] Monthly disbursements numbers are correct

## Updated monthly revenue (March 2021)
Homepage - Yearly Breakdown
- [x] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout - Commodity
 
Homepage - Monthly Breakdown
- [x] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout Commodity
 
Homepage - Source File
- [x] Check source file links are correct.
 
Explore Data - Map and Detail Card
- [x] Select a year and select a state with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [x] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected
 
- [x] Select a year and select a county with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [x] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected.
 
- [x] Select a year and select an offshore area, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [x] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected.
 
- [x] Select a state and county without data and verify the expected information is displayed.
- [x] Add Nationwide Federal Card and verify the expected information is displayed.
- [x] Add Native American Card and verify the expected information is displayed.

Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- [x] Verify breakdowns by revenue type and source are correct as well nationwide locations for the conditions below.
    - [x] Not current Calendar Year
    - [x] Current Calendar Year
    - [x] Not current Fiscal Year
    - [x] Current Fiscal Year

Query Data
- [x] With a selected fiscal or calendar  year range, verify the data is correct and then for the conditions below. 
- [x] One Land Type filter
- [x] One Revenue Type filter
- [ ] One State
- [ ] One Offshore Region
- [x] One to three Commodities
- [x] Clear All and change grouping
- [x] Downloads matches filtered data
- [x] Monthly numbers are correct

Download Page
- [ ] Dates and file size are correct for csv and excel

Fact Sheet
- [x] Revenue numbers are correct

## Other changes
**- [ ] Added how data set fit together diagram**
**- [ ] Enhanced loading on homepage**
**- [ ] Added loading indicator in query tool**

### CODE REVIEW

**Comment by mcharg** [comment]
February 2021 disbursements are missing from monthly views of the homepage and query tool.
image

image

**Comment by Maroyafaied** [comment]
@mojobnichols dev doesn't seem to have the most recent data updates anymore , neither do the files?

**Comment by Baymatt** [comment]
Production Monthly Breakdown on the Homepage has calendar year 2019 and 2020 showing up, unsure if its intended to have both.

Screen Shot 2021-04-14 at 4 38 28 PM

**Comment by mcharg** [comment]
Disbursements data all looks good.

**Comment by Maroyafaied** [comment]
@master12 an error also occurs in the query tool when you're on revenue and try to filter for state/offshore. 
image

**Comment by Maroyafaied** [comment]
@mojobnichols I'm getting a different file size for the monthly revenue csv, all the other file sizes look correct. 
image

**Comment by Baymatt** [comment]
Monthly production looks good

**Review by mcharg — APPROVED** [review]

**Review by master12 — APPROVED** [review]

**Pull request merged**
