### PR TITLE
fy17 disbursements

### LINKED ISSUE #2024: Upload and Review FY 2017 monthly disbursements by commodity

### PR DESCRIPTION
**Pull request by lpgoldstein**
Fixes #2024 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/datadownloads/)

Changes proposed in this pull request:

- fy17 disbursements

### CODE REVIEW

**Review by cthomasONRR — APPROVED** [review]
Disbursements reviewed, looks good to me. Approve :)

**Comment by cthomasONRR** [comment]
Added 12/21 Production & 3/22 Revenue

**Comment by cthomasONRR** [comment]
**Production Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Source File
- [ ] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Land Type filter
- [ ] One to three Products
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
**Revenue Monthly** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout Commodity
 
Homepage - Source File
- [ ] Check source file links are correct.
 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [ ] One Land Type filter
   - [ ] One Revenue Type filter
   - [ ] One State (for Yearly data only)
   - [ ] One Offshore Region
   - [ ] One to three Commodities
   - [ ] Clear All and change grouping
   - [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
@lpgoldstein @Maroyafaied I just checked revenue. Everything looks good except that the monthly fact sheet is updated within the 'What's New' box, and NOT updated in the link with the "Fact Sheets" tab. 

Looks like Production is doing the same (not updated within "Fact Sheets" tab), but haven't done a thorough Production review yet.

**Comment by cthomasONRR** [comment]
@Maroyafaied For Production - Monthly - Calendar Year, it did not update to show CY 21:
image
Production - Yearly - Calendar Year DID update to include CY 21 though

**Comment by Maroyafaied** [comment]
@cthomasONRR the calendar year file is different from the monthly file for production, the monthly production file only has 3 commodities (oil, gas, coal) and the yearly file has all.  I'll ask @mojobnichols about the monthly view not updating to show calendar year 2021 for production, hopefully it's an easy fix since it shows for revenue.

**Comment by Maroyafaied** [comment]
@cthomasONRR also the fact sheet link within the tab is linking to the live site so it won't be updated until I release.

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks for the clarifications! I checked the rest of the production data yesterday, and Production - Monthly - Calendar Year not updating to CY 21 is the only issue I saw. Other than that, data looks good!

**Comment by Maroyafaied** [comment]
@mojobnichols It says now CY 2021 but the data displayed is CY 2020.

**Comment by cthomasONRR** [comment]
@Maroyafaied @mojobnichols All the data look good now!

**Review by cthomasONRR — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein just FYI, I'm waiting on March's disbursements data before I release, we should be getting it this week.

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein we need to change the date in disbursements monthly download page to say 2016 instead of 2017. We can make this change when we receive March's data which will probably be on Monday.
image

**Comment by lpgoldstein** [comment]
**Disbursements Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [ ] Check Treasury Fund column is deleted
- [ ] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [ ] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [ ] Breakout - Source 
- [ ] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Recipient
- [ ] One Source
- [ ] One State
- [ ] One to three Commodities if applicable
- [ ] Clear All and change grouping
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Pull request merged**
