### PR TITLE
Update aml-reclamation-program.mdx

### LINKED ISSUE #1245: Thorough audit and update of AML page
Notes from content audit: Grade level up; need to update data from 2017 or just revise to remove those data points; many linked documents seem very out of date

Manually curated data: Yes: per-ton fees; fund distribution; state and tribal spending; percentage for acid mine drainage; static chart; grants to states and tribes; the fund today; allocation of balance

### PR DESCRIPTION
**Pull request by lpgoldstein**
Fixes #1245

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/amlupdates/)

Changes proposed in this pull request:

- updates text
- removes manually curated data points

### CODE REVIEW

**Comment by jennmalcolm** [comment]
This has some issues. It's all the way on the left, and you can see the title and tags. If you want me to work on it, let me know. 
image

**Comment by lpgoldstein** [comment]
@jennmalcolm yes please. I thought it was an issue with my browser.

**Comment by jennmalcolm** [comment]
I fixed the front matter problem. There is also an issue with not having spaces in all spots that should. In order to fix this, I've had to use html for breaks (and the following links). I won't be at syncup next week, but it seems like it might be good to talk to the developers to see if there's a different solution.

**Comment by Maroyafaied** [comment]
@master12 please look if there is a solution to the spacing issue.

**Comment by lpgoldstein** [comment]
Moving this because still having build issues

**Review by jennmalcolm — APPROVED** [review]

**Comment by jennmalcolm** [comment]
@lpgoldstein I got it to build, and it should be good to go now.

**Pull request merged**
