### PR TITLE
Accessible legend swatches, sliders, toggles, and switch controls

### LINKED ISSUE #1030: Year slider, toggle, and switch controls are not accessible
They don't show up correctly when viewed using contrasting colors.  Seen in both IE and Edge during a user interview.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #1030, #1031

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1031-ChartLegendSwatchesNotAccessible/explore)

Changes proposed in this pull request:

- adds ms-high-contrast styles to add borders around mui elements that don't show up in windows high contrast mode
- updates chart legend swatches to be svg elements using attrs instead of styled elements using css
- [WARNING]: use care when testing in high contrast mode - can make you dizzy

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr The toggle still isn't differentiated.
image

**Comment by mcharg** [comment]
@jlouis-onrr On the homepage, some of the icons turn yellow and some don't.
image

**Comment by mcharg** [comment]
The current logo doesn't show up, but that will be fixed with the new logo.
image

**Comment by jlouis-onrr** [comment]
@mcharg, Im seeing the active states for toggle buttons in high contrast.  
active_map_level_toggle
active_home_yearly_monthly

**Comment by mcharg** [comment]
@Maroyafaied Are you seeing the toggle selections?

**Comment by jlouis-onrr** [comment]
@mcharg, just remembered that you are running the older, non-chromium version of edge.  I need to see if I can recreate a high contrast mode in older edge in a vm.

**Comment by jlouis-onrr** [comment]
@mcharg, just confirmed, the issues with active links not highlighting is occurring in legacy edge

**Comment by Maroyafaied** [comment]
@mcharg yes I see it. 
image

**Comment by Maroyafaied** [comment]
@mcharg @jlouis-onrr The only color that doesn't show up for me are on the summary & detailed cards (line under title).
image
image

**Comment by mcharg** [comment]
@jlouis-onrr It's working now. 
image

**Review by mcharg — APPROVED** [review]

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
