### PR TITLE
561 query toolbar - Ready to merge when approved

### LINKED ISSUE #561: Move query tool controls to top bar and use styling from the Explore Data page for controls
Design is in #557

### PR DESCRIPTION
**Pull request by master12**
Fixes #561 #463 #431 #532 #590 #558 

[:sunglasses: PREVIEW](https://561-query-toolbar.app.cloud.gov/query-data)

Changes proposed in this pull request:

- [x] Toolbars added for filters and grouping
- [x] Drop downs updated
- [x] Download buttons moved to toolbar
- [x]  documentation links added
- [x] state and offshore combined
- [x] Product used vs Commodity for production data (adds units to name)

### CODE REVIEW

**Comment by master12** [comment]
DO NOT MERGE UNTIL DB IS UPDATED

**Comment by mcharg** [comment]
I added #590 to get the download function added to this.  We shouldn't merge without that.

**Comment by mcharg** [comment]
Creates #591 for hooking up the database.

**Comment by mcharg** [comment]
Added @lpgoldstein and @Maroyafaied as reviewers to check the data.

**Comment by Maroyafaied** [comment]
For production data, it's pulling products that have no volume and shouldn't be there. 
image

**Comment by master12** [comment]
@lpgoldstein @Maroyafaied @jennmalcolm Hey this is ready for your review.

**Comment by Maroyafaied** [comment]
@master12 is this supposed to say "All states" 
image

**Comment by Maroyafaied** [comment]
@master12 it's listing products that have no volume, this example is for Native American production. I checked the excel sheets and those commodities are not listed there. 
image

**Comment by jennmalcolm** [comment]
I thought we were just going to say total at the bottom row because we it's not necessarily "All" of anything because of the filters?

**Comment by master12** [comment]
created #634 to fix the total row text @jennmalcolm

**Comment by master12** [comment]
@Maroyafaied Created issue #635 to remove rows with no values

**Comment by mcharg** [comment]
Are we going to merge this with @jlouis-onrr's PR, so we can see what it's going to look like with the styling.  Thinking we need to add a Query Data tab like we have for Explore Data to match and as a header - maybe the data type drop-down could go in that tab?

**Comment by mcharg** [comment]
Not sure if this will be moot after merging with @master12's PR, but when I click on the query disbursements link from explore data, it brings up the query tool filtered to disbursements, but the data type drop-down is missing.
image

**Comment by master12** [comment]
The plan is to verify the fixes for the listed issues are done and I will merge to dev and then jerome can merge his style updates when ready.

**Pull request merged**
