### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)
Changes proposed in this pull request:

**- Update Native American revenue page**
**- Added monthly fact sheet**
**- Added blog post - Jennifer's lessons as product manager** 
**- Added trendlines to database**
**- Enhancements to explore data (map control, glossaries to circle charts, fix year slider bugs)**
**- Refactored database to use consolidated revenue monthly file**
**-Added state and offshore region pages for SEO**
**- Updated production monthly file Nov 2020**

Homepage - Yearly Breakdown
- [x] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
  - [x] Period - Fiscal Year
  - [x] Period - Calendar Year
  - [x] Commodity - Oil (bbl)
  - [x] Commodity - Gas (mcf)
  - [x] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- [x] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
  - [x] Period - Most recent 12 months
  - [x] Period - Fiscal Year
  - [x] Period - Calendar Year
  - [x] Commodity - Oil (bbl)
  - [x] Commodity - Gas (mcf)
  - [x] Commodity - Coal (tons)

Homepage - Source File
- [x] Check source file links are correct.

Query Data
- [x] One Land Type filter
- [x] One Product
- [x] Add a second column
- [x] Downloads matches filtered data
            
Download Page
- [x] Dates and file size are correct for csv and excel

**- Updated disbursement monthly file Jan 21**
Homepage - Yearly Breakdown
- [x] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
  - [x] Breakout - Source 
  - [x] Breakout - Recipient 
      
Homepage - Monthly Breakdown
- [x] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
  - [x] Period - Most recent 12 months
  - [x] Period - Fiscal Year
  - [x] Period - Calendar Year
  - [x] Breakout - Source
  - [x] Breakout - Recipient
      
Query Data
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data
      
Download Page
- [x] Dates and file size are correct for csv and excel
 
**- Updated monthly revenue Feb 21 and CY 20 revenue**
Homepage - Yearly Breakdown
- [x] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
  - [x] Period - Fiscal Year
  - [x] Period - Calendar Year
  - [x] Breakout - Source
  - [x] Breakout - Revenue Type
  - [x] Breakout - Commodity
      
Homepage - Monthly Breakdown
- [x] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
  - [x] Period - Most recent 12 months
  - [x] Period - Fiscal Year
  - [x] Period - Calendar Year
  - [x] Breakout - Source
  - [x] Breakout - Revenue Type
  - [x] Breakout Commodity
       
Homepage - Source File
- [x] Check source file links are correct.
      
Explore Data - Map and Detail Card
- [x] Select a year and select a state with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
  - [x] Period - Calendar Year
  - [x] Period - Fiscal Year
  - [x] With only 2-3 commodities selected

- [x] Select a year and select a county with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
  - [x] Period - Calendar Year
  - [x] Period - Fiscal Year
  - [x] With only 2-3 commodities selected.

- [x] Select a year and select an offshore area, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
  - [x] Period - Calendar Year
  - [x] Period - Fiscal Year
  - [x] With only 2-3 commodities selected.

- [x] Select a state and county without data and verify the expected information is displayed.
- [x] Add Nationwide Federal Card and verify the expected information is displayed.
- [x] Add Native American Card and verify the expected information is displayed.
      
Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- [x] Verify breakdowns by revenue type and source are correct as well nationwide locations for the conditions below.
  - [x] Not current Calendar Year
  - [x] Current Calendar Year
  - [x] Not current Fiscal Year
  - [x] Current Fiscal Year

Query Data
- [ ] With a selected fiscal or calendar  year range, verify the data is correct and then for the conditions below. 
  - [x] One Land Type filter
  - [x] One Revenue Type filter
  - [x] One State
  - [x] One Offshore Region
  - [x] One to three Commodities
  - [x] Clear All and change grouping
  - [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

State/offshore pages
Check a couple of state pages (url format: https://dev-nrrd.app.cloud.gov/explore/states/WY/) 
 - [x] Explore links work
 - [x] Query links work
 - [x] Ownership percentages are correct
 - [x] Check a state with no data and make sure a page doesn't display (url: https://dev-nrrd.app.cloud.gov/explore/states/ME/)
 
Check a couple of offshore pages (url format: https://dev-nrrd.app.cloud.gov/explore/offshore-regions/gulf/)
 - [x] Explore links work
 - [x] Query links work

### CODE REVIEW

**Comment by mcharg** [comment]
Revenue by company isn't displaying.
image

**Comment by mcharg** [comment]
Disbursements Excel file size is way off.
image
image

**Comment by mcharg** [comment]
@jlouis-onrr On the state page, when I click on any of the Explore links for Wyoming, it's not adding the Wyoming card.
image

**Comment by Maroyafaied** [comment]
@mcharg I'm getting the size as 479 KB, can someone else check? 
image

**Comment by mcharg** [comment]
@Maroyafaied I bet it's because I added a pivot table to the doc.  I just downloaded it fresh and got 480 KB.

**Comment by mcharg** [comment]
@jlouis-onrr Same thing for the Explore links on the offshore page.

**Comment by Baymatt** [comment]
I was looking at the monthly revenues on the homepage and the numbers look off for Federal - Not tied to a lease and Federal Offshore revenue.

Screen Shot 2021-03-18 at 1 53 09 PM
Screen Shot 2021-03-18 at 1 55 13 PM

**Comment by Baymatt** [comment]
Noticed some blanks on the Calendar Year Nationwide Federal and Native American detail cards on the Explore data page

Screen Shot 2021-03-18 at 2 08 33 PM
Screen Shot 2021-03-18 at 2 08 39 PM

**Comment by mcharg** [comment]
Native American still has a blank in Revenue Type.  Nationwide appears to be fixed.
image

**Comment by mcharg** [comment]
@master12 The query tool default isn't showing the 3 most recent years.
image

**Comment by mcharg** [comment]
@master12 Monthly disbursements are missing GOMESA and 8(g) from the source filter and the source column.
Dev:
image

Live site:
image

**Comment by mcharg** [comment]
@master12 On monthly disbursements, I picked just oil, geothermal, and potassium, but it's still showing all commodities.
image

**Comment by Maroyafaied** [comment]
> @Maroyafaied I bet it's because I added a pivot table to the doc. I just downloaded it fresh and got 480 KB.

I fixed the size in dev.

**Comment by Maroyafaied** [comment]
> Noticed some blanks on the Calendar Year Nationwide Federal and Native American detail cards on the Explore data page
> 
> Screen Shot 2021-03-18 at 2 08 33 PM
> 
> Screen Shot 2021-03-18 at 2 08 39 PM

The data base sums up everything as "Federal -not tied to a lease" if the land category is offshore but the region is listed as not tied to a lease. If you sum up the highlighted fields in the the file , it'll match the database. 
image

**Comment by Maroyafaied** [comment]
> Noticed some blanks on the Calendar Year Nationwide Federal and Native American detail cards on the Explore data page
> 
> Screen Shot 2021-03-18 at 2 08 33 PM
> 
> Screen Shot 2021-03-18 at 2 08 39 PM

The data base sums up everything as "Federal -not tied to a lease" if the land category is offshore but the region is listed as not tied to a lease. If you sum up the highlighted fields in the the file , it'll match the database.

**Comment by Maroyafaied** [comment]
@Baymatt The data base sums up everything as "Federal -not tied to a lease" if the land category is offshore but the region is listed as not tied to a lease. If you sum up the highlighted fields in the the file , it'll match the database. 
image

**Comment by mcharg** [comment]
@master12 When I click the clear all button on monthly production, the product column disappears, month moves to the left and the column 1 header goes above numbers.
image

**Comment by mcharg** [comment]
@jlouis-onrr The selected state on the homepage charts isn't working. At first, I thought it was just Firefox and Edge, but now I'm seeing it in Chrome.  It's not highlighting the selected year/month and changing to smaller font after it's been selected.
image

**Comment by master12** [comment]
@mojobnichols Monthly disbursements are missing GOMESA and 8(g) from the source filter and the source column.

See above with shannon's comment. Not sure why this is not showing.

**Review by mcharg — APPROVED** [review]

**Review by mcharg — APPROVED** [review]

**Review by master12 — APPROVED** [review]

**Review by mojobnichols — APPROVED** [review]

**Pull request merged**
