### PR TITLE
Added county data to state cards

### LINKED ISSUE #72: Explore Data: Add county data to map and cards

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #72 

[:sunglasses: PREVIEW](https://72-CountyData.app.cloud.gov/explore/)

Changes proposed in this pull request:

Summary cards have county data. 
-
-
-

### CODE REVIEW

**Comment by mentastc** [comment]
@mojobnichols  sorry I should have reviewed this awhile ago but now the preview link doesn't work

**Comment by mcharg** [comment]
@mojobnichols This PR has been out here for a while.  Can it be closed?

**Comment by mojobnichols** [comment]
And it was merged in already by hand.   I'm closing

**Comment by mojobnichols** [comment]
I also deleted the branch after review of changes, whatever was committed after merge with dev was minor or maybe even accidental.   re-merging to dev now would not be worth the testing effort.

**Pull request closed without merging**
