### PR TITLE
Added download file stub (WIP)

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes 1181
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1181-GenerateDownload)

Changes proposed in this pull request:

Uses a metadata file and xls files to create download links from the database.  Files are generated upon upload of data to nrrd-data.    Work in progress it is currently only monthly revenue and the old files are still in place for comparison. 

-
-
-

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@mojobnichols , Jennifer asked you about this already but just as a reminder if you can add 3 links to the revenue download page, 
1. Revenue by month
2. Revenue by Calendar Year
3. Revenue by Fiscal Year

**Comment by lpgoldstein** [comment]
Link to download file - https://nrrd-preview.app.cloud.gov/sites/1181-GenerateDownload/downloads/monthly_revenue.xlsx

**Comment by lpgoldstein** [comment]
Didn't hit comment with the sentence below a few hours ago so here it is now - not sure if still relevant: 

download file showing some columns as blank. Need to decide which columns we want to users to see and which are just for developers.

**Comment by mojobnichols** [comment]
Okay I put in hack to make relative links work for these downloads.

**Pull request merged**
