### PR TITLE
Revenue table: change to old headings and combine rents&fee

### LINKED ISSUE #415: Rename headings for revenue table
Relates to issue #272  Rename headings to "Secure Lease or Claim, Before production, and During Production" . Also, combine rents & fees together under the Before production phase instead of separating them out as we do now.

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #415 

[:sunglasses: PREVIEW](https://revenuetable.app.cloud.gov/how-revenue-works/revenues)

Changes proposed in this pull request:

- Rename headings to "Secure Lease or Claim, Before production, and During Production"
- Combine rents & fees together under the Before production phase

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@mojobnichols can you help me figure out why this build fails right away? Thanks

**Comment by Maroyafaied** [comment]
@mojobnichols @jennmalcolm the information should be correct but I don't know how to format these lines?
image

**Comment by jennmalcolm** [comment]
The phase and line seems like it's in the right place to me. I guess the only difference in the past version was that "Phase" was centered over the line. I can look into that. The alignment of the headings for hardrock minerals is also off. Do you want me to look at this @Maroyafaied? 

image

**Comment by Maroyafaied** [comment]
@jennmalcolm yes please if you have time. Thanks

**Pull request merged**
