### PR TITLE
Dev-->Master 

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

**- Added disclaimer in [glossary ](https://dev-nrrd.app.cloud.gov/glossary)**

**- Added [Meshan's blog post](https://dev-blog-nrrd.app.cloud.gov/Cross-training/)** 

**- Added disclaimer for company name in revenue by company data [download page](https://dev-nrrd.app.cloud.gov/downloads/federal-revenue-by-company/)**

**- Added [FY 18 monthly disbursement data](https://dev-nrrd.app.cloud.gov/downloads/disbursements-by-month/)** 

- [x] Make sure the downloaded data matches the[ raw data](https://teams.microsoft.com/l/file/FCB0BE00-A034-48D1-8E1B-A4262AA0AE98?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FDisbursements%2FFY18%2Ffiscal_year_disbursements%202018%20update.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Explore Data - Map and Detail Card
- With a fiscal year selected, verify the detail card and Disbursements Over Time are correct for the conditions below. Repeat with the current fiscal year.
    - [x] State with data
    - [x] State without data
    - [x] County with data
    - [x] County without data
    - [x] Nationwide Federal Card
    - [x] Native American Card

Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- Verify breakdowns by disbursement recipient and source are correct as well nationwide recipients for the conditions below.
    - [x] Not current Fiscal Year
    - [x] Current Fiscal Year

Query Data - In the 'Period' category, filter to 'Fiscal Year' and check the following:
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

- **Added [August 2021 monthly disbursement data ](https://dev-nrrd.app.cloud.gov/downloads/disbursements-by-month/)** 

- [x] Make sure the downloaded data matches the [raw data.](https://teams.microsoft.com/l/file/31F646F0-4F11-4CC0-A16B-5920B2C8A02A?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FDisbursements%2FFY21%2FQ4%20Total%20Web%20Data%20(Aug).xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a) 
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [x] Check Treasury Fund column is deleted
- [x] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [x] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- [x] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Breakout - Source 
- [x] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**- Added [August 2021 monthly revenue data](https://dev-nrrd.app.cloud.gov/downloads/revenue/)**

- [x] Make sure the downloaded data matches the raw data. Raw data saved [here](https://teams.microsoft.com/l/file/448C5F07-3D45-484E-BD19-386E795642BD?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=csv&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FRevenue%2FFY%202021%2FAugust%202021%20Revenue%20for%20Portal.csv&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Homepage - Yearly Breakdown

- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.

    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout Commodity
 
Homepage - Source File
- [x] Check source file links are correct.

Query Data

- With a selected fiscal or calendar year range, verify the data is correct and then for the conditions below. 
- [x] One Land Type filter
- [x] One Revenue Type filter
- [x] One State
- [x] One Offshore Region
- [x] One to three Commodities
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

**- Added [May 2021 monthly production data](https://dev-nrrd.app.cloud.gov/downloads/production-by-month/)**
- [x] Make sure the downloaded data matches the raw data. Raw data saved [here ](https://teams.microsoft.com/l/file/D5F08E6E-7BCE-4A1D-AE85-F6D3DBA08C29?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FProduction%2FFY%202021%2FProduction%20Volumes%20as%20of%209-13-2021.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Source File
- [x] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Land Type filter
- [x] One to three Products
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

### CODE REVIEW

**Review by mcharg — APPROVED** [review]

**Comment by mcharg** [comment]
I checked everything but the data in several browsers and it looks good.

**Comment by lpgoldstein** [comment]
@mojobnichols @Maroyafaied the monthly disbursement download files are rolling up all of the funds into "other funds" - don't we want to keep them separate for these files but rolled up in the fiscal year files? The good news is that it looks like it's doing it correctly!

**Review by cthomasONRR — APPROVED** [review]
I checked:
- [ ] Glossary Disclaimers
- [ ] August 2021 Monthly Revenue
- [ ] May 2021 Monthly Production

These look good to me! Approving!

**Comment by cvojslavek** [comment]
I checked:

Download Page
- [x] Check Hidalgo Caounty is changed to Hidalgo County under county column

It looks like "Calcasieu Paris" is showing up in county column. Should this just be "Calcasieu"?

Monthly Snap Shot
- [x] Check graphs match homepage

**Comment by lpgoldstein** [comment]
> I checked:
> 
> Download Page
> 
> * [x]  Check Hidalgo Caounty is changed to Hidalgo County under county column
> 
> It looks like "Calcasieu Paris" is showing up in county column. Should this just be "Calcasieu"? image
> 
> Monthly Snap Shot
> 
> * [x]  Check graphs match homepage

@cthomasONRR Yes it should just be calcisieu and  should we take out the hidalgo caounty checkbox because county is no longer included in the column so the misspelling is automatically gone.

**Comment by lpgoldstein** [comment]
@Maroyafaied @cthomasONRR I checked the disbursements data and am currently happy with everything except for the monthly download file rolling up the fund data.

**Review by kjgdata — APPROVED** [review]
I have looked over the August  2021 monthly/yearly revenue data and made sure that the downloaded data matches the raw data.

When querying data online, I looked at the 2020 calendar year with the filters within the list and everything looks great!

**Review by daniel-coleman-1 — APPROVED** [review]

**Review by daniel-coleman-1 — COMMENTED** [review]
I checked Meshan's blog post and the download page disclaimer, both look good.

**Review by jlouis-onrr — APPROVED** [review]

**Review by Baymatt — APPROVED** [review]
Double checked the monthly production data, looks good

**Comment by codyeckstein** [comment]
Blog posts look good. I've been looking through data as well.

**Comment by codyeckstein** [comment]
**Rents
Leaseholders pay rent until the land or water starts producing resources.**

Is there a better way to word this? The water doesn't produce resources. Maybe something like:

_The leaseholders often pay rentals until minerals are produced and sold._

**Comment by cvojslavek** [comment]
Looks good. Checked disbursement data, paris removed, and checked:
- [x] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column
@lpgoldstein "Lease Process Improvement (BLM)" is under fund type column, not sure if this checkbox should be changed or removed for future.

**Review by cvojslavek — APPROVED** [review]

**Review by lpgoldstein — APPROVED** [review]

**Comment by codyeckstein** [comment]
I keep getting this error when trying to look up Explore Data Nationwide 

image

**Comment by Maroyafaied** [comment]
@codyeckstein great catch! It's giving me an error as well! @mojobnichols @jlouis-onrr can one of you look into why that's happening? It doesn't happen in the live site.

**Comment by lpgoldstein** [comment]
@Maroyafaied and @codyeckstein it's not happening for me.

**Comment by codyeckstein** [comment]
> @Maroyafaied and @codyeckstein it's not happening for me.

Try the Disbursement dropdown.

**Comment by Maroyafaied** [comment]
@lpgoldstein are you filtering for disbursement and clicking on the tab? I tried a couple of times and it looks like it's about to load but then gives the error page. 
image

**Comment by lpgoldstein** [comment]
@Maroyafaied 4th time is the charm! I'm now getting the same error.

**Comment by mcharg** [comment]
Looks like the bug is fixed.  I'm not getting an error when I used the Disbursements drop-down and then click on the summary tab.

**Comment by Maroyafaied** [comment]
@mcharg @mojobnichols I'm still getting the error. When you filter disbursements for 2018 in explore data then hit the nationwide disbursement summary tab.

**Review by meshanw — APPROVED** [review]

**Comment by mcharg** [comment]
@Maroyafaied I'm getting the error when I switch to 2018.  I didn't realize it was tied to year.

**Pull request merged**
