### PR TITLE
Update monthly production data

### PR DESCRIPTION
**Pull request by Baymatt**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/update-prodution-revenue-data/)

Changes proposed in this pull request:

- Updated monthly production data
-
-

### CODE REVIEW

**Comment by lpgoldstein** [comment]
@Baymatt numbers look good - I just did one formatting thing in the excel spreadsheet

**Comment by lpgoldstein** [comment]
@jennmalcolm or @Maroyafaied could one of you please review as well?

**Review by lpgoldstein — APPROVED** [review]

**Comment by jennmalcolm** [comment]
The link isn't working for me. I'm trying to re-run, and if it succeeds, I'll review.

**Comment by jennmalcolm** [comment]
It took me a little bit to spot it, but the branch name is missing a c in production, so I corrected the preview link, and it's working now.

**Review by jennmalcolm — APPROVED** [review]
Looks good

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
