### PR TITLE
1557 location offshore

### LINKED ISSUE #1557: Set location for offshore not tied to a region.
At load set location for offshore data not tied to a region.   (inspection fees)

Location name will become: Not tied to a lease

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #1557
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1557-LocationOffshore?/)

Changes proposed in this pull request:

set location_name ='' to Not tied to a lease to prevent issues in query tool

Also set the location_order so that these items appear last. 

-
-
-

### CODE REVIEW

**Comment by mojobnichols** [comment]
Oh something to consider - should I change land_type too ?  This is used in the home page graph so comparing query tool not tied to a lease won't match home page.   

  
image

**Comment by mcharg** [comment]
@mojobnichols Is this just for revenue?  There is a blank checkbox in the drop-down for disbursements.
image

**Comment by mojobnichols** [comment]
> @mojobnichols Is this just for revenue? There is a blank checkbox in the drop-down for disbursements.
> image

Yeah that is Onshore and Offshore - I have to look at what is different for disbursements over revenue, that is not gettting the label.

**Comment by Maroyafaied** [comment]
@mojobnichols @mcharg the blank in disbursements is an issue in the current live site. This PR looks good, I'll create an issue for the blank disbursement issue.

**Review by Maroyafaied — APPROVED** [review]

**Review by mcharg — APPROVED** [review]

**Pull request merged**
