### PR TITLE
Dev-->Master 

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- Publish FY 20201 GOMESA disbursements 
- Make header sticky
- Changes to Disbursements page in how revenue works 
- Add Glossary to horizontal charts
- New wording for cards when there is no data
- Take out NPPLLRF paragraph in how revenue works and page

### CODE REVIEW

**Comment by mcharg** [comment]
@Maroyafaied Paragraph is still there for nppllrf, but the page is gone.
image

**Comment by mcharg** [comment]
@jlouis-onrr Now anytime I'm in How Revenue Works, the logo is missing.

**Comment by jlouis-onrr** [comment]
@mcharg, looks like there is conflicting classes colliding with svgs in in How Revenue Works, working on a fix now...

**Comment by Maroyafaied** [comment]
> @Maroyafaied Paragraph is still there for nppllrf, but the page is gone.
> image

@mcharg this should be gone now, please check again.

**Comment by mcharg** [comment]
@Maroyafaied The paragraph is gone.

**Review by mcharg — APPROVED** [review]

**Pull request merged**
