### PR TITLE
added glossary term to query tool

### LINKED ISSUE #91: Design & build glossaries in query tool

### PR DESCRIPTION
**Pull request by master12**
Fixes #91 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/91-glossary-in-query-tool)

Changes proposed in this pull request:

- Added glossary term component to the library
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 The glossary looks good. @jnwang01 Is going to take a look and make sure it's on all the terms we have definitions for.

**Comment by mcharg** [comment]
@master12 I just noticed that the dollar amounts aren't aligning to the right.
image

**Comment by master12** [comment]
@mcharg I will make a separate issue for the alignment.

**Comment by jnwang01** [comment]
I think its missing terms for the units of measurement in 
revenue: other revenue, not tied to commodity, NGL 
production: mcf, bbl, ton and kilowatt hours, metric ton, long ton
disbursement: historic preservation fund, GOMESA, state 8(g) 

and calender year and fiscal year

**Comment by master12** [comment]
We need to add missing terms to the markdown file for glossary terms. Do you want me to do that?

**Comment by mcharg** [comment]
@master12 Yes, please.

**Review by mcharg — APPROVED** [review]

**Comment by mcharg** [comment]
Putting the list of missing terms into #1332 to clean up next sprint.

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
