### PR TITLE
Monthly pricing

### LINKED ISSUE #1627: Review monthly data
I will do one PR for monthly production, revenue and monthly and add the checklist for each data set. @Baymatt @CM805 please review data, you can split the data sets or review different sections of each data set.

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #1627 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/monthly-pricing/)

Changes proposed in this pull request:

**Uploaded [May 21 Revenue](https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Revenue/May%202021%20Revenue%20for%20Portal.xlsx?web=1) and [June 2021 Revenue](https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Revenue/June%202021%20Revenue%20for%20Portal.xlsx?web=1),** 

- [x] Compare original file to the download file and make sure data matches

Homepage - Yearly Breakdown
- [x] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout - Commodity
 
Homepage - Monthly Breakdown
- [x] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout Commodity
 
Homepage - Source File
- [x] Check source file links are correct.

Query Data 
- [x] With a selected fiscal or calendar  year range, verify the data is correct and then for the conditions below. 
- [x]   One Land Type filter
- [x]   One Revenue Type filter
- [x]   One State
- [x]   One Offshore Region
- [x]   One to three Commodities
- [x]   Clear All and change grouping
- [x]  Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

**Uploaded May 21 Disbursements, here's the [original file ]**(https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Disbursements/FY21/Q3%20May%20Web%20Data%20(May).xlsx?web=1)

- [x] Compare original file to the download file and make sure data matches

Homepage - Yearly Breakdown
- [x]  Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Breakout - Source 
- [x] Breakout - Recipient

Homepage - Monthly Breakdown
- [x] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x]  Clear All and change grouping
- [x]  Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

**Uploaded [Feb 21 Production](https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Production/Production%20Volumes%20as%20of%206-7-2021.xlsx?web=1) and [March 21 Production](https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Production/Production%20Volumes%20as%20of%207-8-2021.xlsx?web=1)** 

- [x] Compare original file to the download file and make sure data matches

Homepage - Yearly Breakdown
- [x] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- [x] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Source File
- [x] Check source file links are correct.

Query Data
- [x]  One Land Type filter
- [x]  One State
- [x]  One Offshore Region
- [x] One to three Product
- [x] Downloads matches filtered data  

Download Page
- [x] Dates and file size are correct for csv and excel

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@Baymatt @CM805 We received [June 2021 revenue file](https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Revenue/June%202021%20Revenue%20for%20Portal.xlsx?web=1) and [March 2021 Production file](https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Production/Production%20Volumes%20as%20of%207-8-2021.xlsx?web=1), please check they match the downloads. Thanks

**Comment by Maroyafaied** [comment]
@mojobnichols I added June 2021 revenue data to this PR yesterday but it's not showing them. Also, the monthly tab is broken in my preview link in homepage revenue tab.

**Comment by CM805** [comment]
My checklist for June 2021 Revenue Data

Changes proposed in this pull request:

**Uploaded [May 21 Revenue](https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Revenue/May%202021%20Revenue%20for%20Portal.xlsx?web=1) and [June 2021 Revenue](https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Revenue/June%202021%20Revenue%20for%20Portal.xlsx?web=1),** 

- [x] Compare original file to the download file and make sure data matches

Homepage - Yearly Breakdown
- [ ] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [ ] Breakout - Commodity
 
Homepage - Monthly Breakdown
- [ ] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout Commodity
 
Homepage - Source File
- [x] Check source file links are correct.

Query Data 
- [x] With a selected fiscal or calendar  year range, verify the data is correct and then for the conditions below. 
- [x]   One Land Type filter
- [x]   One Revenue Type filter
- [x]   One State
- [x]   One Offshore Region
- [x]   One to three Commodities
- [x]   Clear All and change grouping
- [x]  Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

**Comment by Maroyafaied** [comment]
@Baymatt Can you please review March 2021 production data?
**[March 21 Production Original file](https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Production/Production%20Volumes%20as%20of%207-8-2021.xlsx?web=1)** 

- [x] Compare original file to the download file and make sure data matches

Homepage - Yearly Breakdown
- [x] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- [x] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Source File
- [x] Check source file links are correct.

Query Data
- [x]  One Land Type filter
- [x]  One State
- [x]  One Offshore Region
- [x] One to three Product
- [x] Downloads matches filtered data  

Download Page
- [x] Dates and file size are correct for csv and excel

**Review by Baymatt — APPROVED** [review]
May 2021 Revenue, May 2021 Disbursements, Feb 2021 and March 2021 Production look good.

**Comment by CM805** [comment]
@Maroyafaied I have a few questions for you as I'm looking through these.  They relate to the boxes I have not yet checked off.

For "Clear All and change grouping", I did that but I get no data displayed:

image


I also have a question related to functionality of the Query Data screen.  1) Why does the slider not go to 2021 when Fiscal Year or Calendar Year is selected?  Is this because we only want to display data for a completed year, instead of Y-T-D data?

**Comment by Maroyafaied** [comment]
@CM805 , I tried the "clear all" and I also get no data so that's a bug , I'll make an issue for so thanks for finding that. For the query tool, it only displays the full year data if you choose the period as FY or CY, the monthly view is the only one that displays YTD. If the bug is the only issue you found, then you can go ahead and approve the PR since the bug is not data related. Thanks

**Review by CM805 — APPROVED** [review]
All data is correct.

Bug when using "clear all"- no data displayed.

**Comment by Maroyafaied** [comment]
@mojobnichols I still see LA in state/offshore region.

**Pull request merged**
