### PR TITLE
New production and revenue monthly data

### LINKED ISSUE #1554: Upload production and revenue monthly data

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #1554 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/new-monthly-data/)

Changes proposed in this pull request:

- Upload Production Jan 21 monthly
- Upload Revenue April 21 monthly

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 please use the checklist below to check production data, here's the [original data set](https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Production/Production%20Volumes%20as%20of%205_11_2021.xlsx?web=1) send to us to use to check the data against the visuals on the website and the file on the download page. Don't hesitate to ask questions. **Production Monthly** 

Homepage - Yearly Breakdown
- [ ] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- [ ] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Source File
- [ ] Check source file links are correct.

Query Data
    - [ ] One Land Type filter
    - [ ] One State
    - [ ] One Offshore Region
    - [ ] One to three Product
    - [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by Maroyafaied** [comment]
@CM805 please use the checklist below to check revenue data, here's the [original data set](https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Revenue/April%202021%20Revenue%20for%20Portal.xlsx?web=1) send to us, please use it to check the data against the visuals on the website and the file on the download page. Don't hesitate to ask questions. 
Homepage - Yearly Breakdown
- [ ] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout - Commodity
 
Homepage - Monthly Breakdown
- [ ] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout Commodity
 
Homepage - Source File
- [ ] Check source file links are correct.
 
Explore Data - Map and Detail Card
- [ ] Select a year and select a state with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected
 
- [ ] Select a year and select a county with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected.
 
- [ ] Select a year and select an offshore area, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected.
 
- [ ] Select a state and county without data and verify the expected information is displayed.
- [ ] Add Nationwide Federal Card and verify the expected information is displayed.
- [ ] Add Native American Card and verify the expected information is displayed.

Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- [ ] Verify breakdowns by revenue type and source are correct as well nationwide locations for the conditions below.
    - [ ] Not current Calendar Year
    - [ ] Current Calendar Year
    - [ ] Not current Fiscal Year
    - [ ] Current Fiscal Year

Query Data
    - [ ] With a selected fiscal or calendar  year range, verify the data is correct and then for the conditions below. 
    - [ ] One Land Type filter
    - [ ] One Revenue Type filter
    - [ ] One State
    - [ ] One Offshore Region
    - [ ] One to three Commodities
    - [ ] Clear All and change grouping
    - [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by Maroyafaied** [comment]
@mojobnichols I noticed this in the morning while showing @daniel-coleman-1 how to check data. The production FY so far bar data doesn't match what's in the file. It's an issue on the live site as well. 
image

**Comment by Maroyafaied** [comment]
@mojobnichols the revenue file for April is not matching the original data from DORC. Here is a screenshot 
image

**Comment by mojobnichols** [comment]
> @mojobnichols I noticed this in the morning while showing @daniel-coleman-1 how to check data. The production FY so far bar data doesn't match what's in the file. It's an issue on the live site as well.
> image

Resolved - simple logic bug in production comparison

**Comment by mojobnichols** [comment]
> > @mojobnichols I noticed this in the morning while showing @daniel-coleman-1 how to check data. The production FY so far bar data doesn't match what's in the file. It's an issue on the live site as well.
> > image
> 
> Resolved - simple logic bug in production comparison

Resolved by making ELT handle ( ) for negative numbers

**Comment by Maroyafaied** [comment]
@mojobnichols the Native American data is not matching. 
image

**Comment by mojobnichols** [comment]
> @mojobnichols the Native American data is not matching for revenue.
> image

Fixed.

**Comment by Maroyafaied** [comment]
@Baymatt if you can help with the data checks that would be great, just check off what you checked. Thanks

**Review by mojobnichols — APPROVED** [review]

**Comment by Baymatt** [comment]
@Maroyafaied @mojobnichols My revenue data isn't matching up

Screen Shot 2021-05-24 at 3 35 48 PM

**Comment by Maroyafaied** [comment]
@mojobnichols seems like the negative numbers is causing an issue again. See @Baymatt comment above.

**Comment by Baymatt** [comment]
@Maroyafaied @mojobnichols In production data with coal as the commodity on the yearly breakdown, it seems like total is only taking into account the Native American value.

Screen Shot 2021-05-24 at 4 48 55 PM

**Comment by daniel-coleman-1** [comment]
> @Maroyafaied @mojobnichols In production data with coal as the commodity on the yearly breakdown, it seems like total is only taking into account the Native American value.
> 
> Screen Shot 2021-05-24 at 4 48 55 PM

@Maroyafaied @mojobnichols 
I'm seeing the same thing with the monthly reports for coal.  I'm thinking that the empty value is keeping the three (or two, in this case) from combining together

Oct2020CoalScreenshot 2021-05-24 183039

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 @Baymatt I checked the query tool for production. @CM805 I checked revenue data. We will need to check data one more time in the dev to master PR.

**Pull request merged**
