### PR TITLE
1355 fact sheet

### LINKED ISSUE #1355: Build Fact Sheet

### PR DESCRIPTION
**Pull request by master12**
Fixes #1355

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1355-fact-sheet/fact-sheet/)

Changes proposed in this pull request:

- 1 page printable fact sheet
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 Can you right align the month column header on all the charts?
image

**Comment by mcharg** [comment]
@master12 On production, the 2020 label is missing below the months.
image

**Comment by mcharg** [comment]
@master12 On production, maybe try using just the first letter of the month name to avoid overlapping?  For gas, can you display fewer numbers on the y axis?
image

**Comment by mcharg** [comment]
@master12 Can you shrink the number at the top of the y axis and the years below to the same font size as the rest of the font on the chart?
image

**Comment by mcharg** [comment]
@master12 Production shouldn't have dollar signs.
image

**Comment by Maroyafaied** [comment]
@master12 It's look good, if you can please remove the $ on production charts and alight the header for months to the right.

**Comment by mcharg** [comment]
@master12 When I print to pdf, the numbers in the revenue by revenue type table are different from what is on screen.  Not sure what's going on.  The totals are the same, but the broken out amounts are different.  I'm not noticing issues with the other charts.
[Fact Sheet _ Natural Resources Revenue Data.pdf](https://github.com/ONRR/nrrd/files/6044884/Fact.Sheet._.Natural.Resources.Revenue.Data.pdf)
On screen:
image

PDF: 
image

**Comment by mcharg** [comment]
@master12 Revenue by source is also off.

Page:
image
PDF:
image

**Comment by mcharg** [comment]
@master12 Production, except for oil, is also off.

Screen:
image

PDF: 
image

**Comment by master12** [comment]
@mcharg I cannot recreate the print view different from what is on the screen. I will disable the hover so the numbers don't change.

**Comment by master12** [comment]
@mcharg Ok so i disabled all interactions including select and hover. I also removed the related css styling that relates to those interactions such as a mouse pointer.

**Comment by mcharg** [comment]
@master12 Production is still showing dollar signs.  Otherwise, looks good.
image

**Comment by mcharg** [comment]
@mentastc Do you want to take a look at the fact sheet?

**Review by mcharg — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@master12 this looks good, just two small suggestions. Can you make  revenuedata.doi.gov clickable and would it be possible to add a print icon for users to know this can be printed as 1 page. 
image

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
