### PR TITLE
Updated revenue-by-month.mdx

### LINKED ISSUE #1259: Create consolidated downloads page for consolidated revenue file
Since the new file is a combo of monthly and annual revenue files, and we will no longer have separate FY/CY files, we need to create a new download page (edit monthly page) with all appropriate definitions, scope, etc.

### PR DESCRIPTION
**Pull request by Baymatt**
Updated revenue-by-month.mdx to reflect the change to a consolidated revenue file

Fixes #1259

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/consolidated_revenue/)

Changes proposed in this pull request:

- Changes made to content of revenue-by-month.mdx
-
-

### CODE REVIEW

**Comment by lpgoldstein** [comment]
@Maroyafaied @jennmalcolm What do we want to call "not tied to a lease" under land category? On the homepage we have "not tied to location" while in the current monthly file we have blanks and in the new monthly file we have "not tied to lease".

**Comment by lpgoldstein** [comment]
@Baymatt Also brought up that we need to update the main index page but I told him to wait for now. https://revenuedata.doi.gov/downloads/

**Comment by Baymatt** [comment]
I didn't change the file size or file path because I wasn't sure which file we were going to use so that probably needs to be edited as well.
Ex. [Consolidated revenue, 1/2003-12/2020 (csv, 5.4 MB)](/downloads/csv/revenue/monthly_revenue.csv)

**Comment by lpgoldstein** [comment]
@Baymatt Good catch - you are right - we don't have the final file yet so don't know the size.

**Comment by lpgoldstein** [comment]
@Baymatt I'm taking off the other reviewers because I want to make some edits first, but will do tomorrow. Then will re-add them.

**Comment by jennmalcolm** [comment]
@lpgoldstein, "not tied to lease" and "not tied to a location" really were intended for different things because we have some revenues that we can identify as onshore or offshore, but they are not specifically for one lease (e.g. offshore inspection fees, some other revenues). Since we can't classify them down to the level of state or offshore region, we were going to label those as "not tied to lease". Some other revenues such as civil penalties do not even have onshore or offshore, so we were going to classify those as "not tied to a location". 

That being said, it looks like we're doing it wrong in the query tool, and since it's this confusing even to us, it probably isn't a useful distinction for our users. Therefore, I suggest we change it to "not tied to lease" when a line doesn't have onshore/offshore, state/offshore region, or both. Since none of these lines are tied to a lease that is still accurate where using "location" technically would not be since onshore/offshore is broadly a location. We should still keep Native American lines as "location not published." What do you think @Maroyafaied @lpgoldstein ?

**Comment by lpgoldstein** [comment]
@jennmalcolm I agree with your assessment of just using not tied to a lease and then location not published. It's less confusing.

**Comment by Maroyafaied** [comment]
@jennmalcolm I agree that it's confusing and we should stick with one phrase, I just wonder if it'll cause confusion for users if we use "not tied to a lease" in the state/offshore region filter in the query tool instead of "not tied to a location".  @mcharg have we asked users about this? If we do make that changes, then we def need to define in the glossary what we mean by "not tied to a lease"

**Comment by mcharg** [comment]
I don't think we've asked about lease vs. location.  Mostly when anyone sees any of the "not tied to" items they say they want a glossary to tell them what it means.

**Comment by mcharg** [comment]
We may have used location in the query tool because you select it from the location drop-down.

**Comment by Maroyafaied** [comment]
@Baymatt @lpgoldstein we need to get rid of revenue by year in the main download page.  Also the title should be "Revenue by month" instead of year, and the file can still be called revenue by month instead of consolidated revenue. 
image
image

**Comment by jennmalcolm** [comment]
Shouldn't we change this to a "date" field since we're going to have month and year in the same field? Also, is there any reason to discuss FY and CY on this page anymore? 
image

There are also spacing problems on this page. Do you want me to go through and correct them because I have an issue for that for download pages anyway?

**Comment by Maroyafaied** [comment]
@lpgoldstein @jennmalcolm should we keep the FY and CY definitions if we plan on having links to all 3 files in the same download page? I know the fields for CY and FY won't be in the file but we can still keep the definitions.

**Comment by mcharg** [comment]
@Maroyafaied I think it makes sense to keep the definitions because users who don't work for the federal government often don't know when our fiscal year starts and ends.

**Comment by jennmalcolm** [comment]
Yes, I agree that we should keep the FY and CY definitions on this page since we decided it would have the annual files on it too.

**Comment by Maroyafaied** [comment]
Can we take "by month" out and add in this paragraph that we provide the file by fiscal year and calendar year so all the 3 files will be in this page. 
image
image

**Comment by Maroyafaied** [comment]
Add this info  
image

**Comment by lpgoldstein** [comment]
I need developer help please - my changes seem stuck in "stash" mode. I accidently switched branches while I was working and then tried to switch back and now my changes are stuck. @master12 @jlouis-onrr @mojobnichols

**Comment by Maroyafaied** [comment]
@lpgoldstein please also change anywhere that says "Oil & Gas" to Oil or Gas (pre-production) since Mojo will be making that change in the database. 
image
image
image

**Review by lpgoldstein — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@lpgoldstein the fiscal year file would only go up to FY 20 since we don't have the entire FY 21 completed.  So we should change that 
image

**Pull request merged**
