### PR TITLE
1241 pattern lib enhance

### LINKED ISSUE #1241: Pattern library refinements
Refine the components in the pattern library:
- [x] It seems like some components are missing. For example, are the explore data cards not a component? I also don't see tabs, links, or tables. 
- [x] You were also going to show the horizontal version of the bar chart as a variant.
- [x] For the guidelines page in Visual Style make the headers white so that it's easier to skim/read
- [x] For the menu tabs darken or lighten the blue on whatever page they're on, so they know where they are in the menu tab

### PR DESCRIPTION
**Pull request by master12**
Fixes #1241

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1241-pattern-lib-enhance/patterns/)

Changes proposed in this pull request:

- Search is implemented
- Documentation added to readme.md
- Added missing components
- Added 2 tickets for ExploreData Card and Tabtastic components

### CODE REVIEW

**Review by mcharg — APPROVED** [review]

**Comment by mcharg** [comment]
@master12 Components aren't showing up even after clearing my cache. 
image

**Comment by mcharg** [comment]
@master12 The components still aren't displaying even after clearing my cache.

**Comment by master12** [comment]
Ok components are displaying

@mcharg

**Review by mcharg — APPROVED** [review]

**Comment by mcharg** [comment]
@master12 Can the search label be white?  It's hard to see right now.
image

**Comment by mcharg** [comment]
@master12 Or can the background of the search field be white?

**Comment by mcharg** [comment]
@master12 When you first click on the components tab, can it select the first toggle instead of the middle one?
image

**Comment by mcharg** [comment]
@master12 Can you please fix the search box text or background color so it's readable and default toggle selection, so we can get this merged?

**Comment by mcharg** [comment]
@master12 The background on the search field is still blue (the autocomplete list is now white) and it's now not selecting any toggle by default.
image

**Review by mcharg — APPROVED** [review]

**Pull request merged**
