### PR TITLE
Got revenue by company mostly up and running

### LINKED ISSUE #182: Explore data: Build revenue by company summary
Design:

Annotated prototype: https://935313.axshare.com/#g=1&p=revenue_default

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #182
[:sunglasses: PREVIEW](https://182-revenuebycompanysummary.app.cloud.gov/explore/)

Changes proposed in this pull request:

Takes top 10 ranked companies.

Still need to roll up the rest of the companies into other  row.

-
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@mojobnichols Looking good, so far.

**Comment by mcharg** [comment]
@mojobnichols You have an extra word in the query tool link.
image

**Comment by mcharg** [comment]
@mojobnichols Can you change the colors to the orange ramp to match the revenue type circle charts?

**Review by mcharg — APPROVED** [review]

**Comment by mcharg** [comment]
@jennmalcolm The latest is out in the preview link.  Someone should probably review the data before it's merged into dev.
https://preview-nrrd.app.cloud.gov/explore/?dataType=Revenue&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2019

**Comment by jennmalcolm** [comment]
@Maroyafaied or @lpgoldstein can one or both of you review the data?

**Comment by jennmalcolm** [comment]
@mojobnichols can you change the company names to title case rather than all caps? It's not that important, so if it's hard we can add address it later.

**Comment by mcharg** [comment]
FYI - I asked Mojo for 3 changes.
1) Fix the typo in the query tool link
2) Make the query tool link select "Revenue by company" data type when you get there
3) Change "Show" to "Show details" and "Hide" to "Hide details"

**Comment by mcharg** [comment]
@jennmalcolm We probably want to have flexibility on the company names so "BP" doesn't end up "Bp" and "LLC" doesn't end up "Llc", etc.

**Comment by jennmalcolm** [comment]
I'm not sure if @jlouis-onrr or @mojobnichols would do this, but can you remove the revenue by company from the navigation bar when fiscal year is selected? 

image

**Pull request merged**
