### PR TITLE
Update federal-revenue-by-company.mdx

### PR DESCRIPTION
**Pull request by daniel-coleman-1**
Fixes #<1707>

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Tutorial/)

Changes proposed in this pull request:

- Updated Scope with disclaimer

### CODE REVIEW

**Review by codyeckstein — APPROVED** [review]
Looks good.

**Review by lpgoldstein — APPROVED** [review]

**Review by jlouis-onrr — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Melissa reviewed and would the like the disclaimer to be moved next the the company name under field definitions. Thanks
image

**Comment by daniel-coleman-1** [comment]
Screenshot 2021-09-15 121348

@Maroyafaied updated to reflect Melissa's feedback

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Do you think having the definition saying "Name of company" adds any value to the user or should it be removed and replaced with just the disclaimer? 
image

**Comment by daniel-coleman-1** [comment]
@Maroyafaied I don't have a good answer here.  Does it add value?  Only in that it's consistent with defining the item, Calendar Year, Revenue Type, etc.  Does the text itself add any value to the reader's understanding?  I don't think so.

I think we should open an issue to review how we are presenting these definitions.  I think if we moved the unitalicized definitions to the line below the italicized text it may make more sense.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 The italicized text represent the field names within the data sets. Let's delete the "Name of a company" and move up the disclaimer next to the italicized "Company Name"

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
