### PR TITLE
Disbursement card county updates

### LINKED ISSUE #518: state line charts on production detail cards go away when a county is added
State line charts on production detail cards disappear when a county card is added

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #518, #519, #472

[:sunglasses: PREVIEW](https://519-countycardshavenationwidecharts.app.cloud.gov/explore/)

Changes proposed in this pull request:

- Removes top locations section from county cards, similar to Native American cards
- Update to missing production detail card line chart data
- Removes county map sections for county cards

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr Not a show stopper, but we should hide the production line chart for counties that have no production.
image

**Comment by jennmalcolm** [comment]
@mojobnichols do you want to review this PR, or should we merge?

**Comment by jlouis-onrr** [comment]
@mcharg, #527 is now out in this PR

**Comment by mcharg** [comment]
@jlouis-onrr Looks good.

**Comment by jlouis-onrr** [comment]
cool, going to merge this into dev

**Pull request merged**
