### PR TITLE
Horizontal chart updates

### LINKED ISSUE #1295: Revenue by company bar charts are wonky
This is what happens when I select geothermal.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #1295
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1295-RevenueByCompanyBarChartsWonky/explore)

Changes proposed in this pull request:

- Fixes overflow issues of bar charts
- Complete refactor of the way horizontal bar charts are built
- Clean up old horizontal code

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr On revenue by company, we should use the same color to represent the same thing on each bar.
image

**Comment by jlouis-onrr** [comment]
@mcharg, shouldn't the legend ordering be a separate issue since this already exists in production and is separate from the actual issue that has been fixed?

**Comment by mcharg** [comment]
@jlouis-onrr I think it was all in the same order at one point. It might have been part of this issue.  
https://github.com/ONRR/nrrd/issues/893

I can create a new issue to fix it again.

**Review by mcharg — APPROVED** [review]

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@mojobnichols can you please review and approve if it looks good then I will merge it. Thanks

**Review by mojobnichols — APPROVED** [review]

**Pull request merged**
