### PR TITLE
Migrate How it works pages to mdx

### PR DESCRIPTION
**Pull request by brentryanjohnson**
[🌟 PREEEEEEEEVIEW](https://mdx-how-it-works.app.cloud.gov/how-it-works)

Work in progress to migrate how-it-works to mdx.

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
@master12 I've refactored everything to vanilla markdown in `mdx` file format.

Here are few things we need to address:

- landing how it works page (`default.mdx`) isn't loading content to `how-it-works`. I assume that's simply a filename change to `index`, but wanted to run that by you.
- "dive-in" pages for nonenergy, onshore and offshore oil and gas, coal, onshore and offshore renewables no longer have background images or styling. (I also removed the Get involved and Did you know sections for now, along with the custom footer linking to the other pages).
- icons weren't loading properly for me in some cases (namely, icons for commodities, such as oil rig, coal car, etc.)

**Comment by brentryanjohnson** [comment]
Added Reclamation Fund page back, since it was added to production repo after this one was split off.

**Comment by brentryanjohnson** [comment]
Repaired links, since `permalink` key in former front matter no longer re-paths.

**Comment by master12** [comment]
closing since this is merged in another branch

**Pull request closed without merging**
