### PR TITLE
January 2021 Monthly Revenue Download File 

### PR DESCRIPTION
**Pull request by lpgoldstein**
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Januaryrevenue/)

Changes proposed in this pull request:

- adds January 2021 to csv and excel download files
- changes download file sizes - will redo once preview builds

### CODE REVIEW

**Review by Baymatt — COMMENTED** [review]
Just a really minor thing, in the csv file, January seems to have an extra space after it.

Ex. 
January ,2021,Federal,Onshore,Royalties,Sulfur,"(24,632.08)"
January ,2021,Federal,Onshore,Royalties,Zinc,"105,919.91 "

**Review by Maroyafaied — APPROVED** [review]

**Comment by lpgoldstein** [comment]
@Baymatt Good catch! I think I fixed the spacing in the csv file if you want to take a look.

**Comment by jennmalcolm** [comment]
Looks good. The only thing I noticed is that the cells that are blank under Land Category during previous months are noted as "Not tied to lease" during Jan 2021 only. I don't know if this will cause any hiccups for Mojo when loading the new month.

**Comment by jennmalcolm** [comment]
There's also a space after January in the Excel file.

**Comment by lpgoldstein** [comment]
@jennmalcolm Thanks. I will make those changes.

**Comment by jennmalcolm** [comment]
It still seems like there is a space in the Excel file after January. It's just a problem if you try to do a pivot table because there are two Januaries.

**Comment by lpgoldstein** [comment]
@jennmalcolm I'll try again. Maybe I just didn't save it properly.

**Review by jennmalcolm — APPROVED** [review]

**Pull request merged**
