### PR TITLE
added cents to query tool

### LINKED ISSUE #679: Rounding in Query Tool
Part 1: Why do we have more decimals than just cents in revenue file?

In comparing a pivot table from the download file to the download from the query tool, many number are off from $0.01 to $0.05.

This might have something to do with where we are rounding for the query tool, but I also think that a lot of it might be because in the revenue files, we go out more than to the cents decimal. I don't understand why this would be, and we should ask DORC about that.

Part 2: Should we be adding amounts rounded to the dollar to get grand total or adding all amounts to the cent and then rounding to the dollar for the grand total? We seem to be doing the first right now, which results in different totals in Excel and query tool. If we did the latter, they would match Excel and Query tool, but if you added all amounts on the screen, you wouldn't arrive at the same total as displayed.

### PR DESCRIPTION
**Pull request by master12**
Fixes #679 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/679-round-query-tool/query-data)

Changes proposed in this pull request:

- I round to Dollar Float vs Dollar int. 
-
-

### CODE REVIEW

**Review by jennmalcolm — APPROVED** [review]
Looks good. We still need to get files' revenues rounded to cents to get things to match, but that should happen if we round in DB and download files from DB.

**Comment by Maroyafaied** [comment]
@master12 it doesn't work for me for Calendar year revenue, this is what I see. 

image

**Comment by jennmalcolm** [comment]
@Maroyafaied Mojo is reloading CY revenues to fix the problem I found.

**Comment by Maroyafaied** [comment]
@jennmalcolm Ahh makes sense now. Thanks

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
