### PR TITLE
new production file

### PR DESCRIPTION
**Pull request by lpgoldstein**
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/monproduction/)

Changes proposed in this pull request:

- new monthly production with formatting fixed in date column

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@lpgoldstein this looks good, can you update the file size to 64? Thanks

**Comment by lpgoldstein** [comment]
@Maroyafaied edited file size

**Comment by Maroyafaied** [comment]
@lpgoldstein looks like something failed when updating the size.

**Comment by jennmalcolm** [comment]
I re-ran the build, and it went through this time.

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
