### PR TITLE
Added accessibility page & link to footer

### PR DESCRIPTION
**Pull request by eelzi-ONRR**
Fixes #<2335>

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/accessibilty-page/)

Changes proposed in this pull request:

- Added accessibility page
- Added link to the footer for the accessibility page

### CODE REVIEW

**Comment by eelzi-ONRR** [comment]
@Maroyafaied this is ready for review.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Great job troubleshooting and fixing the footer and the 404 error! Blow are my review comments

1. Can you format the address similar to onrr.gov's page so it's not all in one line. 
image


2. It looks like this section is missing one of the bullet points that's on onrr.gov's page
image


3. This is nitpicky but can either change onrr.gov or nrrd so this link is labeled the same. 
image

Thanks, and nice job!

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Thank you for catching those! The address spacing is fixed. I removed that bullet point and changed the link label on the ONRR page (which was reviewed and approved via slack)

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Looks good! I will merge this to dev now. After it's done building, you should be able to see the new page in dev https://dev-nrrd.app.cloud.gov/.

**Pull request merged**
