### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- [x] [Accessibility blog post](https://dev-blog-nrrd.app.cloud.gov/accessibility/) 

- [x] Homepage comparison text

- [x] Left nav fix in how revenue works

**Federal Revenue by Company data CY 20**

- [x] Make sure the downloaded data matches the raw data. Raw data saved [here](https://teams.microsoft.com/l/file/BCAFFDD4-557B-4C74-8405-30E9884403B4?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FRevenue%20by%20company%2FCY20%20Federal%20Revenues%20by%20Company%20Final.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Explore Data - Click on the "Federal revenue by company" link below the map
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
   - [x]  One to three Companies
   - [x]  Revenue Types within a Company
   - [x]  One to three Commodities
   - [x]  Check the Top 10 Companies (highest revenue) to ensure revenue sums and their percent of total is correct
   - [x]  Check "Other Companies" to ensure that the revenue sum and percent of total is correct

Query Data - In the "Data Type" category, filter to "Federal revenue by company"
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
   - [x]  One to three Companies
   - [x]  One to three Revenue Types
   - [x]  One to three Commodities
   - [x]  Clear All and change grouping
   - [x]  Download matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

**Monthly Disbursement data July 2021**

- [x] Make sure the downloaded data matches the raw data. Raw data saved [here](https://teams.microsoft.com/l/file/317BA3D4-1E3B-409B-A71A-8FFD017A29EF?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FDisbursements%2FFY21%2FQ4%20Total%20Web%20Data%20(Jul).xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)
- [x]  Check Treasury Fund column is deleted
- [x]  Check Hidalgo Caounty is changed to Hidalgo under county column
- [x]  Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown

Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x]  Breakout - Source
- [x]  Breakout - Recipient

Homepage - Monthly Breakdown

Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
- [x]  Period - Most recent 12 months
- [x]  Period - Fiscal Year
- [x]  Period - Calendar Year
- [x]  Breakout - Source
- [x]  Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x]  One Recipient
- [x]  One Source
- [x]  One State
- [x]  One to three Commodities if applicable
- [x]  Clear All and change grouping
- [x]  Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x]  Check graphs match homepage

### CODE REVIEW

**Comment by mcharg** [comment]
Checked the new homepage text, left nav fix and blog in Chrome, Firefox, IE, Edge and on both my phones.  Only issue I noticed is the menu is missing on mobile, but it's also missing in the live site.  It's happening on both my iPhone and Android phones.  Created #1713 to fix that.

**Review by cthomasONRR — APPROVED** [review]
I checked:

- [ ] federal revenue by company data , and 
- [ ] the accessibility blog post

Everything looks good to me! Approving.

**Comment by lpgoldstein** [comment]
Monthly disbursements look good

**Review by lpgoldstein — APPROVED** [review]

**Comment by cvojslavek** [comment]
@lpgoldstein I checked the Monthly Snap Shot:

- [ ] Check graphs match homepage

Looks good to me.

**Review by mcharg — APPROVED** [review]
Mobile issue appears to be fixed.

**Review by cvojslavek — APPROVED** [review]

**Review by jlouis-onrr — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 can you please review.

**Review by daniel-coleman-1 — APPROVED** [review]

**Pull request merged**
