### PR TITLE
179 build national revenue summary

### LINKED ISSUE #179: Explore data: Build national revenue summary
Design: 

Prototype: https://935313.axshare.com/#g=1&p=national_revenue_summary

Page context: https://935313.axshare.com/#g=1&p=revenue_default

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #179
[:sunglasses: PREVIEW](https://179-BuildNationalRevenueSummary.app.cloud.gov/explore/)

Changes proposed in this pull request:

Added National Revenue Summary componenet with horizontal bar charts

-
-
-

### CODE REVIEW

**Comment by jennmalcolm** [comment]
It's looking pretty good. I haven't checked the data yet, but I was just wondering if we should reverse the color scale since on our other charts the darker colors are for the larger proportions.

**Comment by mcharg** [comment]
I agree that we should reverse the colors and the order should be the one at the top of the legend comes first.  I know it's the opposite of the vertical charts, but it makes more logical sense for a horizontal chart.

**Comment by mcharg** [comment]
Also, the color ramp isn't far enough apart.  Can we use the darkest and lightest shades here as the start and end colors?
image

**Comment by Maroyafaied** [comment]
@mojobnichols I checked the numbers and they are correct, it would be nice to emphasize this is fiscal year data, maybe in the heading of the table it should say " FY 2019 amount" 
image

**Comment by mcharg** [comment]
@mojobnichols Native American is missing a color swatch.

image

**Comment by mcharg** [comment]
@mojobnichols We should add a "Source" label above the first column to be consistent with the other graphs.  Otherwise, looks good.
image

**Comment by mcharg** [comment]
@mojobnichols The green line just above the revenue type column looks funny.  Can you extend it over the column with the charts?
image

**Comment by jennmalcolm** [comment]
I agree with Shannon on the line below revenue type, and I was thinking we could also put amount above the line on the right. In looking at our current disbursements chart, I think it looks good to have headings for both sides. Also, since the whole chart shows the data for the one year, could we move the source and the FY 2019 to the headings above the line too. It just would seem cleaner rather than repeating that information on each revenue type. Here's a shot of the headings for the disbursements ones. 
image

**Pull request merged**
