### PR TITLE
Added land_type, region_type, district_type - consolidated to locatio…

### LINKED ISSUE #421: Create a consolidated location option for State, Offshore Region and County

### PR DESCRIPTION
**Pull request by mojobnichols**
…n_name - added fund table to create source and recipients and other fund attributes

[:sunglasses: PREVIEW](https://421-422-423-DatabaseChanges.app.cloud.gov/explore/)

Additional fixes applied here for review

- [x] [402 disbursements not including offshore](https://app.zenhub.com/workspaces/data-display-5464fa79c3cc8d7f4c384eaf/issues/onrr/nrrd/402)
- [x] [341 county level disbursements](https://app.zenhub.com/workspaces/data-display-5464fa79c3cc8d7f4c384eaf/issues/onrr/nrrd/341)
- [x] [top locations off](https://app.zenhub.com/workspaces/data-display-5464fa79c3cc8d7f4c384eaf/issues/onrr/nrrd/399)
- [x] [disbursement line charts](https://app.zenhub.com/workspaces/data-display-5464fa79c3cc8d7f4c384eaf/issues/onrr/nrrd/452)
- [x] [remove links in revenue cards](https://app.zenhub.com/workspaces/data-display-5464fa79c3cc8d7f4c384eaf/issues/onrr/nrrd/391)
- [x] [450 county data incorrect](https://app.zenhub.com/workspaces/data-display-5464fa79c3cc8d7f4c384eaf/issues/onrr/nrrd/450)

Todo to load before next pull:

- [ ] Production yearly files are putting two spaces in product between Commodity and unit
- [ ] Disbursements doens't have county fips lookup during load. 
- [ ] Yearly production has Coal (ton) it needs to be Coal (tons)
- [ ] Production files are not loading planning area

Changes proposed in this pull request:

created a location_name that contains the long form of the name for typesensitive drop downs

added attribute land_type which combines land_category and land_class in a consistent way.
added attribute region_type (State, County or Offshore)
added attribute district_type(Area, State, County, Parish, or Burough.

added table fund for disbursements.
attributes include:
recipients - essentially fund_type except Native american is cleaned up and normalized and county is broken out of state
fund_class - a hierachy of fund_type except the non major fund_types are rolled int to Specific fund
revenue_type - the type of revenue that funded the disbursement
source - The source of the revenue generated Onshore, Offshore,  GOMESA offshore, 8(g) offshore

-
-
-

### CODE REVIEW

**Comment by jennmalcolm** [comment]
@mojobnichols production data is not loading in this branch

**Comment by mojobnichols** [comment]
Oil is not loading by default.  In fact, the menu doesn't even get populated with Oil for default.   If you select you will see production data.  I'll look into what is going on.

**Comment by mojobnichols** [comment]
Oil loads by default now load script didn't properly parse out ' Prod Vol '.   I made a todo list for before the next time I load and manually fixed

**Comment by jennmalcolm** [comment]
@mojobnichols thanks, it's good that the data is loading now. It seems that there is still an issue because the oil label doesn't show as selected in the commodity dropdown for the default, and also if you select oil from the list, the map is blank. Should this be another issue?

**Comment by jennmalcolm** [comment]
Gas also doesn't load.

**Comment by jennmalcolm** [comment]
Other is looking good. The only thing I noticed is that the Native American circle has an ellipsis, indicating to me that you added "lands" to that, but the legend part does not have "lands." @mojobnichols do you want me to create a new issue for that? 
image

**Comment by jennmalcolm** [comment]
All features seem to be responding to the year slider now.

**Comment by mcharg** [comment]
#421 is not closed.  Land class and land category are still separate in the query tool.

**Comment by mcharg** [comment]
#422 is also should not be closed.  There is no source field for disbursements in the query tool.

**Comment by mcharg** [comment]
And #423 is also not reflected in the query tool.

**Comment by Maroyafaied** [comment]
@mojobnichols the county data looks good but now the production number on the cards are incorrect 
image
image

**Comment by jennmalcolm** [comment]
Native American lands legend label fixed. Thanks, @mojobnichols

**Pull request merged**
