### PR TITLE
Edge card layout issues

### LINKED ISSUE #504: Cards have minor layout issues in Edge
Revenue:
Circle charts aren't centered and county maps have thick lines.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #504

[:sunglasses: PREVIEW](https://preview-nrrd.app.cloud.gov/explore)

Changes proposed in this pull request:

- updates to flexbox styling for chart containers
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr It's still cut off.
image

**Comment by jlouis-onrr** [comment]
@mcharg, what version of Edge do you have?

**Comment by jlouis-onrr** [comment]
looks like support for the legacy version of edge will stop next March 🎉 :
https://docs.microsoft.com/en-us/lifecycle/announcements/m365-ie11-microsoft-edge-legacy

**Comment by mcharg** [comment]
Microsoft Edge 44.17763.831.0

**Comment by mcharg** [comment]
Fixed!
image

**Review by mcharg — APPROVED** [review]

**Pull request merged**
