### PR TITLE
Dev-->Master 

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- [x] [**Cat's blog post**](https://dev-blog-nrrd.app.cloud.gov/breaking-down-silos-by-cross-training/)

- [x] [**Coal Excise Tax 2020**](https://dev-nrrd.app.cloud.gov/how-revenue-works/coal-excise-tax)

- [x] [**Update ONRR's logo** ](https://dev-nrrd.app.cloud.gov/about)

- [x] [**Updated link in audit & assurance page**](https://dev-nrrd.app.cloud.gov/how-revenue-works/audits-and-assurances)

- [x] **Added October 2021 monthly revenue**
- [x] Make sure the downloaded data matches the raw data. Raw data saved [here](https://teams.microsoft.com/l/file/68B14464-2E2C-495F-B258-6ADCD269CCF1?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=csv&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FRevenue%2FFY%202022%2FOctober%202021%20Revenue%20for%20Portal_CSV_DO%20NOT%20EDIT.csv&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout Commodity
 
Homepage - Source File
- [x] Check source file links are correct.
 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [x] One Land Type filter
   - [x] One Revenue Type filter
   - [x] One State (for Yearly data only)
   - [x] One Offshore Region
   - [x] One to three Commodities
   - [x] Clear All and change grouping
   - [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

- [x]  **Added October 2021 monthly disbursement**
- [x] Make sure the downloaded data matches the raw data. Raw data saved [here](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Data/Disbursements/FY22/Web%20upload%20(Oct).xlsx?d=wd7796d3b84fa45698ed5c06fcb862fe1&csf=1&web=1&e=WuigZ9).

- [x] Check Treasury Fund column is deleted
- [x] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [x] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
  - [x] Breakout - Source 
  - [x] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

- [x] **Added July 2021 monthly production** 

- [x] Make sure the downloaded data matches the raw data. Raw data saved [here](https://teams.microsoft.com/l/file/205D1AD9-19F9-477D-B13F-CAB02147ACCC?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=csv&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FProduction%2FFY%202021%2FProduction%20Volumes%20as%20of%2011-8-2021_CSV_DO%20NOT%20EDIT.csv&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Source File
- [x] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Land Type filter
- [x] One to three Products
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

### CODE REVIEW

**Comment by lpgoldstein** [comment]
Disbursements look good!

**Review by mcharg — APPROVED** [review]
Checked the blog post, logo, and spot checked in a bunch of browsers. Looks good.

**Review by cthomasONRR — APPROVED** [review]
Revenue and Production look good! Approving!

**Review by lpgoldstein — APPROVED** [review]

**Review by daniel-coleman-1 — COMMENTED** [review]
Audits and assurances looks good!

**Review by kjgdata — APPROVED** [review]
Hello all,

I have reviewed all of the Revenue data as Christine suggested and the data looks great! I noticed that the preview does work on Chrome, but not on the Microsoft Edge browser.  I am approving.

**Review by Baymatt — APPROVED** [review]

**Pull request merged**
