### PR TITLE
Redirect state pages to explore data with card select (both cases)

### LINKED ISSUE #1032: Redirect state pages to the explore data page with the card selected
https://revenuedata.doi.gov/explore/tx/

returns a 404 page, but I thought we set up redirects for the state pages, so we don't lose SEO power.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #1032

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1032-RedirectStatePagesCasing/explore)

Changes proposed in this pull request:

- updates content for state redirects
- updates to frontMatter query and createRedirect methods to handle new data for both case types
-

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr It's opening the explore data page, but isn't selecting the Texas card when I append either /TX or /tx after explore in the url.

**Comment by mcharg** [comment]
Footer is messing up again here.
image

**Comment by jlouis-onrr** [comment]
@mcharg, i think the footer issue is somehow related to the new preview url structure.  Still trying to pinpoint whats actually happening.

**Comment by mcharg** [comment]
@jlouis-onrr Did you see that the state card isn't opening on the Explore Data page for this one?

**Comment by jlouis-onrr** [comment]
@mcharg, the redirects seem to be working for me.  Can you provide a example url that have used?

**Comment by mcharg** [comment]
https://nrrd-preview.app.cloud.gov/sites/1032-RedirectStatePagesCasing/explore/TX/

**Review by mcharg — APPROVED** [review]
It's working now!

**Pull request merged**
