### PR TITLE
515 revenue county data

### LINKED ISSUE #515: Wrong data on detail cards - revenue
The county detail cards are taking state data. This example below, a bunch of counties took the commodity data from CO. I first opened the counties (testing one-by-one) when CO was still open, and the data on the cards was correct at that point. Then, after I closed the CO card, the newly opened card wen to the CO data. I tried the example again with TX. I opened TX and three counties. The data looked fine. When I closed the TX card, the first county that had been right next to TX went to the TX numbers for both the commodity and revenue type data, but the other two remained ok.

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #515

[:sunglasses: PREVIEW](https://515-RevenueCountyData.app.cloud.gov/explore/)

Changes proposed in this pull request:

Fixes issue with data being incorrect between state and county changes.

Steps to reproduce:

1) Select colorado
2) select county level map
3) select Gunnison county
4) select state level
5) remove Colorado
6) select state Colorado

No charts should have stale or wrong data. 

-
-
-

### CODE REVIEW

**Comment by lpgoldstein** [comment]
This works for me!

**Comment by jennmalcolm** [comment]
This fixes this issue. I found an issue with some county data, but I'll make a separate issue for that.

**Comment by Maroyafaied** [comment]
@mojobnichols the "other" data is wrong for me here as well. 
image

**Comment by jennmalcolm** [comment]
@Maroyafaied if that's not a separate issue already, could you make it a separate issue. This PR was to fix the issue where state numbers were showing up on county cards, and I merged it already.

**Comment by Maroyafaied** [comment]
@jennmalcolm i have an issue for something similar on production data

**Comment by jennmalcolm** [comment]
Ok thanks @Maroyafaied. It would probably be a good idea to add the notes/screenshot for revenu to that issue.

**Pull request merged**
