### PR TITLE
Update coal-excise-tax.mdx

### LINKED ISSUE #1846: Update Coal Excise Tax page with 2020 data
https://revenuedata.doi.gov/how-revenue-works/coal-excise-tax

### PR DESCRIPTION
**Pull request by lpgoldstein**
Fixes #1846 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/coalexcisetax/)

Changes proposed in this pull request:

- updates with 2020 numbers
- [excise tax file ](https://www.irs.gov/pub/irs-soi/histab20.xls)

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@lpgoldstein It seems like you switched the number in the columns. The $120,453.00 should be in the surface mining column and the $131,213,000 should be in the subsurface column.

**Comment by Maroyafaied** [comment]
@lpgoldstein the build failed for some reason, I'll try to re-run it now.

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@Baymatt This PR is fixed and ready for your review.

**Review by Baymatt — APPROVED** [review]
Coal excise tax values and tax rates look correct.

**Pull request merged**
