### PR TITLE
Added docker container

### LINKED ISSUE #46: Create Docker/Kubernetes container

### PR DESCRIPTION
**Pull request by master12**
Fixes #46 

[:sunglasses: PREVIEW](https://46-docker-container.app.cloud.gov/)

Changes proposed in this pull request:

- Added docker support
-
-

### CODE REVIEW

**Comment by jlouis-onrr** [comment]
@master12, cant see the preview. Also, whats the best way to test this?

**Review by mojobnichols — APPROVED** [review]

**Comment by jlouis-onrr** [comment]
couldnt run on my windows machine due to permissions.  But in unix, I get the following error 'TypeError: Cannot read property 'fluid' of null' when accessing locally.


`% docker-compose up
Creating network "nrrd_default" with the default driver
Building web
Step 1/9 : FROM node:12.13.0
12.13.0: Pulling from library/node
9a0b0ce99936: Already exists
db3b6004c61a: Already exists
f8f075920295: Already exists
6ef14aff1139: Already exists
0bbd8b48260f: Already exists
524be717efb1: Already exists
da330b3729a7: Already exists
2c9863d012f5: Already exists
06cd084e76f0: Already exists
Digest: sha256:fc6c1371e3a0883f17e34492bcaffb4d8ad986ebb4a5eeafa8817bd425446566
Status: Downloaded newer image for node:12.13.0
 ---> 11e92fc50c4a
Step 2/9 : EXPOSE 8000
 ---> Running in d2aba9396e18
Removing intermediate container d2aba9396e18
 ---> f0bd38de218b
Step 3/9 : RUN npm install --quiet -g gatsby-cli
 ---> Running in 39ebcd1c8064
npm WARN deprecated @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/bin/gatsby -> /usr/local/lib/node_modules/gatsby-cli/cli.js

> core-js@2.6.11 postinstall /usr/local/lib/node_modules/gatsby-cli/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> gatsby-telemetry@1.3.32 postinstall /usr/local/lib/node_modules/gatsby-cli/node_modules/gatsby-telemetry
> node src/postinstall.js || true


> gatsby-cli@2.12.95 postinstall /usr/local/lib/node_modules/gatsby-cli
> node scripts/postinstall.js

Success!

Welcome to the Gatsby CLI! Please visit https://www.gatsbyjs.org/docs/gatsby-cli/ for more information.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/gatsby-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ink@2.7.1 requires a peer of @types/react@>=16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of gatsby@2.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of react@16.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of react-dom@16.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/alert@0.10.3 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/menu-button@0.10.3 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/combobox@0.10.3 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN theme-ui@0.2.52 requires a peer of @mdx-js/react@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/tabs@0.10.3 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/popover@0.10.3 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/tooltip@0.10.3 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/dialog@0.10.3 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/utils@0.10.5 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/visually-hidden@0.10.4 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/portal@0.10.5 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/auto-id@0.10.5 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/descendants@0.10.5 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/rect@0.10.5 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-remove-scroll@2.4.0 requires a peer of @types/react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN use-callback-ref@1.2.4 requires a peer of @types/react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-style-singleton@2.1.0 requires a peer of @types/react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-remove-scroll-bar@2.1.0 requires a peer of @types/react@^16.8.0 but none is installed. You must install peer dependencies yourself.

+ gatsby-cli@2.12.95
added 864 packages from 622 contributors in 61.207s
Removing intermediate container 39ebcd1c8064
 ---> 4a9f15c92fc2
Step 4/9 : WORKDIR /app
 ---> Running in cc9f5089d831
Removing intermediate container cc9f5089d831
 ---> da63bc7f5870
Step 5/9 : COPY ./package.json .
 ---> ab3ba261234f
Step 6/9 : RUN npm install
 ---> Running in 775b7d5b56a6
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated graphql-import@0.7.1: GraphQL Import has been deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-import for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142

> sharp@0.25.4 install /app/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-linux-x64.tar.gz

> core-js@2.6.11 postinstall /app/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js-pure@3.6.5 postinstall /app/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@3.6.5 postinstall /app/node_modules/gatsby-plugin-mdx/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@3.6.5 postinstall /app/node_modules/gatsby/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> gatsby-telemetry@1.3.32 postinstall /app/node_modules/gatsby-telemetry
> node src/postinstall.js || true


> mozjpeg@7.0.0 postinstall /app/node_modules/mozjpeg
> node lib/install.js

  ✔ mozjpeg pre-build test passed successfully

> pngquant-bin@6.0.0 postinstall /app/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully

> gatsby-cli@2.12.95 postinstall /app/node_modules/gatsby-cli
> node scripts/postinstall.js


> gatsby@2.24.57 postinstall /app/node_modules/gatsby
> node scripts/postinstall.js


> styled-components@4.4.1 postinstall /app/node_modules/styled-components
> node ./scripts/postinstall.js || exit 0

Use styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/babel-plugin-add-module-exports/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.13.0","npm":"6.12.0"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.2 requires a peer of @types/webpack@4.x but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.2 requires a peer of react-refresh@^0.8.3 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.2 requires a peer of sockjs-client@^1.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.2 requires a peer of type-fest@^0.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.2 requires a peer of webpack-plugin-serve@0.x || 1.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.2.1 requires a peer of @typescript-eslint/eslint-plugin@2.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.2.1 requires a peer of @typescript-eslint/parser@2.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.2.1 requires a peer of eslint-plugin-flowtype@3.x || 4.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.2.1 requires a peer of eslint-plugin-react-hooks@1.x || 2.x but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of gatsby@2.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of react@16.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of react-dom@16.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN The package app-root-dir is included as both a dev and production dependency.

added 3171 packages from 1688 contributors and audited 3188 packages in 159.648s
found 9 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container 775b7d5b56a6
 ---> a37edf13a489
Step 7/9 : COPY . .
 ---> 52b51609893e
Step 8/9 : RUN gatsby clean
 ---> Running in 422eed181eb5
╔════════════════════════════════════════════════════════════════════════╗
║                                                                        ║
║   Gatsby collects anonymous usage analytics                            ║
║   to help improve Gatsby for all users.                                ║
║                                                                        ║
║   If you'd like to opt-out, you can use `gatsby telemetry --disable`   ║
║   To learn more, checkout https://gatsby.dev/telemetry                 ║
║                                                                        ║
╚════════════════════════════════════════════════════════════════════════╝
info Deleting .cache, public, /app/node_modules/.cache/babel-loader,
info Successfully deleted directories
Removing intermediate container 422eed181eb5
 ---> f3f7aef4f406
Step 9/9 : CMD ["gatsby", "develop", "-H", "0.0.0.0" ]
 ---> Running in 0989ae2f8039
Removing intermediate container 0989ae2f8039
 ---> 50bdc394385f
Successfully built 50bdc394385f
Successfully tagged nrrd_web:latest
WARNING: Image for service web was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating nrrd_web_1 ... done
Attaching to nrrd_web_1
web_1  | success open and validate gatsby-configs - 0.187s
web_1  | success load plugins - 3.325s
web_1  | success onPreInit - 0.109s
web_1  | info One or more of your plugins have changed since the last time you ran Gatsby. As
web_1  | a precaution, we're deleting your site's cache to ensure there's no stale data.
web_1  | success initialize cache - 1.117s
web_1  | success copy gatsby files - 0.544s
web_1  | success onPreBootstrap - 0.079s
web_1  | success createSchemaCustomization - 0.034s
web_1  | 
web_1  |  ERROR #11321  PLUGIN
web_1  | 
web_1  | "gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:
web_1  | 
web_1  | unknown: Unexpected token (9:95)
web_1  | 
web_1  |   7 | import * as React from 'react'
web_1  |   8 |
web_1  | > 9 | export default { graphql, MDXRenderer, // import Grid, Typography, MuiLink, makeStyles, React }
web_1  |     |                                                                                                ^
web_1  | 
web_1  |   31 |   const createAndProcessNode = path => {
web_1  |   32 |     const fileNodePromise = createFileNode(path, createNodeId, pluginOptions).then(fileNode => {
web_1  | > 33 |       createNode(fileNode);
web_1  |      |       ^
web_1  |   34 |       return null;
web_1  |   35 |     });
web_1  |   36 |     return fileNodePromise;
web_1  | 
web_1  | File: node_modules/gatsby-source-filesystem/gatsby-node.js:33:7
web_1  | 
web_1  | 
web_1  | 
web_1  |   SyntaxError: unknown: Unexpected token (9:95)
web_1  |     7 | import * as React from 'react'
web_1  |     8 | 
web_1  |   > 9 | export default { graphql, MDXRenderer, // import Grid, Typography, MuiLi  nk, makeStyles, React }
web_1  |       |                                                                                                  ^
web_1  |   SyntaxError: unknown: Unexpected token (9:95)
web_1  |     7 | import * as React from 'react'
web_1  |     8 | 
web_1  |   > 9 | export default { graphql, MDXRenderer, // import Grid, Typography, MuiLi  nk, makeStyles, React }
web_1  |       |                                                                                                  ^
web_1  |   
web_1  |   - error.js:60 Parser._raise
web_1  |     [app]/[@babel]/parser/src/parser/error.js:60:45
web_1  |   
web_1  |   - error.js:55 Parser.raiseWithData
web_1  |     [app]/[@babel]/parser/src/parser/error.js:55:17
web_1  |   
web_1  |   - error.js:39 Parser.raise
web_1  |     [app]/[@babel]/parser/src/parser/error.js:39:17
web_1  |   
web_1  |   - util.js:139 Parser.unexpected
web_1  |     [app]/[@babel]/parser/src/parser/util.js:139:16
web_1  |   
web_1  |   - expression.js:2332 Parser.parseIdentifierName
web_1  |     [app]/[@babel]/parser/src/parser/expression.js:2332:18
web_1  |   
web_1  |   - expression.js:2298 Parser.parseIdentifier
web_1  |     [app]/[@babel]/parser/src/parser/expression.js:2298:23
web_1  |   
web_1  |   - expression.js:1279 Parser.parseMaybePrivateName
web_1  |     [app]/[@babel]/parser/src/parser/expression.js:1279:19
web_1  |   
web_1  |   - expression.js:1958 Parser.parsePropertyName
web_1  |     [app]/[@babel]/parser/src/parser/expression.js:1958:18
web_1  |   
web_1  |   - expression.js:1748 Parser.parsePropertyDefinition
web_1  |     [app]/[@babel]/parser/src/parser/expression.js:1748:22
web_1  |   
web_1  |   - expression.js:1648 Parser.parseObjectLike
web_1  |     [app]/[@babel]/parser/src/parser/expression.js:1648:25
web_1  |   
web_1  |   - expression.js:1091 Parser.parseExprAtom
web_1  |     [app]/[@babel]/parser/src/parser/expression.js:1091:21
web_1  |   
web_1  |   - expression.js:563 Parser.parseExprSubscripts
web_1  |     [app]/[@babel]/parser/src/parser/expression.js:563:23
web_1  |   
web_1  |   - expression.js:543 Parser.parseUpdate
web_1  |     [app]/[@babel]/parser/src/parser/expression.js:543:21
web_1  |   
web_1  |   - expression.js:527 Parser.parseMaybeUnary
web_1  |     [app]/[@babel]/parser/src/parser/expression.js:527:17
web_1  |   
web_1  |   - expression.js:343 Parser.parseExprOps
web_1  |     [app]/[@babel]/parser/src/parser/expression.js:343:23
web_1  |   
web_1  |   - expression.js:308 Parser.parseMaybeConditional
web_1  |     [app]/[@babel]/parser/src/parser/expression.js:308:23
web_1  |   
web_1  |   - expression.js:263 Parser.parseMaybeAssign
web_1  |     [app]/[@babel]/parser/src/parser/expression.js:263:21
web_1  |   
web_1  |   - expression.js:218 callback
web_1  |     [app]/[@babel]/parser/src/parser/expression.js:218:12
web_1  |   
web_1  |   - expression.js:2617 Parser.allowInAnd
web_1  |     [app]/[@babel]/parser/src/parser/expression.js:2617:16
web_1  |   
web_1  |   - expression.js:217 Parser.parseMaybeAssignAllowIn
web_1  |     [app]/[@babel]/parser/src/parser/expression.js:217:17
web_1  |   
web_1  |   - statement.js:1815 Parser.parseExportDefaultExpression
web_1  |     [app]/[@babel]/parser/src/parser/statement.js:1815:24
web_1  |   
web_1  |   - statement.js:1707 Parser.parseExport
web_1  |     [app]/[@babel]/parser/src/parser/statement.js:1707:31
web_1  |   
web_1  |   - statement.js:249 Parser.parseStatementContent
web_1  |     [app]/[@babel]/parser/src/parser/statement.js:249:25
web_1  |   
web_1  |   - statement.js:151 Parser.parseStatement
web_1  |     [app]/[@babel]/parser/src/parser/statement.js:151:17
web_1  |   
web_1  |   - statement.js:871 Parser.parseBlockOrModuleBlockBody
web_1  |     [app]/[@babel]/parser/src/parser/statement.js:871:25
web_1  |   
web_1  |   - statement.js:841 Parser.parseBlockBody
web_1  |     [app]/[@babel]/parser/src/parser/statement.js:841:10
web_1  |   
web_1  |   - statement.js:55 Parser.parseTopLevel
web_1  |     [app]/[@babel]/parser/src/parser/statement.js:55:10
web_1  |   
web_1  |   - index.js:57 Parser.parse
web_1  |     [app]/[@babel]/parser/src/parser/index.js:57:10
web_1  |   
web_1  |   - index.js:58 parse
web_1  |     [app]/[@babel]/parser/src/index.js:58:38
web_1  |   
web_1  |   - index.js:54 parser
web_1  |     [app]/[@babel]/core/lib/parser/index.js:54:34
web_1  |   
web_1  |   - parser.next
web_1  |   
web_1  |   - normalize-file.js:93 normalizeFile
web_1  |     [app]/[@babel]/core/lib/transformation/normalize-file.js:93:38
web_1  |   
web_1  |   - normalizeFile.next
web_1  |   
web_1  |   - index.js:31 run
web_1  |     [app]/[@babel]/core/lib/transformation/index.js:31:50
web_1  |   
web_1  |   - run.next
web_1  |   
web_1  |   - transform.js:27 Function.transform
web_1  |     [app]/[@babel]/core/lib/transform.js:27:41
web_1  |   
web_1  |   - transform.next
web_1  |   
web_1  |   - index.js:244 evaluateSync
web_1  |     [app]/[gensync]/index.js:244:28
web_1  |   
web_1  |   - index.js:84 Function.sync
web_1  |     [app]/[gensync]/index.js:84:14
web_1  |   
web_1  |   - transform.js:36 Object.transform
web_1  |     [app]/[@babel]/core/lib/transform.js:36:54
web_1  |   
web_1  |   - on-create-node.js:100 cacheScope
web_1  |     [app]/[gatsby-plugin-mdx]/gatsby/on-create-node.js:100:26
web_1  |   
web_1  |   - on-create-node.js:72 Object.module.exports [as onCreateNode]
web_1  |     [app]/[gatsby-plugin-mdx]/gatsby/on-create-node.js:72:9
web_1  |   
web_1  |   - api-runner-node.js:350 runAPI
web_1  |     [app]/[gatsby]/src/utils/api-runner-node.js:350:16
web_1  |   
web_1  |   - From previous event:
web_1  |   
web_1  |   - api-runner-node.js:460 Promise.catch.decorateEvent.pluginName
web_1  |     [app]/[gatsby]/src/utils/api-runner-node.js:460:9
web_1  |   
web_1  |   - From previous event:
web_1  |   
web_1  |   - api-runner-node.js:459 
web_1  |     [app]/[gatsby]/src/utils/api-runner-node.js:459:14
web_1  |   
web_1  |   - timers.js:439 processImmediate
web_1  |     internal/timers.js:439:21
web_1  |   
web_1  |   - From previous event:
web_1  |   
web_1  |   - api-runner-node.js:451 
web_1  |     [app]/[gatsby]/src/utils/api-runner-node.js:451:13
web_1  |   
web_1  |   - From previous event:
web_1  |   
web_1  | 
web_1  | success Checking for changed pages - 0.040s
web_1  | success source and transform nodes - 47.611s
web_1  | warn There are conflicting field types in your data.
web_1  | 
web_1  | If you have explicitly defined a type for those fields, you can safely ignore this warning message.
web_1  | Otherwise, Gatsby will omit those fields from the GraphQL schema.
web_1  | 
web_1  | If you know all field types in advance, the best strategy is to explicitly define them with the
web_1  | `createTypes` action, and skip inference with the `@dontInfer` directive.
web_1  | ComponentProp.type.value:
web_1  |  - type: array
web_1  |    value: [ ..., { value: "'DownloadXls'", computed: false, name: 'object' }, ... ]
web_1  |  - type: object
web_1  |    value: { name: 'object' }
web_1  | ComponentProp.parentType.value:
web_1  |  - type: array
web_1  |    value: [ ..., { value: "'DownloadXls'", computed: false, name: 'object' }, ... ]
web_1  |  - type: object
web_1  |    value: { name: 'object' }
web_1  | success building schema - 2.371s
web_1  | info creating components cache index
web_1  | success createPages - 0.458s
web_1  | success Checking for changed pages - 0.002s
web_1  | success createPagesStatefully - 5.126s
web_1  | success update schema - 0.080s
web_1  | success write out redirect data - 0.008s
web_1  | success Build manifest and related icons - 0.376s
web_1  | success onPostBootstrap - 0.391s
web_1  | info bootstrap finished - 67.865s
web_1  | success onPreExtractQueries - 0.003s
web_1  | success extract queries from components - 7.086s
web_1  | success write out requires - 0.245s
web_1  | warn Query takes too long:
web_1  | File path: /app/src/components/GlossaryTerm/GlossaryTerm.js
web_1  | success run static queries - 46.930s - 18/18 0.38/s
web_1  | success run page queries - 0.473s - 41/41 86.76/s
web_1  | success Generating image thumbnails - 111.991s - 55/55 0.49/s
web_1  | ⠀
web_1  | You can now view gatsby-starter-default in the browser.
web_1  | ⠀
web_1  |   Local:            http://localhost:8000/
web_1  |   On Your Network:  http://172.18.0.2:8000/
web_1  | ⠀
web_1  | View GraphiQL, an in-browser IDE, to explore your site's data and schema
web_1  | ⠀
web_1  |   Local:            http://localhost:8000/___graphql
web_1  |   On Your Network:  http://172.18.0.2:8000/___graphql
web_1  | ⠀
web_1  | Note that the development build is not optimized.
web_1  | To create a production build, use gatsby build
web_1  | ⠀
web_1  | warn "export 'default' (reexported as 'FilterToggleInput') was not found in
web_1  | success Building development bundle - 71.210s
web_1  | ⠀
web_1  | Could not open DoiLogoImg.js in the editor.
web_1  | ⠀
web_1  | To set up the editor integration, add something like REACT_EDITOR=atom to the .env.local file in your project folder and restart the development server. Learn more: https://goo.gl/MMTaZt
web_1  |`

**Comment by master12** [comment]
has nothing to do with the docker container. Can you try and rerun it.

**Comment by jlouis-onrr** [comment]
@master12, tried again.  Its still erroring out.

**Comment by master12** [comment]
the error is not related to the docker container so wil merge this and create a seperate issue

**Pull request merged**
