### PR TITLE
Streamline site header

### LINKED ISSUE #950: Streamline site header
Jerome wants to visually streamline the site header to make it match better with the new Explore Data and Query Tool pages.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #950

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/950-SiteHeader/)

Changes proposed in this pull request:

- Updates old header to new appHeader using default base toolbar as its base
- Adds new updated NRRD logo svg
- Updates menu to be in-line
- Places home and about links into footer
- Adds two new primary/secondary header colors
- Updated styling and new mobile menu
- Updated site search bar

### CODE REVIEW

**Comment by mcharg** [comment]
The search text still doesn't have enough contrast.  Try #DEDEDE to get it up to AA levels - can't get to AAA with that background color.
image

image

**Comment by mcharg** [comment]
I'm going to use this preview link for the user testing next week, so we can test the new header and chart colors.

**Comment by mcharg** [comment]
The revenue by company graphs aren't showing up.
image

**Comment by mcharg** [comment]
@jlouis-onrr Can you apply the new colors to the revenue by company graph?

**Review by mcharg — APPROVED** [review]

**Comment by mcharg** [comment]
I added @lpgoldstein to review, since Jennifer is out this week.

**Review by lpgoldstein — APPROVED** [review]

**Comment by mcharg** [comment]
@jlouis-onrr Got New Mexico to turn blue in top locations.  I selected Montana and then Wyoming and then switched from Revenue to Disbursements to Production and back to Revenue and it was blue.
image

**Comment by mcharg** [comment]
@jlouis-onrr For the second participant, the mobile menu was displaying at a fairly large viewport size.  It was a standard laptop size.

**Review by mcharg — APPROVED** [review]

**Comment by mcharg** [comment]
@jlouis-onrr Is it possible to make it consistent what gets which color.  For example, other revenues is getting two different colors in the revenue by company chart.
image

**Comment by jlouis-onrr** [comment]
> @jlouis-onrr Is it possible to make it consistent what gets which color. For example, other revenues is getting two different colors in the revenue by company chart.
> image

The reason this happens is due to the position of the element.  If the first company, Other Revenues is the third position in the array so it gets the third color specified.  Where in the second company, its in the sixth position.  I guess we would have to have the items all be ordered in the same order.  @mojobnichols do you have some thoughts on how to achieve this?

**Comment by jlouis-onrr** [comment]
@mcharg, regarding the mobile kicking in.  Currently its setup to start around 1280, which is pretty large.  The overlap of icon, menu and search happens around 1160px.  Im thinking, about swapping the explore menu items to be housed under one button around the 1160 breakpoint, then when the header gets closer to mobile (around 600), then do the full change over to mobile menu?  Thoughts?

**Comment by jennmalcolm** [comment]
The color issue always representing the same thing, we have discussed before and decided to keep it as by position/size. It's not ideal for me, but I think that's the best we can do, especially here where you can't really see most of the small slices of the chart anyway. I did create a new issue #1037 for consistent placement of the "other revenues" in the legend.

**Comment by mcharg** [comment]
I think we decided on not having the same color represent the same thing was okay for the circle charts, but it's different for the bar charts, especially if the legends are collapsed, users may just expand one and assume the same color means the same thing.

**Comment by mcharg** [comment]
@jlouis-onrr I like what you did with the header at medium breakpoints.

**Review by mcharg — APPROVED** [review]

**Comment by mcharg** [comment]
@jlouis-onrr Another participant got the blue circle.  It changed when she switched from CY to FY.
image

**Review by jennmalcolm — APPROVED** [review]

**Pull request merged**
