### PR TITLE
439 add production units

### LINKED ISSUE #439: Add production units to explore data page
Requires having a separate units column in the database.

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #439 

[:sunglasses: PREVIEW](https://439-AddProductionUnits.app.cloud.gov/explore/)

Changes proposed in this pull request:

Added units and overview to production

-
-
-

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@mojobnichols is it possible to remove the dollar signs on the scale?
image

**Comment by mcharg** [comment]
@mojobnichols I'm getting a 404 error on the preview link.

**Comment by mojobnichols** [comment]
Added units to map legend

**Comment by jennmalcolm** [comment]
@mojobnichols the units are there, but there is still a dollar sign on the numbers on production. Can you remove that, too?

**Comment by jennmalcolm** [comment]
Sorry I meant to submit this comment last week, but could you change this unit on the detailed cards to be in parentheses? 
image

**Comment by jennmalcolm** [comment]
And could you remove the parentheses from the unit that comes right after the numbers on the line graph @mojobnichols? 
image

**Comment by jennmalcolm** [comment]
@mojo, this unit on the top locations legend should be in parentheses. Basically, if it comes right after the number, it shouldn't have parentheses. Otherwise, it should. 
image

**Comment by mojobnichols** [comment]
@jennmalcolm fixed the y label in top locations legend to have parens.

**Comment by jennmalcolm** [comment]
@mojobnichols one more thing (sorry): 

Can you add a space between the number and the unit in the top locations circles?

image

**Comment by jennmalcolm** [comment]
@mojobnichols the "something went wrong" error doesn't come as fast, but I'm still getting it. This is how you can reproduce the one I just got:

Go to production
Select NV, ND, SD
Select Gypsum
Change to Gold
Get error
image

**Comment by jennmalcolm** [comment]
@mojobnichols did you look into the something went wrong? I'm not getting the same errors in dev (although I did in production), so it might be something in this branch. If you determine we should merge this and see if it works in dev, let me know.

**Comment by mojobnichols** [comment]
The error was from adding unit_abbr to queries and accessing it.   It has been corrected in this PR.  The error in beta and not dev was a different fix.

**Pull request merged**
