### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:
## Updated Calendar Year production data  (CY03 -2020)
@Baymatt here's the [original file](https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Production/Federal%20&%20Indian%20CY03-20%20Production%20Final%20File.xlsx?web=1) , please compare it to the download file in the preview link and go through the check list. Thank you 

Explore Data - Map and Detail Card 
- [x] Select a year and select a state with data, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [x] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected
 
- [x] Select a year and select a county with data, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [x] Period - Calendar Year
    - [x]  Period - Fiscal Year
    - [x] With only 2-3 commodities selected.

- [x] Select a year and select an offshore area, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [x] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected.
 
- [x] Select a state and county without data and verify the expected information is displayed.
- [x] Add Nationwide Federal Card and verify the expected information is displayed.
- [x] Add Native American Card and verify the expected information is displayed.

Explore Data - Nationwide Production Summary and Top Nationwide Locations
- [x] Verify breakdowns by production type and source are correct as well nationwide locations for the conditions below.
- [x] Not current Calendar Year
- [x] Current Calendar Year
- [x] Not current Fiscal Year
- [x] Current Fiscal Year

Query Data 
  
- [x]  One Land Type filter
- [x]  One State
- [x]  One Offshore Region
- [x]  One to three Product
- [x]  Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

## Other changes
- [x] **Update Federal Reforms Page**
- [x] **Update Federal Laws Page**
- [x] **Fix bug in blog when click next page**
- [x] **Remove FY 2003 for revenue in explore data and query tool**
- [x] **Enhancement to production homepage tab**
- [x] **Fix Query tool revenue link**
- [x] **Fix Query tool disbursement blank checkbox**

### CODE REVIEW

**Comment by mcharg** [comment]
@mojobnichols I'm getting the blog bug when I click Older from page 2. 
image

**Review by mcharg — APPROVED** [review]
Checked all changes, except the data changes.

**Review by Baymatt — APPROVED** [review]
CY Production data looks good on my end

**Comment by Maroyafaied** [comment]
@mojobnichols @jlouis-onrr I get error message when I click on the monthly revenue or when I go to the production tab in dev. 
image

**Review by daniel-coleman-1 — APPROVED** [review]

**Review by meshanw — APPROVED** [review]
Not sure what all I'm looking at.

**Pull request merged**
