### PR TITLE
Update monthly data 

### LINKED ISSUE #1664: Upload June disbursements data

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #1664 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/upload-monthly-data/)

Changes proposed in this pull request:

- Uploaded June 2021 Disbursement data 

@daniel-coleman-1  Please use this checklist to check Disbursements Monthly

**Download Page**
- [x] Dates and file size are correct for csv and excel

- [x] Check download file against [raw file ](https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Disbursements/FY21/Q3%20Total%20Web%20Data%20(Jun).xlsx?web=1)

- [x]  Check  Treasury Fund column is deleted  

- [x] Check  Hidalgo Caounty is changed to Hidalgo County under county column 

- [x] Check  "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column 

**Homepage - Yearly Breakdown**
    

- [x] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x]     Breakout - Source 
- [x]     Breakout - Recipient

 
**Homepage - Monthly Breakdown**
- [x] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
  

- [x]   Period - Most recent 12 months
- [x]   Period - Fiscal Year
- [x]  Period
- [x]  Calendar Year
- [x]  Breakout - Source
- [x]  Breakout - Recipient

**Query Data**
  

- [x]   One Recipient
- [x]     One Source
- [x]     One State
- [x]     One to three Commodities if applicable
- [x]     Clear All and change grouping
- [x]     Downloads matches filtered data

**Monthly Snap Shot**

- [x] Check graphs match homepage

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@cthomasONRR Please use this checklist to check disbursement monthly data


**Download Page**
- [ ] Dates and file size are correct for csv and excel

- [ ] Check download file against [raw file ](https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Disbursements/FY21/Q3%20Total%20Web%20Data%20(Jun).xlsx?web=1)

- [ ]  Check  Treasury Fund column is deleted  

- [ ] Check  Hidalgo Caounty is changed to Hidalgo County under county column 

- [ ] Check  "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column 

**Homepage - Yearly Breakdown**
    

- [ ] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [ ]     Breakout - Source 
- [ ]     Breakout - Recipient

 
**Homepage - Monthly Breakdown**
- [ ] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
  

- [ ]   Period - Most recent 12 months
- [ ]   Period - Fiscal Year
- [ ]  Period
- [ ]  Calendar Year
- [ ]  Breakout - Source
- [ ]  Breakout - Recipient

**Query Data**
  

- [ ]   One Recipient
- [ ]     One Source
- [ ]     One State
- [ ]     One to three Commodities if applicable
- [ ]     Clear All and change grouping
- [ ]     Downloads matches filtered data


**Monthly Snap Shot**

- [ ] Check graphs match homepage

**Review by cthomasONRR — APPROVED** [review]
Everything looks good!

**Review by daniel-coleman-1 — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 please go through your checklist and mark off what you checked as you review the data. Thanks

**Review by daniel-coleman-1 — APPROVED** [review]

**Comment by daniel-coleman-1** [comment]
Looks good to me!

**Comment by cthomasONRR** [comment]
Checklist for Revenue:

Revenue
**Revenue** 	

Homepage - Yearly Breakdown
- [ ] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout - Commodity
 
Homepage - Monthly Breakdown
- [ ] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout Commodity
 
Homepage - Source File
- [ ] Check source file links are correct.
 
Explore Data - Map and Detail Card
- [ ] Select a year and select a state with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected
 
- [ ] Select a year and select a county with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected.
 
- [ ] Select a year and select an offshore area, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected.
 
- [ ] Select a state and county without data and verify the expected information is displayed.
- [ ] Add Nationwide Federal Card and verify the expected information is displayed.
- [ ] Add Native American Card and verify the expected information is displayed.

Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- [ ] Verify breakdowns by revenue type and source are correct as well nationwide locations for the conditions below.
    - [ ] Not current Calendar Year
    - [ ] Current Calendar Year
    - [ ] Not current Fiscal Year
    - [ ] Current Fiscal Year

Query Data
    - [ ] With a selected fiscal or calendar  year range, verify the data is correct and then for the conditions below. 
    - [ ] One Land Type filter
    - [ ] One Revenue Type filter
    - [ ] One State
    - [ ] One Offshore Region
    - [ ] One to three Commodities
    - [ ] Clear All and change grouping
    - [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by cthomasONRR** [comment]
Checklist for Production:

**Production Monthly** 

Homepage - Yearly Breakdown
- [ ] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- [ ] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Source File
- [ ] Check source file links are correct.

Query Data
    - [ ] One Land Type filter
    - [ ] One State
    - [ ] One Offshore Region
    - [ ] One to three Product
    - [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by mojobnichols** [comment]
@Maroyafaied @cthomasONRR  @daniel-coleman-1 

I fixed disbursement bug.   Numbers should be correct in comparison data.   If someone could verify that would be great.

**Comment by cthomasONRR** [comment]
> @Maroyafaied @cthomasONRR @daniel-coleman-1
> 
> I fixed disbursement bug. Numbers should be correct in comparison data. If someone could verify that would be great.

@mojobnichols - Checking this is on my to-do list for first thin tomorrow morning!

**Comment by Maroyafaied** [comment]
@mojobnichols @cthomasONRR I checked a few years and it looks good, I checked FY10, FY11 and FY 12. @cthomasONRR please check a couple other years to be sure , this data will be in Fiscal Year disbursements file in the download page. Thanks

**Comment by cthomasONRR** [comment]
@mojobnichols @Maroyafaied I checked FY13-FY20. 

I'm seeing something odd in the visualization. In 2019, the Historic Preservation Fun got its typical $150mil and this is shown when you click on the 2019 bar. The sums shown here match the downloaded excel:
image

But when you click on the 2020 bar, it shows the 2019 HPF as 0, and the 2019 sum is incorrect (the $150mil is subtracted out)
image

The same thing happens for 2020 and 2021 for the HPF. This is the only weird thing I'm seeing.... all the other Funds look correct.

**Comment by Maroyafaied** [comment]
@cthomasONRR For production, are you using the monthly file to check the data against the visual? I just checked coal for CY 2011 and got the same number as the visual.  
image

**Comment by cthomasONRR** [comment]
@Maroyafaied - I get the correct numbers when using the monthly data downloads. I get numbers that are slightly off when using the all production yearly download.

**Comment by Maroyafaied** [comment]
> @Maroyafaied - I get the correct numbers when using the monthly data downloads. I get numbers that are slightly off when using the all production yearly download.

@cthomasONRR yes, the numbers will be different in both files, the production monthly file only has oil, gas, coal data and reflects adjustments made to production reporting since this is accounting year data. Here's a brief explanation in the production monthly download page. 
image

**Comment by cthomasONRR** [comment]
@Maroyafaied Ok!!! Glad this one was me just being new to the datasets!!!

**Comment by cthomasONRR** [comment]
@mojobnichols 

I just re-checked- Revenue and Disbursements look great!

The Production numbers look good, but I'm seeing two minor visualization issues. First, the comparison year has the volume in parenthesis while the current year doesn't. I think this can be removed. Second, for coal the tables are mis-aligned. The nil for Federal offshore is missing from the comparison year and misaligning the tables:
image

**Comment by Maroyafaied** [comment]
@cthomasONRR the table for coal is aligned for me, can you check again? Also, we have the unit mentioned on top of the graph so I think that's why we decided not to repeat it in the design in the first table but it's something we can ask users about if it causes confusion in future studies. 

image

**Comment by cthomasONRR** [comment]
@Maroyafaied Mojo fixed the coal table alignment last week, so we're good there.

I mentioned the unit issue previously, and it might be something that Mojo fixes later on.

**Comment by Maroyafaied** [comment]
@cthomasONRR Ok, I will merge this PR then since everything is fixed for it. Thanks

**Pull request merged**
