### PR TITLE
Explore more scroll down/scroll up update

### LINKED ISSUE #647: Explore Data: The explore more button looks like a drop-down
One participant pointed this out in user research and several participants didn't know there was more than the map, so we should explore other visuals.

The arrow does look just like the ones on our drop-downs:

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #647

[:sunglasses: PREVIEW](https://647-exploremorebuttonlookslikedropdown.app.cloud.gov/explore)

Changes proposed in this pull request:

- moves button arrow to the bottom
- adds addition description text for the action of the button (Scroll down/Scroll up)
- explore data year slider updates to get slider more inline with other inputs

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr Preview link is broken.

**Comment by jlouis-onrr** [comment]
@mcharg, seems to be working for me, Can you try doing a hard refresh(ctrl + F5) to see if that helps?

**Comment by mcharg** [comment]
@jlouis-onrr Doesn't fix it.

**Comment by jlouis-onrr** [comment]
hmmm....   https://647-exploremorebuttonlookslikedropdown.app.cloud.gov/explore

**Comment by mcharg** [comment]
image
I even tried in other browsers and it's not working.

**Comment by jlouis-onrr** [comment]
@mcharg, appears to have build successfully now.  Can you try again?

**Comment by mcharg** [comment]
@jlouis-onrr I got in and approved the PR.

**Pull request merged**
