### PR TITLE
New wording for cards when there is no data/Update chart and comparison tables

### LINKED ISSUE #1396: Implement new wording on cards for when there is no data
For commodity
(state/county/offshore region) has not produced any (commodity) from (year) to (year).

For data type
(state/county/offshore region) did not have (data type) from (year) to (year).

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #1396

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1396-NewWordingCards/)

Changes proposed in this pull request:

- Updates wording for cards when there is no data for commodity or data types
- Adds new period all years to get min and max years for explore data
- Updates alignment of homepage chart legend and comparison tables

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr Can you change production from "has not" to "did not" to be consistent with revenue and disbursements?
image

**Review by mcharg — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@jlouis-onrr Is the wording only apply when there is no data at all in the entire time period or during any period there's no data? It's not showing up for cards when there's no revenue on the selected year. 
image

**Comment by mcharg** [comment]
@Maroyafaied We want to have the sparkline when there is no data for one year, but data in other years, so we opted to not have the text in those instances.

**Comment by mcharg** [comment]
The way we're displaying $0,000 is weird in those instances.

**Comment by Maroyafaied** [comment]
> @Maroyafaied We want to have the sparkline when there is no data for one year, but data in other years, so we opted to not have the text in those instances.

Ok just wanted to make sure if the wording was supposed to be displayed in those instances or not.

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
