### PR TITLE
Updates for Nationwide Federal

### LINKED ISSUE #193: Explore Data: Change National card to be Nationwide Federal
And don't include Native American data.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #193, #168

[:sunglasses: PREVIEW](https://168-builddetailedrevenuecomparisoncards.app.cloud.gov/explore)

Changes proposed in this pull request:

- Fixes totals
- Adds federal percentage
- Adds Totals to cards
- Adds sparkline to cards
- Adds revenue trend years
- Minor box styling for cards

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr Can you add some space above the sparkline, so it's clear the label above goes with the total and not the sparkline?  The sparkline could also be bigger on this version of the cards.
image

**Comment by mcharg** [comment]
The numbers look good.

**Comment by jlouis-onrr** [comment]
For sure, I'll adjust the spacing on that.

**Comment by jennmalcolm** [comment]
Is this ready to merge @jlouis-onrr? I'm just trying to clean up and close the last sprint.

**Comment by jlouis-onrr** [comment]
Yep, Ill merge this into dev.

**Pull request merged**
