### PR TITLE
UpdateDisclaimer

### LINKED ISSUE #1747: Add disclaimers to NRRD Glossary
Language to add at the top of the glossary page:

<p>The definitions in this glossary are simplified. Some are NRRD-specific in their usage. None of the definitions takes precedence over laws, legislation, regulations, contracts, or specific interpretations or rulings.</p>

<p>This glossary defines many commonly used terms and acronyms but isn’t a full list. To request changes to terms on this list, or to suggest new terms be added, email <a href=mailto:nrrd@onrr.gov>nrrd@onrr.gov</a>.</p>

Idea came from the glossary issue [#906](https://app.zenhub.com/workspaces/data-display-5464fa79c3cc8d7f4c384eaf/issues/onrr/onrr.gov-site/906)

This issue is linked to PR #1752

### PR DESCRIPTION
**Pull request by cthomasONRR**
Fixes #1747

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/GlossaryDisclaimer)

Changes proposed in this pull request:

- Adding disclaimers to the glossary webpage

### CODE REVIEW

**Comment by cthomasONRR** [comment]
@jlouis-onrr Hi Jerome, I'm trying to add 2 paragraphs of disclaimers to the NRRD Glossary. Shannon and I are struggling to identify which markdown file is the correct location to add this static text right below the Glossary page title. Could you please help us find the correct markdown file location? Thanks!

**Comment by jlouis-onrr** [comment]
@mcharg and @cthomasONRR, the disclaimer updates are now out.

**Comment by cthomasONRR** [comment]
@jlouis-onrr I just checked out the preview, and this is perfect!

**Comment by mcharg** [comment]
@cthomasONRR The mailto link isn't working.  I think you might need to get rid of a space after "mailto:"

**Comment by cthomasONRR** [comment]
@mcharg Oh weird, the mailto link is working for me!

**Comment by mcharg** [comment]
The one in the footer isn't working for me, either.  I'll check my browser settings.

**Comment by mcharg** [comment]
I think I clicked on something recently that offered to make Outlook web my default mailto application instead of Outlook desktop, but now I can't find where to change the setting.  I'll assume it's a problem on my end.

**Review by mcharg — APPROVED** [review]

**Comment by mcharg** [comment]
Figured it out.  I changed the setting back and now it's opening Outlook desktop when I click the email link.

**Comment by cthomasONRR** [comment]
@mcharg thanks for your review!!!

**Comment by Maroyafaied** [comment]
@cthomasONRR @mcharg Do you think saying "NRRD" specific could be confusing to users since we don't define or explain what NRRD is referring to ? 
image

**Comment by cthomasONRR** [comment]
> @cthomasONRR @mcharg Do you think saying "NRRD" specific could be confusing to users since we don't define or explain what NRRD is referring to ? image

@Maroyafaied would saying 'ONRR' specific be better? This might be good since we eventually want 1 glossary for both websites.
Or we can rephrase to "Some definitions are specific to Natural Resources Revenue Data in their usage."

**Comment by Maroyafaied** [comment]
@cthomasONRR I think it's better to rephrase as you suggested to "Some definitions are specific to Natural Resources Revenue Data in their usage" or "Some definitions are specific to the agency in their usage."

**Comment by mcharg** [comment]
I agree with Maroya.

**Comment by cthomasONRR** [comment]
@Maroyafaied @mcharg Updating it to say "Some definitions are specific to the agency in their usage."

**Comment by Maroyafaied** [comment]
@cthomasONRR Thank you, I don't mean to be a pain but I didn't want an abbreviation on the glossary page that's not defined lol

**Pull request merged**
