### PR TITLE
Add smart query links on detail cards

### LINKED ISSUE #328: Make query tool links on detail cards smart (and add them back)
They should automatically filter to the state or county that the card is for and be grouped by the appropriate thing.

For example, the link here should filter to Colorado, grouped by commodity with no breakout.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #328

[:sunglasses: PREVIEW](https://328-querytoollinks.app.cloud.gov/explore)

Changes proposed in this pull request:

- adds QueryTool component to handle smart query links

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr Can you reduce the space below the links?
image

**Comment by mcharg** [comment]
@jlouis-onrr For the county card, since we took off county as a filter, I'm thinking we should group by county and then by what I said to group by.  Is that possible?

**Comment by mcharg** [comment]
@jlouis-onrr It's wrapping the revenue by commodity link on some cards, but not all (state isn't wrapping).  Is it possible to get it to not wrap on all?
image

**Comment by mcharg** [comment]
@jlouis-onrr On revenue, when you have a commodity selected, can we carry that to the query tool?

**Comment by mcharg** [comment]
On the nationwide summary, is it possible to move up the query link inline with the header to reduce the space between the header and the table? 
image

**Comment by mcharg** [comment]
Floating key is back (at the bottom of Revenue).
image

**Comment by mcharg** [comment]
Production by commodity on the Nationwide card is only selecting federal offshore for land type.  It should select everything but Native American.
image
image

**Comment by mcharg** [comment]
Production state card, let's group by county instead of state/offshore region for both links, since that's the only option with more than one value.
image

**Comment by mcharg** [comment]
The link from the county production card should be grouped by county, as well.

**Comment by mcharg** [comment]
The link from the Native American production card would make more sense grouped by land type, so we're not leading with "location not published".

**Comment by mcharg** [comment]
Disbursements Nationwide - need to remove Native American from selected recipients.

**Comment by mcharg** [comment]
State disbursements - Need to select the state.

**Comment by mcharg** [comment]
The link from the disbursements circle chart says it's revenue.
image

**Comment by mcharg** [comment]
Production circle chart link is hidden below the chart.  Could we try putting it right under the table for the circle charts? 
image

**Comment by mcharg** [comment]
- [ ] We should add links to the county and Native American disbursements cards that have the data for Native American and the state sorted by county, so users can get to that data.
image

**Comment by mcharg** [comment]
- [ ] @jlouis-onrr Can you reduce the space under the links below the circle charts?
image

**Comment by mcharg** [comment]
@jlouis-onrr I noted above which items are fixed and added new checkboxes for the one that aren't.

**Comment by jlouis-onrr** [comment]
> * [ ]  Production circle chart link is hidden below the chart.  Could we try putting it right under the table for the circle charts?
>   image
> * [ ]  @jlouis-onrr Not fixed

@mcharg, this one is really hard to achieve as the chart and legend are d3.  So, placement of the link has to be placed before or after.  Maybe, I can create a header component that excepts a link component that would be placed inline with the header, then below the header for mobile views?

**Comment by mcharg** [comment]
- [ ] @jlouis-onrr The change to the top locations links did it for the charts in the detail cards, as well as the big one.
image

**Comment by mcharg** [comment]
@jlouis-onrr I noted which things are fixed and added checkboxes in a couple places where one link on the detail card is fixed, but the second one isn't.

**Comment by mcharg** [comment]
@jlouis-onrr The link on the nationwide production card for by location is missing.
image

**Comment by mcharg** [comment]
@jlouis-onrr It's actually missing for all the cards for the top locations circle chart.

**Pull request merged**
