### PR TITLE
Add glossaries to stacked bar charts

### LINKED ISSUE #1453: Add glossaries to vertical bar charts

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #1453

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1453-AddGlossariesStackedBarCharts/?tab=tab-disbursements)

Changes proposed in this pull request:

- adds glossaries to stacked bar charts
- refactors stackedBarChart class into react d3 functional components
-

### CODE REVIEW

**Review by mcharg — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@jlouis-onrr I get an error message when I'm in explore data and scroll down to the charts. @mcharg are you getting the same?

**Comment by mcharg** [comment]
@Maroyafaied Yep.  It errored out while I was scrolling down.

**Review by Maroyafaied — APPROVED** [review]

**Review by mojobnichols — APPROVED** [review]
Noticed data is not synced up with capitalization.  I am sure this not an issue with this.

**Comment by mcharg** [comment]
@jlouis-onrr The query tool link on the nationwide disbursements card is overlapping the header below.
image

**Comment by mcharg** [comment]
@jlouis-onrr I'm not seeing any glossaries on units in Explore Data.
@jlouis-onrr The unit definitions don't have a home on Explore Data. We should come up with a good place to put them.

Maybe after this big instance on the detail card?
image

**Review by mcharg — APPROVED** [review]

**Comment by jlouis-onrr** [comment]
added #1517 to this PR

**Pull request merged**
