### PR TITLE
Change H1s to title case Native American pages

### PR DESCRIPTION
**Pull request by jennmalcolm**
Partial fix for #1203
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Fix-capitalization/how-revenue-works#how-are-natural-resources-on-native-american-land-governed)

Changes proposed in this pull request:

- Fix H1 capitalization on all How Revenue Works, Native American pages

### CODE REVIEW

**Comment by mcharg** [comment]
When I click on the onshore tab from the offshore oil and gas page it's giving me a 404 error.  It's fine in both the live site and dev, just broken in this PR. 
image

**Comment by mcharg** [comment]
Same thing when clicking the offshore tab from the onshore renewables page.

**Comment by mcharg** [comment]
The background images are also missing on the dive in pages.
Oil & gas:
image

Renewables:
image

**Comment by mcharg** [comment]
The H1s all look good.

**Comment by jennmalcolm** [comment]
That's strange @mcharg because I didn't touch those pages on this branch. I thought maybe I did something accidental, but the files changed don't reflect any changes to those pages. It's beyond me what's going on with that.  Maybe we can ask the developers at sync up.

**Comment by jennmalcolm** [comment]
@mcharg I see those issues in other previews too, such as #1204 , which hasn't been merged, and #1218, which has been merged, so I think it must be an issue with the preview branch. So, it seems like a good thing to address with the developers.

**Review by mcharg — APPROVED** [review]

**Pull request merged**
