### PR TITLE
Comparison trends homepage (NOT READY TO MERGE)

### LINKED ISSUE #1147: Build new revenue trends on the homepage
Design: https://v25akx.axshare.com/

# Revenue
- [x] Remove existing trends section

## Yearly
- [x] Add ability to select the breakout (source, revenue type, commodity)
- [x] Add graph for revenue type
- [x] Add graph for commodity
- [x] Add new comparison section to compare the selected year to the current FY so far
- [ ] Add ability to choose whether to compare to the current FY so far or the previous year (nice to have)

## Monthly
- [ ] Add current FY so far period
- [x] Add ability to select the breakout (source, revenue type, commodity)
- [x] Add graph for revenue type
- [x] Add graph for commodity
- [x] Add new comparison section to compare the selected year to the same month the previous year
- [ ] Add ability to choose whether to compare to the same month in the previous year or the previous month (nice to have)

# Disbursements
- [x] Remove existing trends section

## Yearly
- [x] Add ability to select the breakout (source, recipient)
- [x] Add graph for recipient
- [x] Add new comparison section to compare the selected year to the current FY so far
- [ ] Add ability to choose whether to compare to the current FY so far or the previous year (nice to have)

## Monthly
- [x] Add current FY so far period and graph
- [x] Add ability to select the breakout (source, recipient)
- [x] Add graph for recipient
- [x] Add new comparison section to compare the selected year to the same month the previous year
- [ ] Add ability to choose whether to compare to the same month in the previous year or the previous month (nice to have)

# Production
- [x] Add ability to select commodity
- [x] Split the 3 existing graphs into separate views based on commodity selected

## Yearly
- [x] Add new comparison section to compare the selected year to the current FY so far
- [ ] Add ability to choose whether to compare to the current FY so far or the previous year (nice to have)

## Monthly
- [ ] Add current FY so far period and graph
- [x] Add new comparison section to compare the selected year to the same month the previous year
- [ ] Add ability to choose whether to compare to the same month in the previous year or the previous month (nice to have)

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #1147

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1147-NewHomepageTrends/)

Changes proposed in this pull request:

- Add comparison trends for Revenue, Disbursements and Production
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr What about minerals on the commodity view?  Are those in with not tied to a commodity?
image

**Comment by mcharg** [comment]
@jlouis-onrr I'm thinking we might want to switch to the chart colors from explore data.  The blues are getting harder to distinguish the more items we have in the chart.  We may also want to keep the rows there when there's no data for a given year or month, so the swatches are still there to act as sort of a key for the other bars.

image

**Comment by mcharg** [comment]
@jlouis-onrr The new location for the location link looks good.  Is it possible to middle align the icons and links, so they're all in a row?
image

**Comment by mcharg** [comment]
We should standardize the headers across the two tables, so they match.  In this instance, I would go with FY 2019 and FY 2018.
image

This one I would make FY 2021 so far (Oct) and FY 2020 so far (Oct)
image


And we can drop the range below the change label:
image

Can you style the headers above the chart and the comparison section the same?  They look slightly different.
image

**Comment by mcharg** [comment]
@jlouis-onrr Can you right align the dollar amounts in the comparison table?
image

**Comment by mcharg** [comment]
@jlouis-onrr Looks like we're either not pulling the same months for FY21 and FY20 or the labels are off.
image

**Comment by mcharg** [comment]
Monthly revenue is showing 2018 in the table below the bars instead of 2020.  And the years below the chart are off.
image

**Comment by mcharg** [comment]
I don't think the monthly comparison is really a month to month comparison, since it's comparing the same month in different years.  Maybe it should still say year over year comparison?
image

**Comment by mcharg** [comment]
@jlouis-onrr Is it possible to range from the green to the darkest purple no matter how many items we have to allow for more contrast?  I thought the lightest color in the bars was not tied to a lease when I initially looked at this.
image

**Comment by mcharg** [comment]
@jlouis-onrr For disbursements, the colors in the bar aren't matching the colors in the swatches.
image

**Comment by mcharg** [comment]
@jlouis-onrr I clicked on September and then moused straight down to replicate the different months displaying.
image

**Comment by mcharg** [comment]
@jlouis-onrr Can you mark the 0 line as being 0?  We could also look at changing the top line and using something more like an traditional scale line - I know we used to have issues with people understanding the top line, so we aligned it right instead of left, but not sure if that fixed the problem.
image

**Comment by mcharg** [comment]
@jlouis-onrr It's looking good.  The only thing keeping me from updating the fact sheet prototype is the disbursments by recipient colors still don't match the key.
image

**Comment by jlouis-onrr** [comment]
@mcharg, I'm looking into why the colors in disbursements are not lining up and will look at adding the zero label for the zero line.

**Comment by mcharg** [comment]
@jlouis-onrr The 0 line seems to have reverted in your last commit.

**Comment by mcharg** [comment]
@jlouis-onrr It would be nice to have if you could get them to all start at green and end at dark purple, as well.

**Comment by mcharg** [comment]
@jlouis-onrr It looks like the key still isn't quite matching up on the monthly disbursement by recipient.  The first swatch on the key looks like the second color down on the bars and the negative one definitely doesn't match up.
image

**Comment by mcharg** [comment]
@jlouis-onrr The purple you have in the bars isn't the darkest.  Can you put in #C4D99B and #37253C as the end points and see if we get more differentiated colors?

**Comment by mcharg** [comment]
@jlouis-onrr Can you make it so it only shows the negative axis if the selected view has a negative number?  This is holding the place for if you select by recipient, but there are no negatives in the by source view.
image

**Comment by mcharg** [comment]
@jlouis The years below the months need to be adjusted to account for the new y axis.
image

**Comment by Maroyafaied** [comment]
@jlouis-onrr The yearly revenue and disbursement charts look like there's two lines on x axsis but it looks fine in production. 

image
image

**Comment by mcharg** [comment]
@jlouis-onrr Looking good.  The disbursements by recipient still isn't using the darkest purple.
image

**Comment by jlouis-onrr** [comment]
@mcharg, looks like the disbursements by recipient darkest purple issue is related to the historic preservation fund data issue.  I think we have a plan to create a new view that will stub out null data for the months that dont have data and that should resolve the missing items in the legend as well at not seeing the darkest color range.

**Comment by mcharg** [comment]
@jlouis-onrr What is the ordering scheme for the bars?  I know in the past we ordered them with the largest at the bottom.  It seems kind of arbitrary to me to have royalties in the middle with the smaller ones on both sides.

image

**Comment by mcharg** [comment]
Here's how I think they should be ordered.

Revenue by revenue type:
* Federal - not tied to a location
* Native American
* Federal offshore
* Federal onshore

Revenue by revenue type:
* Other revenues
* Inspection fees
* Civil penalties
* Rents
* Bonuses
* Royalties

Revenue by commodity:
* Not tied to a commodity
* Other commodities
* Coal
* Gas
* Oil

Disbursements by source
* Native American
* Federal offshore
* Federal onshore

Disbursements by recipient
* Other funds
* Historic Preservation Fund
* Land and Water Conservation Fund
* Native American tribes and individuals
* Reclamation Fund
* States and local governments
* U.S. Treasury

Production
* Native American
* Federal offshore - we can probably drop this for Coal now that the charts aren't visible at the same time.
* Federal onshore

**Comment by mcharg** [comment]
@jlouis-onrr The orange outline doesn't show up in both Edge and IE.
image

**Comment by mcharg** [comment]
Orange also doesn't show up on iPhone Safari.
image

**Comment by mcharg** [comment]
Comparison is also weird on mobile.  I have FY21 so far selected and it's comparing to FY14.  I'm wondering if we should just leave the comparison section off on smaller viewports.
image
image

**Comment by Maroyafaied** [comment]
@jlouis-onrr the comparison numbers are not aligned correctly for production. 
image

**Comment by mcharg** [comment]
The bars are also not matching the numbers.  If they were the dark purple would be smallest in both Maroya's screenshots.

**Comment by mcharg** [comment]
@jlouis-onrr The transparency on the non-selected bars doesn't work.  For example, the lighter version of the royalties color looks an awful lot like the bonus color in the key.
image

**Comment by mcharg** [comment]
And in this view the negative purple looks like the same shade as the purple right above the 0 line.
image

**Comment by mcharg** [comment]
@jlouis-onrr The colors look much more distinguishable.

**Comment by mcharg** [comment]
@jlouis-onrr The first time I view the homepage in any of the browsers, it's giving me this Graph QL error, but refreshing fixes it.
image

**Comment by mcharg** [comment]
The bolding works in all the non-Chrome browsers.

**Comment by mcharg** [comment]
@jlouis-onrr Mobile is still comparing against the wrong year.  I have FY21 so far selected and it's comparing against FY17.  There doesn't seem to be any pattern to which year it picks.  When I first got to the page it was comparing to FY18.
image

**Comment by shannonmcharg** [comment]
Checked on Safari on my new computer (I finally broke down and got a Mac) and the comparison is working right, so it's definitely a mobile issue and not a Safari issue.

**Comment by mcharg** [comment]
@jlouis-onrr It's comparing to the right year on my Android, so it might be an issue specific to iPhone.

**Comment by jlouis-onrr** [comment]
@mcharg, what iOS version is that on your iphone where you experienced the comparison issues?

**Comment by mcharg** [comment]
@jlouis-onrr iOS 14.4 on an iPhone SE.

**Comment by mcharg** [comment]
@jlouis-onrr I think I figured out what's happening.  It appears to be changing the selection back to FY21 so far any time I scroll up, but the comparison stays with what it was, so they get out of sync.

**Review by mcharg — APPROVED** [review]

**Review by Maroyafaied — APPROVED** [review]

**Review by lpgoldstein — APPROVED** [review]

**Comment by jennmalcolm** [comment]
When I click on a year and then scroll over a different year, the data changes (permanently). It doesn't go back to the year I clicked on until I click back on that year, but the year heading and the total seem to stay with the initial click. See example below. 
Correct numbers:
image

When I scroll elsewhere but do not click:
image


image

**Comment by jennmalcolm** [comment]
Also with the year so far comparisons (I don't know about others yet), the previous year's numbers and the % change are wrong. I've only looked at revenue so far. 
image

**Comment by Maroyafaied** [comment]
@jlouis-onrr @jennmalcolm It's happening for me as well but when I hover my mouse in between two years.

**Comment by Maroyafaied** [comment]
image

**Comment by Maroyafaied** [comment]
@jlouis-onrr looks like what you did fixed it. @jennmalcolm can you check if it's fixed for you?

**Comment by jennmalcolm** [comment]
The issue of the wrong year's data showing when you scrolled somewhere else seems to be fixed. The previous period so far numbers are still wrong for revenue. I'll check disbursements and production too. I haven't looked that those yet.

**Comment by jennmalcolm** [comment]
Production and disbursements look ok. I'm just seeing the data issue with the FY 2020 (Oct- Dec) so far comparison total numbers and percent change in the revenue section.

**Comment by mcharg** [comment]
@jlouis-onrr The 2021 is getting cut off in the monthly revenue view.
image

**Comment by mcharg** [comment]
@jlouis I don't think we need this comma.
image

**Comment by jennmalcolm** [comment]
In the production so far, it doesn't indicate the "so far" and that it's just Oct. 
image

**Comment by jennmalcolm** [comment]
Also, I thought we were going to do the "so far" on the calendar year too. Did we decide to just do it for FY?

image

**Comment by jennmalcolm** [comment]
This changes if I click away from it and then back onto CY20, but when I first load the page and select CY revenue, it always compares CY20 to CY20 
image

**Comment by Maroyafaied** [comment]
@jennmalcolm I don't believe we discussed doing "so far" for CY, I think we only decided to do it for FY.

**Comment by Maroyafaied** [comment]
> This changes if I click away from it and then back onto CY20, but when I first load the page and select CY revenue, it always compares CY20 to CY20
> image

@jennmalcolm That's not happening for me. Can someone else try to replicate this?

**Comment by mcharg** [comment]
@Maroyafaied @jennmalcolm It's happening for me.

**Comment by mcharg** [comment]
Looks like all the functionality bugs Jennifer found are fixed.

**Comment by Maroyafaied** [comment]
**Production Tab** 

Homepage
- [ ] Monthly bar charts (most recent 12 months, FY & CY)
- [ ] CY bar charts
- [ ] FY bar charts
- [ ] Check all commodities
- [ ] Check year over year comparison
- [ ] Check month over month comparison
- [ ] Source file links

**Revenue Tab** 	

Homepage 
- [ ] Monthly bar charts (most recent 12 months, FY & CY)
- [ ] CY bar charts
- [ ] FY bar charts
- [ ] Check Breakouts (Source & Revenue type, commodity)
- [ ] Check year over year comparison
- [ ] Check month over month comparison
- [ ] Source file links

**Disbursements Tab** 

Homepage	
- [ ] Monthly bar charts (most recent 12 months, FY & CY)
- [ ] CY bar charts
- [ ] FY bar charts
- [ ] Check Breakouts (Source & Recipient)
- [ ] Check year over year comparison
- [ ] Check month over month comparison
- [ ] Source file links

**Comment by Maroyafaied** [comment]
@jlouis-onrr For production monthly, when I select CY 20 it's pulling CY 19 instead. 
image

**Comment by jlouis-onrr** [comment]
@Maroyafaied, looking into the production issue...

**Comment by mcharg** [comment]
@jlouis-onrr The monthly view is sometimes comparing to 2018 instead of 2019. The numbers are also matching 2018, so it's not just the label.
image

**Comment by mcharg** [comment]
@jlouis-onrr The labels are wrong on the 2019 months in the FY monthly view.  The numbers are for 2019 and 2018, but it says 2020 and 2019.
image

**Comment by Maroyafaied** [comment]
@jlouis-onrr When I check revenue CY19 by commodity the numbers in the bar chart are correct, but when I select CY 20 the numbers are wrong for CY19 comparison. 
image
image

**Comment by mcharg** [comment]
I think the two comments above capture the issues with monthly revenue.

**Comment by mcharg** [comment]
@jlouis-onrr Seeing the same issues with FY monthly production as with revenue.

The issue @Maroyafaied found with production appears to be fixed.

**Comment by mcharg** [comment]
@jlouis-onrr Disbursements has a slightly different issue than the others with the FY monthly view.
image

**Comment by Maroyafaied** [comment]
@jlouis-onrr We don't have CY 20 production data so I'm not sure where this is being pulled from. 
image

**Comment by mcharg** [comment]
@jlouis-onrr The 2018 numbers in the revenue monthly FY comparison are incorrect.
image
image

**Comment by mcharg** [comment]
@jlouis-onrr The rest of the monthly revenue bugs appear to be fixed.

**Comment by mcharg** [comment]
@jlouis-onrr The 2018 comparison is also off for production.
image
image

**Comment by mcharg** [comment]
@jlouis-onrr It's only an issue in the FY monthly view.  The most recent 12 months view is correct.
image
image

**Comment by mcharg** [comment]
I'm not seeing any issues with disbursements monthly.

**Comment by jlouis-onrr** [comment]
@Maroyafaied, @mcharg, I just pushed out an update that should resolve the FY comparison data issues reported earlier today.  Can you verify?

**Comment by mcharg** [comment]
@jlouis-onrr Looks like it's fixed!

**Review by mcharg — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@jlouis-onrr for production this needs to CY 20 so far (Jan-Oct) and compared to CY19 so far (Jan-Oct)
image

**Comment by jennmalcolm** [comment]
@jlouis-onrr in calendar year so far, the 2020 comparison seems to be picking up more than January 2020. If you look at the monthly view the January total is correctly $903m, but here you've got $1.5b

image

**Review by lpgoldstein — APPROVED** [review]

**Comment by lpgoldstein** [comment]
I'm happy with production

**Comment by jlouis-onrr** [comment]
@Maroyafaied, @jennmalcolm, just pushed out updates that should address the issues brought up earlier.

**Review by Maroyafaied — APPROVED** [review]

**Review by jennmalcolm — APPROVED** [review]

**Pull request merged**
