### PR TITLE
74 add cy revenue

### LINKED ISSUE #74: Explore Data: Add CY revenue data
To allow the user to pick fiscal or calendar year.

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #74
[:sunglasses: PREVIEW](https://74-addcyrevenue.app.cloud.gov/explore/)

Changes proposed in this pull request:

User can now select between fiscal and calendar year.
All graphs should switch accordingly. 

NOTE I believe the year slider is changing significantly so it doesn't reflect the period (label says FY)   

-
-
-

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@mojobnichols the revenue over time trend line still displays fiscal year data when I switch to CY. 
image

**Comment by Maroyafaied** [comment]
@mojobnichols Also I think we should add the label "CY" on the map cards to be consistent. 
image

**Comment by mcharg** [comment]
Horizontal bar chart is full width instead of relative to total and displays FY label when CY selected.
image

**Comment by mcharg** [comment]
Top locations label has FY when CY is selected.
image

**Comment by mcharg** [comment]
It lets you pick Calendar Year for disbursements, even though there is no data.
image

**Comment by lpgoldstein** [comment]
@mojobnichols data looks good. The nationwide summary and top locations is still listed as fy though. I'm not sure if this data is supposed to change.

**Comment by mcharg** [comment]
@lpgoldstein All the data is supposed to change.

**Comment by mojobnichols** [comment]
Okay CY issue for those graphs was because it was using old deprecated component.    This is also why the nation wide graph wasnt' relative"

**Comment by mcharg** [comment]
Revenue looks good.  I think we should remove the ability to pick CY for disbursements and production before merging.

**Comment by jennmalcolm** [comment]
@mojobnichols the disbursements map isn't showing the data on this branch. 
image

**Comment by jennmalcolm** [comment]
I just checked dev, and the disbursements map isn't showing data in there either. I guess I can create a new issue. I didn't see one for this.

**Comment by jennmalcolm** [comment]
I see that there is a comment in the dev--> master PR on the disbursements issue, so Ill go ahead and merge this one.

**Pull request merged**
