### PR TITLE
Sticky Header

### LINKED ISSUE #1424: Make NRRD header sticky
Request from program manager

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #1424

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1424-StickyHeader/)

Changes proposed in this pull request:

- updates header to be sticky
- adds new component withStyles HOC to handle sticky header component and header components
-

### CODE REVIEW

**Comment by mcharg** [comment]
Here are a few things to fix.

- [ ] Sometimes the header doesn't shrink when scrolling in Chrome.
image

- [ ] The map doesn't have enough space with the new county treatment on mobile.
- [ ] "explore data" is also lower casing on mobile.
image

IE has some issues that we might want to look at.
- [ ] Explore data won't load.
image

- [ ] Header covers up content.
Homepage
image

Query data (can't access toolbar)
image

**Comment by mcharg** [comment]
@jlouis-onrr The map spacing looks better on my phone, but "explore data" in the tab is still lower casing.
image

**Comment by mcharg** [comment]
@jlouis-onrr IE got worse.  The IE banner is no longer displaying and the nav items don't show on the menu bar.  Menu bar is still covering content at the top of the page.  
image

**Comment by jlouis-onrr** [comment]
@mcharg, yeh, this is still a hot mess atm.  I needed to push some stuff out yesterday so that I could pull down on to my mac for some local network mobile testing.

**Review by mcharg — APPROVED** [review]

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
