### PR TITLE
Production card  and more explore updates

### LINKED ISSUE #437: Production bar chart is missing on nationwide and Native American cards

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #437, #480, #438, #333

[:sunglasses: PREVIEW](https://480-replaceproductionbarchartwithlinechart.app.cloud.gov/explore/)

Changes proposed in this pull request:

-  fix for top locations showing in Native American card
- replaces production bar chart with line charts
- fix for production bar chart not showing, updated query
- introduces css grid property for detail card alignment 
- introduces global data filter select inputs

### CODE REVIEW

**Comment by mojobnichols** [comment]
I would change title since line and data doesn't have anything to do with land category.

Ideally it would say Produciton of <commodiity> (<units_abbr>)

**Comment by mcharg** [comment]
@jlouis-onrr The commodity selection can't be multi-select for production because they're all in different units.

**Comment by mcharg** [comment]
@jlouis-onrr Nevermind, I thought I was looking at production, but it was still in revenue.

**Comment by mcharg** [comment]
@jlouis-onrr Can we relabel the line chart to "Production over time", since land category is no longer in the chart.
image

**Comment by mcharg** [comment]
@jlouis-onrr Top Locations isn't populating on the nationwide card.
image

**Comment by mcharg** [comment]
#333 isn't fixed in the query tool.

**Comment by mcharg** [comment]
It also doesn't make sense to have production by county on the nationwide and Native American cards.  Is that a quick fix or should I create a new issue for it? 
image

**Comment by mcharg** [comment]
Top nationwide locations is also not displaying below the cards.
image

**Comment by mojobnichols** [comment]
@mcharg  Let's leave this as separate issues because 1) 450 merged with 453 may remove this issue and 2) production by county is separate issue.  I'd like to merge this branch into dev and then into 453 so we can see updated data in one place.

**Comment by jlouis-onrr** [comment]
@mcharg, the title has been updated and the county content removed from Nationwide Federal and Native American cards.  @mojobnichols, i agree that 450 should resolve the top locations issue in this branch.

**Pull request merged**
