### PR TITLE
change blog link in footer

### LINKED ISSUE #885: Update footer link to blog
New blog address https://blog-nrrd.doi.gov/

### PR DESCRIPTION
**Pull request by jennmalcolm**
Fixes #885 

[:sunglasses: PREVIEW](https://blog-link.app.cloud.gov/)

Changes proposed in this pull request:

- updates blog link in footer
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@jennmalcolm We also need to merge dev on the blog to master to get the card sorting post.

**Comment by jennmalcolm** [comment]
Yes @mcharg do you want to do that for the blog site now? We can add it to what's new with our next release, which I think will be early next week.

**Comment by mcharg** [comment]
@jennmalcolm Yes, we can do it now. I don't know how to merge from dev to master.

**Comment by jennmalcolm** [comment]
Ok, I can get the PR set up @mcharg

**Pull request merged**
