### PR TITLE
954 unit testing mocks

### PR DESCRIPTION
**Pull request by master12**
Changes proposed in this pull request:

- Test libraries and mock examples
-
-

### CODE REVIEW

**Comment by jlouis-onrr** [comment]
@master12,  how should I test this one?

**Review by mojobnichols — CHANGES_REQUESTED** [review]
In my branch the tests only ran after I installed jest.   Is jest in the package.json file?   I would fix and commit but I wanted to run by you.   One thought is your jest installed globally and that is why it works for you and not from a fresh build.  I did start with npm install then npm run test-unit-tests

Once I installed they ran an passed - so other then the minor thing above no issues.

**Comment by mojobnichols** [comment]
Also you're lint tests failed.   I'm just glad I'm not the only one:-D!

**Comment by master12** [comment]
@mojobnichols I wil add jest to the package and fix lint issues

**Pull request merged**
