### PR TITLE
656 product column changes

### LINKED ISSUE #656: Query Tool production data changes to Product col and total rows
- Make the product column always show with multiple products
- Make total rows only show with 1 product selected. 
- Hide total rows with more than 1 product column

### PR DESCRIPTION
**Pull request by master12**
Fixes #656 

[:sunglasses: PREVIEW](https://656-product-column-changes.app.cloud.gov/query-data)

Changes proposed in this pull request:

- Product column shows as an additional column in Production
- Totals only show for a single Product in Production
- Additional columns are hidden if only 1 value is selected for the filter
- Additional columns don't appear int he group by and then group by lists
- Additional columns appear after the group by/then group by cols and before the year total cols

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 The preview link isn't working.

**Comment by mcharg** [comment]
@master12 The product column should be the first column and there should only be a group by if the user adds a second column.

**Comment by master12** [comment]
@mcharg Not sure that we want Product as a  first column but we can discuss at standup.

**Comment by mcharg** [comment]
@master12 I don't know why we would want anything other than product as the first column, since you need to know the product before comparing anything else to prevent comparing apples and oranges.

**Comment by master12** [comment]
@mcharg If we make it the first column then we could do subtotals just not totals

**Pull request merged**
