### PR TITLE
Pulled changes from 511 to new branch off of dev

### LINKED ISSUE #511: Offshore cards not working
This is related to #410 since it's an offshore issue. The offshore data is showing on the map for revenue, but the cards do not come up when an area is clicked or searched. Also the offshore options in the search box still show the planning areas. We should include only the offshore region.

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #511

[:sunglasses: PREVIEW](https://511b-OffshoreCards.app.cloud.gov/explore/)

Changes proposed in this pull request:
Fixed revenue offshore and commodity offshore.   See closed pull request: 
https://github.com/ONRR/nrrd/pull/563

-
-
-

### CODE REVIEW

**Comment by jennmalcolm** [comment]
I'm going to check more data, but it looks like there's an issue with some of the oil & gas numbers, causing the totals on the detailed cards to also be wrong. 
image

**Comment by jennmalcolm** [comment]
The issue seems to only be with the Gulf of Mexico and Pacific and only oil & gas. Offshore Alaska seems ok, but it is happening in multiple years. 
image

**Comment by jennmalcolm** [comment]
There are also issues with rents and other revenues (at least) on Pacific and Gulf of Mexico.

image

**Comment by mojobnichols** [comment]
The problem was the planning areas were either easements or right of way.  I was looking up region code by planning area for revenue

**Pull request merged**
