### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by lpgoldstein**
[Shannon's blog post](https://dev-blog-nrrd.app.cloud.gov/)

[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:
- Adds June 2022 disbursement data
- Adds June 2022 revenue data
- Adds April 2022 production data 

### Production Monthly

- [x] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Source File
- [x] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Land Type filter
- [x] One to three Products
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

### Revenue Monthly	

- [x] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout Commodity
 
Homepage - Source File
- [x] Check source file links are correct.
 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [x] One Land Type filter
   - [x] One Revenue Type filter
   - [x] One State (for Yearly data only)
   - [x] One Offshore Region
   - [x] One to three Commodities
   - [x] Clear All and change grouping
   - [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

### Disbursements Monthly

- [x] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [x] Check Treasury Fund column is deleted
- [x] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [x] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Breakout - Source 
- [x] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

### Other things to check
-Navigate between pages
- [x] Check several types of location profile page to ensure data and liquid templates are working as expected
- [x] Check links are working correctly
- [x] Check drop downs menu and validate they work 

Text
- [x] No misspelling
- [x] Correct spacing
- [x] Correct format
- [x] Accurate dates displayed

Maps
- [x] Appears on the page
- [x] Shaded correctly
- [x] Hover behavior works
- [x] county/offshore area maps: hover behavior and do detail tables open

Data 
- [x] Review 1 verified 5-10 sample lines of data--against source data and relevant charts (Assigned commodities)
- [ ] Review 2 verified 5-10 sample lines of data--against source data and relevant charts (Assigned commodities)

Bar Charts
- [x] Hover behavior is working 
- [x] Data displayed is correct
- [x] Chart changes if you select yearly or monthly

Check all browsers
- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

Check all devices
- [x] Dell Laptop
- [ ] Chromebook
- [x] Macbook
- [ ] iPad
- [x] iPhones
- [ ] Samsung phones

Check all responsive breakpoints
- [x] < 480 px (switches to one-column layout)
- [x] 600 px (changes bar chart layout from three column to accordion with one column)
- [x] 768 px (converts side navigation from separate column to the right to a select list)
- [x] > 768 (full site layout)

### CODE REVIEW

**Review by cthomasONRR — APPROVED** [review]
I reviewed: Production Data, Revenue Data, and the new blog post. All 3 look good :) Approved!

**Review by daniel-coleman-1 — APPROVED** [review]
I checked browsers but not IE, should we remove that from the checklist since IE is no longer in use?  I checked responsiveness, looks good in all of the browsers.  I also checked on my work Dell laptop and on my personal Macbook and iPhone, but I don't have an iPad, Samsung phone or chromebook to check.

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 good catch! Yes, will do that.

**Review by Baymatt — APPROVED** [review]
Reviewed Production, Revenue and Disbursement data. Looks good.

**Comment by mojobnichols** [comment]
Added changes to download generation that  would not affect website.   Verified it didn't affect website.

**Review by mojobnichols — APPROVED** [review]

**Pull request merged**
