### PR TITLE
Jan-22-Disbursements

### LINKED ISSUE #1932: Upload and Review December 2021 Disbursement data

### PR DESCRIPTION
**Pull request by cthomasONRR**
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Jan-22-Disbursements/)

Changes proposed in this pull request:
- December 2021 Disbursements
-
-

### CODE REVIEW

**Comment by cthomasONRR** [comment]
**Disbursements Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [ ] Check Treasury Fund column is deleted
- [ ] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [ ] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [ ] Breakout - Source 
- [ ] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Recipient
- [ ] One Source
- [ ] One State
- [ ] One to three Commodities if applicable
- [ ] Clear All and change grouping
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
I just checked December 2021 Monthly Disbursements, and the data looks good! I didn't see any errors, and the CY 2021 updated on the homepage: 
image

**Comment by Maroyafaied** [comment]
@cthomasONRR I'm confused, I'm in your branch but I don't see Dec 2021 data updated in the homepage for disbursements. but I see the file updated in the download page. 
image

**Comment by cthomasONRR** [comment]
@Maroyafaied @mojobnichols 

I just checked disbursements 20min ago, and Dec 2021 was in the homepage. I closed and reopened the preview link, and now it's not there! What's going on?!

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@Baymatt this is ready for you to review. Thanks

**Comment by cthomasONRR** [comment]
I also re-checked the data, and everything looks good.

**Comment by Maroyafaied** [comment]
@Baymatt I'm going to merge this to dev and include you to review all the data sets in the dev to master PR.

**Pull request merged**
