### PR TITLE
Explore Data Updated Toolbar

### LINKED ISSUE #70: Explore Data: Add ability to select the data type displayed on the map
Using a toggle or tab.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #70

[:sunglasses: PREVIEW](https://70-addabilitytoselectdatatype.app.cloud.gov/explore)

Changes proposed in this pull request:

- adds init setup of Data type, Map level, Offshore data, Period, and Commodity dropdown selections
- adds the MapSelectControl component for easier control of creating select dropdowns
- also taps into send dispatch to provider
- cleans up explore data directory
- updated styles for toolbar and year slider
- fyi, currently only the Map level and Offshore data are working, where as the others are just dispatching to the store provider

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr 

Disbursements
- The period will be fiscal year.

Production
- Commodity won't be able to be multi-select or have an "all" option, since they are in different units.

I like the blue on the year slider.  We'll see if users see it more in user interviews.

**Comment by jlouis-onrr** [comment]
@mcharg 
"Production
Commodity won't be able to be multi-select or have an "all" option, since they are in different units."
is this for only production or all datatypes?

**Comment by mcharg** [comment]
@jlouis-onrr Yes, just for production.  For revenue, it can be multi-select, since they all use dollars.

**Comment by jlouis-onrr** [comment]
> @jlouis-onrr Yes, just for production. For revenue, it can be multi-select, since they all use dollars.

@mcharg, After i posted that question.  I was able to figure it out via the prototypes.  Super helpful. 
You can see the updates with default values as well here: 
https://70-addabilitytoselectdatatype.app.cloud.gov/explore/

**Comment by jlouis-onrr** [comment]
@mcharg, @mojobnichols if you could approve of this PR I can get it merged into dev

**Pull request merged**
