### PR TITLE
603 consistent wording on cards

### LINKED ISSUE #603: Consistent wording on cards with no revenue/production/disbursements
A couple concerns on the production cards:

- The writing should span the width of the card.
- Oil (or other commodity) should not be capitalized, and we don't need the unit here.
- The wording makes it sound like oil was produced in 2003. I would change it to be more consistent with the revenue statement. In this case, it could say, "This location has no federal oil production." We could also be consistent with what disbursements is saying now and say "no production" instead.

For disbursements and revenue, we should be consistent either with a full sentence or not.

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #603, 331 

[:sunglasses: PREVIEW](https://603-ConsistentWordingOnCards.app.cloud.gov/explore/)

Changes proposed in this pull request:

Added consistent wording to summary and detail cards for Revenue.

Fixed issue 331 making cards reflect commodity selection [331 zenhub ](https://app.zenhub.com/workspaces/data-display-5464fa79c3cc8d7f4c384eaf/issues/onrr/nrrd/331)

Not fixed production or disbursemnt wording.   This was fixed in [PR](https://github.com/ONRR/nrrd/pull/706)
-
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@mojobnichols 
- [ ] County cards should indicate that the county hasn't had any production/revenue/disbursements rather than the state.
Summary card:
image
Detail card:
image

**Comment by mojobnichols** [comment]
I resolved conflicts, but the states with no data is corrected in the  PR https://github.com/ONRR/nrrd/pull/736.   The two thing this depends on is the bug fix to allow states without data to open.   And the states opening without zoom - makes it easier to open state or county cards.     I think the best options  are to 1) merge above PR and then merge this with dev and continue getting the wording right for counties.  Or 2) merge and close this and then I can pull new branch and correct the county issue.

**Comment by mojobnichols** [comment]
I don't think you need to write up I'll just correct here after merging with the other branches.

**Comment by jennmalcolm** [comment]
@mojobnichols can you look at conflicts please?

**Comment by mcharg** [comment]
@mojobnichols The revenue types are running into the revenue by county section.
image

**Comment by mcharg** [comment]
@mojobnichols The county card wording is still off when you don't have a commodity selected.
image

**Comment by mcharg** [comment]
Disbursements by source is looking good.

**Comment by mcharg** [comment]
@mojobnichols The circle and legend colors still aren't matching up.
image

**Comment by mojobnichols** [comment]
@mcharg   I think it didn't build because of routes and thats why colors were not working.

**Comment by mcharg** [comment]
@mojobnichols The fixes all look good.

Just noticed that Cherry County is trying to pin an image at the top of the detail card, but not all counties do.  Not sure if that's just counties with no data.
image

**Comment by jennmalcolm** [comment]
I am not doing thorough data checks since that will happen in #670, but it looks like the revenue over time line graph is showing the all commodities total rather than the selected commodity @mojobnichols. 
image

**Pull request merged**
