### PR TITLE
1347 refactor query tool

### LINKED ISSUE #1347: Refactor Group By and Breakout By logic in query tool

### PR DESCRIPTION
**Pull request by master12**
Fixes #1347 #1361 #1341 #99

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1347-refactor-query-tool/query-data/)

Changes proposed in this pull request:

- Added sparkline trend column
- Fixed Disbursements Monthly query
- Get default years from DB vs hard coded
- refactor group by and breakout by code

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 The trend lines aren't updating when I select a different item in column 1 and some values in column 1 are showing up blank.
image

**Comment by mcharg** [comment]
@master12 Many commodities are missing when I organize by commodity.
image

**Comment by mcharg** [comment]
@master12 It's also not grouping.
image

**Comment by mcharg** [comment]
@master12 Column 2 is also not updating the sparklines and it isn't smart (i.e. month shows up for fiscal year data).
image

**Comment by Maroyafaied** [comment]
@master12 I'm seeing the same issues as Shannon, it's not grouping and FY 2020 production is showing up as zero's. 
image

**Comment by Maroyafaied** [comment]
@master12 can you remove "month" as an option when adding the second column? 
image

**Comment by mcharg** [comment]
@master12 Month is also an option for column 1 in revenue fiscal year when it shouldn't be.
image

**Comment by mcharg** [comment]
I think everything except for the month thing is fixed.

**Comment by Maroyafaied** [comment]
@master12 could you fix the issue with months appearing in the second column?

**Comment by master12** [comment]
@Maroyafaied @mcharg fixed the Month showing up in the group by and breakout list. I also added commodity to the monthly disbursement query so it should return the correct data based on that filter

**Comment by Maroyafaied** [comment]
@master12 I still see the month showing up, it actually shows up in column 1 and 2.

**Review by Maroyafaied — APPROVED** [review]

**Review by mcharg — APPROVED** [review]

**Pull request merged**
