### PR TITLE
Add offshore areas from search input

### LINKED ISSUE #773: Can't add offshore areas from search
they appear but cannot be selected

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #773

[:sunglasses: PREVIEW](https://773-cantaddoffshoreareas.app.cloud.gov/explore/)

Changes proposed in this pull request:

- ability to add offshore areas from search input

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr Is it possible to make it so when you type the word "offshore" you get the offshore regions?  Right now, it displays nothing.
image

**Comment by jlouis-onrr** [comment]
@mcharg, I'll check it out and see why offshore and other strings are not being picked up

**Comment by mcharg** [comment]
@jlouis-onrr Can you fix the conflicts, so we can merge?  We're running out of PR slots.

**Comment by mcharg** [comment]
Created #827 for adding the ability to search strings.

**Comment by jlouis-onrr** [comment]
@mcharg, im seeing the ability to search by string, like "offshore".  That got added to this branch.

**Pull request merged**
