### PR TITLE
Add glossaries to Circle Charts

### LINKED ISSUE #1388: Glossary Term in D3 using React D3 Library

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #1388

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1388-D3GlossaryTerms/explore)

Changes proposed in this pull request:

- Refactors D3circleChart class into react functional component
- Adds new SVG react components (ChartTooltips, Circles, Circle, Rect, Label, and Translate)
- Adds new Legend component
- Adds GlossaryTerms compoment to handle glossary legend items

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr The query link is being pushed into the header below.
image

**Comment by mcharg** [comment]
@jlouis Same thing for revenue.  The query links are getting unaligned.
image

**Comment by mcharg** [comment]
Otherwise, it looks good.

**Comment by mcharg** [comment]
There's a stray $0 revenue type line on the Native American card.  Not sure if that's specific to this PR or a database issue.
image

**Comment by mcharg** [comment]
@jlouis-onrr It also looks like the chart colors aren't matching the legend for anything but Nationwide.

**Comment by jlouis-onrr** [comment]
> There's a stray $0 revenue type line on the Native American card. Not sure if that's specific to this PR or a database issue.
> image

@mcharg, looks like this might be a data issue as I see the same in dev:
https://dev-nrrd.app.cloud.gov/explore/?dataType=Revenue&location=NF%2CNM%2C35039%2CNA&mapLevel=County&offshoreRegions=false&period=Calendar%20Year&year=2019

gonna look into it further

**Comment by Maroyafaied** [comment]
@jlouis-onrr looks good but the query production by location link is gone. 
image

**Comment by mcharg** [comment]
@jlouis-onrr Getting a random green background circle on the Nevada disbursements card.
image

**Comment by mcharg** [comment]
@jlouis It's looping back to purple on the nationwide circle chart for disbursements.  If it's easier, we could move to using the same colors as the homepage charts on Explore Data.
image

**Comment by mcharg** [comment]
@jlouis Also getting the green background on nationwide revenue.
image

**Comment by jlouis-onrr** [comment]
@mcharg, how do recreate the green background on the first circle?  I'm trying to recreate it, but having no luck.

**Comment by mcharg** [comment]
@jlouis-onrr I'm not having luck recreating it either.  Seems to be kind of like the rogue blue circles where it shows up when it wants to.

**Comment by mcharg** [comment]
@jlouis-onrr Here Wyoming turned green on me, but it changed back right before I took the screenshot.
image

**Comment by mcharg** [comment]
@jlouis-onrr The first time I moused over Gulf of Mexico, it turned green, but then it changed back before I could get a screenshot.
image

**Comment by jlouis-onrr** [comment]
@mcharg, I think it might be related to the mouse over events as I'm seeing some weird behavior there.

**Review by mcharg — APPROVED** [review]

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@jlouis-onrr is this good to merge?

**Pull request merged**
