### PR TITLE
Fix Download Query Data

### LINKED ISSUE #678: Downloads not working right
With two columns, the download for both Excel and CSV doesn't show the correct second column. In this example, I queried revenue type and added a second column of state, but the download has revenue type with a second column of commodity. Also, this particular query gave me all zeros except for 2017, but I'm not experiencing that problem anymore, so hopefully that won't repeat 

This is in dev. Right now in production, the columns are the right columns but in reverse order in the download.

### PR DESCRIPTION
**Pull request by master12**
Fixes #678 

[:sunglasses: PREVIEW](https://678-fix-downloads.app.cloud.gov/query-data)

Changes proposed in this pull request:

- Download columns now will match what is selected
-
-

### CODE REVIEW

**Comment by lpgoldstein** [comment]
@master12 the download columns match in my first query but there is now no total line at the bottom. Not sure if that's important. image

**Comment by lpgoldstein** [comment]
@master12 It still doesn't seem right when you add another group by option. Land type column in this download is mixing federal onshore and offshore rather than listing one and then the other as in the query results 
image

**Comment by master12** [comment]
@lpgoldstein The script does not do grouping or total rows, its more of raw output. But I think we could add that but that would have to be an enhancement. So please make another ticket if you want that option.

**Comment by lpgoldstein** [comment]
@master12 Got it. I pulled down several different download options and the downloads matched the results in the query tool.

**Pull request merged**
