### PR TITLE
Create state pages for SEO

### LINKED ISSUE #1360: Create a state page for SEO
To help explain how money goes to the states and to increase SEO.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #1360

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1360-StatePagesSEO/explore/states/AK/)

Changes proposed in this pull request:

- adds state/offshore mdx pages with seo frontmatter
- Sample state page: https://nrrd-preview.app.cloud.gov/sites/1360-StatePagesSEO/explore/states/AK/
- Sample offshore page: https://nrrd-preview.app.cloud.gov/sites/1360-StatePagesSEO/explore/offshore-regions/pacific

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr Can you match up the explore and query links, so the same data sets are next to each other?
image

**Comment by mcharg** [comment]
Same thing for offshore and there's never any disbursements data for the region on Explore Data, so we can drop that link.
image

**Comment by mcharg** [comment]
@jlouis There's also updated copy for offshore.
This page provides information about energy and minerals produced in federal waters in the [Offshore region name].

The federal government manages the waters and submerged lands of the [Outer Continental Shelf](https://www.boem.gov/oil-gas-energy/leasing/outer-continental-shelf). The first three nautical miles offshore (generally) are in the states' jurisdiction. This means that most [offshore drilling](https://revenuedata.doi.gov/how-revenue-works/offshore-oil-gas) and [renewable energy generation](https://revenuedata.doi.gov/how-revenue-works/offshore-renewables/) takes place in federal waters.  

The Office of Natural Resources Revenue (ONRR) collects rent, royalty, and bonus payments from companies that lease the federal waters. Revenue from offshore production is disbursed to the states and counties that surround the offshore area.

**Comment by mcharg** [comment]
@jlouis-onrr On the filter for disbursements in the query tool, we should add GOMESA and 8(g).  I thought those were included in the Offshore option.

**Comment by mcharg** [comment]
@jlouis-onrr On the state page, the link to the query tool for disbursements isn't selecting the state.
image

**Comment by mcharg** [comment]
@jlouis Can you turn on the offshore regions on the map if the user clicks from the offshore page to Explore Data?

**Comment by mcharg** [comment]
@jlouis-onrr This doesn't work so well for states without data.  For Maine, when I click on the Explore Data links, it doesn't bring up the Maine card.  

This is what I get on the query tool:
image

Is there an easy way to handle these states?

**Review by mcharg — APPROVED** [review]

**Review by Maroyafaied — APPROVED** [review]
@jlouis-onrr it looks good, should I merge it now?

**Pull request merged**
