### PR TITLE
fixed bug with monthly disbursement rollup of native american

### LINKED ISSUE #1760: Change US TreasuryAI and Paris in disbursement data

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #1760

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1760-USTreasuryAI/)

Changes proposed in this pull request:

Fixed native american bug causing error on explore data page
-
-
-

### CODE REVIEW

**Review by mcharg — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@mojobnichols how come it's not showing GOMESA offshore or 8(g) as it does in the live site?

image

Live site
image

**Comment by Maroyafaied** [comment]
@mojobnichols Also I don't see Native American tribes and individuals category that's currently on the live site.

image

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein @mojobnichols 
I am reviewing the data, specifically checking the errors previously mentioned. From what I see, everything is fixed- I see the correct source breakdowns under each fund type, and the visualization data matches the downloaded excel.

This is a fix for another time, but it would be nice to see this 'disbursements over time' graph to be in log scale, so the Native American data doesn't look like a flat 0 line. 
image

**Comment by lpgoldstein** [comment]
@maroyafaied @mojobnichols @lpgoldstein  I checked for years 2016 and 2020 so far. I was able to get the page to load correctly several times and the data that I've checked is correct.

**Review by mcharg — APPROVED** [review]

**Review by cthomasONRR — APPROVED** [review]

**Review by Maroyafaied — APPROVED** [review]

**Review by lpgoldstein — APPROVED** [review]

**Pull request merged**
