### PR TITLE
change release version 6.0.1

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://release-changes-601.app.cloud.gov/explore/)

Changes proposed in this pull request:

- increment version 
- updated what's new section

### CODE REVIEW

**Comment by mcharg** [comment]
I'm getting a privacy error on the preview link.

**Comment by Maroyafaied** [comment]
@mojobnichols I'm not sure why it's giving a privacy error, it went through successfully through circleci .
image

**Comment by mcharg** [comment]
It won't let me view the site and I'm not on vpn.
image

**Comment by mcharg** [comment]
I get the same error on my personal computer.

**Comment by mcharg** [comment]
@mojobnichols Any ideas?

**Comment by Maroyafaied** [comment]
@mcharg I'm getting the same error, I don't know what I did wrong. I don't know it's because I put dashes on the branch name?

**Pull request merged**
