### PR TITLE
1016 pattern library

### LINKED ISSUE #1016: Build initial pattern libarary

### PR DESCRIPTION
**Pull request by master12**
Fixes #1016

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1016-pattern-library/patterns)

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 The build failed.

**Comment by master12** [comment]
@mcharg Ok it finally built might have to clear your cache

**Comment by mcharg** [comment]
@master12 

A few bugs:
* Clicking on visual styles doesn't work when you're on the components tab.
* I can't click on the color, typography, or iconography tabs.
*  It seems like some components are missing. For example, are the explore data cards not a component?  I also don't see tabs, links, or tables.  You were also going to show the horizontal version of the bar chart as a variant.

**Comment by mcharg** [comment]
@master12 Clearing my cache fixed the clickability problems.

**Comment by branic18** [comment]
My feedback:
- For the guidelines page in Visual Style make the headers white so that it's easier to skim/read
- For the menu tabs darken or lighten the blue on whatever page they're on, so they know where they are in the menu tab

**Comment by mcharg** [comment]
I created #1241 to address the tweaks @branic18 and I pointed out.

**Review by mcharg — APPROVED** [review]

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
