### PR TITLE
Adds cy native american production to download files 

### PR DESCRIPTION
**Pull request by lpgoldstein**
Fixes #<694>

[:sunglasses: PREVIEW](694cyproductiondataNA.app.cloud.gov/explore/)

[Web preview](https://694cyproductiondatana.app.cloud.gov/)

Changes proposed in this pull request:

- add csv and excel cy production download files with native american data from 2003-2019
- updates download pages to reflect addition of native american data to cy data
- adds borrow sand and gravel (tons) to product list on download page

### CODE REVIEW

**Comment by Maroyafaied** [comment]
https://694cyproductiondatana.app.cloud.gov/downloads/production/

**Comment by Maroyafaied** [comment]
@lpgoldstein should this be taken out on the main download page 
image

**Comment by lpgoldstein** [comment]
@Faied, Maroya<mailto:Maroya.Faied@onrr.gov> sure if we want to wait that's fine

________________________________

**Comment by jennmalcolm** [comment]
Why are we waiting  to remove the reference to no CY Native American data from the main downloads page? Also, could you please add a space here?  
image

**Comment by lpgoldstein** [comment]
@jennmalcolm I'll take care of that now.

**Comment by mojobnichols** [comment]
Data has been reloaded for Production CY

**Comment by jennmalcolm** [comment]
@lpgoldstein could you help me review the CY Native American production data in explore data?

**Comment by jennmalcolm** [comment]
@mojobnichols the data isn't working right in this branch. All production data is zeros. Also, some of the revenues and disbursements are as well. Also the disbursements map colors are gone again here.

image

image

image

**Comment by mojobnichols** [comment]
Merge dev into this branch to squash all bugs already squashed

**Pull request merged**
