### PR TITLE
updates oil and gas on download pages

### PR DESCRIPTION
**Pull request by lpgoldstein**
fixes fiscal year on revenue by month download page 
fixes any remaining oil and gas references to oil or gas 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/mdxfixes/)

-
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
Are we updating oil & gas on revenue by company?  That page still says oil & gas.

**Review by mcharg — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@lpgoldstein this needs to be changed in company be revenue . @mcharg when we came up with the label , were we thinking in the files we will have it as "Oil or Gas" or "Oil or Gas (pre-production)"? I think the term we use in the download page should match the files.

**Comment by mcharg** [comment]
Oil or gas (pre-production)

**Comment by Maroyafaied** [comment]
@mcharg @lpgoldstein So we should  add "(pre-production)" as well in the download pages.

**Comment by lpgoldstein** [comment]
@Maroyafaied @mcharg Yes it probably makes sense to change the label to pre-production

**Comment by Maroyafaied** [comment]
@lpgoldstein ok, can you make that change to include pre-production to the label. Thank you!

**Comment by lpgoldstein** [comment]
@Maroyafaied @mcharg ready to check again

**Review by mcharg — APPROVED** [review]

**Review by Maroyafaied — APPROVED** [review]
Looks good!

**Pull request merged**
