### PR TITLE
dev-->master

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- updated monthly revenue for June 2020
- [x] homepage charts
- [x] revenue trend charts

- updated monthly production for March 2020
- [x] homepage charts

- updated monthly disbursements for May 2020
- [x] homepage charts
- [x] disbursement trend charts

- updated CY 2019 Revenue by company download file
- Added a blog post from our intern discussing her journey working with our team.
- updated query tool for production to always have product column

- [x] check data on explore data page (note what you've checked.)
- [x] check data on query tool (note what you've checked.)

- [x] search works
- [x] state and offshore region are combined into a single group by option in query tool
- [x] check url parameters to the query tool work.
- [x] check download column order on query tool.

### CODE REVIEW

**Comment by mcharg** [comment]
Monthly production charts on the homepage are only going through Jan, not March.  And the headers on the tables below are all showing different months.
image

**Comment by mcharg** [comment]
Clicking on the disbursements tab on the homepage throws an error:
image

**Comment by mcharg** [comment]
Clicking on the link to the query tool for disbursements from explore data, brings up the disbursements data, but the data type drop-down says revenue.
image

**Comment by mcharg** [comment]
On production explore data, the intro sentence is repeated at the bottom of the page.

image

**Comment by mcharg** [comment]
Clicking on the link to the query tool for production from explore data, brings up the production data, but the data type drop-down says revenue.
image

**Comment by mcharg** [comment]
State/offshore region filter label is unreadable for disbursements.
image

**Comment by mcharg** [comment]
Disbursements is working now, but the trends say it goes through June instead of May.
image

**Comment by lpgoldstein** [comment]
detail revenue cards didn't finish loading 
image

**Comment by mcharg** [comment]
I'm getting the same error on the revenue cards.

**Comment by lpgoldstein** [comment]
I checked nationwide, native american, wyoming, and idaho, state and some county data for revenue for several years and they looked good for revenue

**Comment by mcharg** [comment]
Map isn't coloring in for disbursements.
image

**Comment by mcharg** [comment]
Production card when there's no data for a state is pulling in the top locations nationwide.
image

**Comment by mcharg** [comment]
Horizontal bar charts for revenue and disbursements are full width instead of being relative to the total.
image

**Comment by lpgoldstein** [comment]
disbursements trend % change is off on homepage. I think it's probably pulling fy19-june data and comparing it with fy20-may because the amounts are correct. 
image

**Comment by mcharg** [comment]
Still to be fixed.

- [ ] On production explore data, the intro sentence is repeated at the bottom of the page. @mojobnichols I think you said you had a fix for this.

image

- [ ] Disbursements is working now, but the trends say it goes through June instead of May. @jlouis-onrr I think you said on Friday you were going to work on this one.
image

- [ ] Map isn't coloring in for disbursements. @mojobnichols 
image

- [ ] Disbursements horizontal bar charts aren't relative to each other.  This was fixed for revenue, but not disbursements. @mojobnichols 
image

- [ ] disbursements trend % change is off on homepage. I think it's probably pulling fy19-june data and comparing it with fy20-may because the amounts are correct. @jlouis-onrr Can you look at this with the other disbursements trends one?
image

**Comment by mcharg** [comment]
Search and the combination of state/offshore region group by look good.

**Comment by mcharg** [comment]
This is looking good.  Pending data checks, the one thing that's still an issue here is the production intro repeating, which we were hoping to pull in from Jerome's PR, but that still has bugs and conflicts.

**Comment by lpgoldstein** [comment]
disbursements cards aren't loading properly 
image

**Comment by mcharg** [comment]
New list of bugs from the latest merge.

- [ ] Line charts (all three) are broken.
The purple line is Gulf of Mexico.
And nationwide isn't big enough on the chart.
And one of the Nevadas is a county.
Revenue:
image
Production:
image
Disbursements:
image

- [ ] Top locations is now showing the nationwide breakdown on the state card for production.
image

- [ ] The cards aren't refreshing when switching to disbursements.  They're still showing the production numbers.
image

- [ ] Random "blah" on the disbursements page.
image

**Comment by lpgoldstein** [comment]
- [ ] getting an error message when I try to switch commodities in fy production

**Comment by mcharg** [comment]
@jlouis-onrr Revenue line chart is fixed, but production is still broken and getting a something went wrong error when I try to get to disbursements.

**Comment by mcharg** [comment]
@jlouis-onrr The production line chart is still off.  Gulf of Mexico is higher than Nationwide.
image

**Comment by mcharg** [comment]
@jlouis-onrr Disbursements summary cards are still showing production numbers when you switch from production to disbursements.
image

**Comment by mcharg** [comment]
@jlouis-onrr 
- [ ] Disbursements by recipient and source are missing from all the detail cards except the state card.

image

**Comment by mcharg** [comment]
@jlouis-onrr 
- [ ] The disbursements line chart is looking good, except it's putting in $0 for the county when the card shows a value.
image

image

**Comment by mcharg** [comment]
New list.

- [ ] Disbursements line chart is still off for county.
image
image

**Comment by mcharg** [comment]
- [ ] Cameron Parish, LA is also 0ing out after 2016 on revenue even though there is an amount for FY19.
image

**Comment by mcharg** [comment]
- [ ] Same on production.
image

**Comment by jlouis-onrr** [comment]
@mcharg, looks like this bug with linechart county missing data has been around for some time.  Its currently happening in beta.  Maybe we could create a new issue for this?

**Comment by mcharg** [comment]
@jlouis-onrr I'm okay with that if @jennmalcolm is.

**Comment by mcharg** [comment]
Created #703 for the line chart issue.

**Comment by jennmalcolm** [comment]
Ok, that works. @lpgoldstein can you and I do some data checks of dev now and see if we're ready to approve? How do you want to split it up?

**Comment by lpgoldstein** [comment]
@jennmalcolm I can start with disbursements since it's the easiest to check. Then production if you want to start with revenue.

**Comment by jennmalcolm** [comment]
Ok, I will work on revenue on the home page, explore data, and the query tool @lpgoldstein.

**Comment by lpgoldstein** [comment]
- [ ] query tool has LWCF twice because of the capitalization in GOMESA 
image

**Comment by jennmalcolm** [comment]
@lpgoldstein since there are issues to address those, I think they shouldn't hold up release.

**Comment by lpgoldstein** [comment]
@jennmalcolm moving onto production checks. Disbursements looks good

**Comment by jennmalcolm** [comment]
@mojobnichols I found the other category on Native American detail card is off for 2019. I haven't checked other years yet. 
image

**Comment by lpgoldstein** [comment]
@jlouis-onrr Production over time chart isn't changing commodity. The locations are changing when selected but the chart is just showing oil. I tried choosing several states, counties and commodities. 
image

**Comment by mcharg** [comment]
@jlouis-onrr The line chart is reflecting the commodity in beta, so the issue Lindsay brought up above is new in this build.

**Comment by jennmalcolm** [comment]
Also noted in #667, but the production top locations aren't right yet.

image

**Comment by jennmalcolm** [comment]
Two more issues: 

1. The spark lines on revenue top commodities don't reflect the selected year.
image

2.  Going to disbursements or production data does not keep the selected period (CY if selected and year). It always goes back to FY 2019. Going to revenue does keep the selection from the other data types. 

I guess these are not deal breakers for me on release, but they are correct in beta right now so I would like to see if they're quickly fixable @mojobnichols and @jlouis-onrr.

**Pull request merged**
