### PR TITLE
189 nationwide production

### LINKED ISSUE #189: Explore data: Build nationwide production summary
Design TBD.

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #189 

[:sunglasses: PREVIEW](https://189-nationwideproduction.app.cloud.gov/explore/)

Changes proposed in this pull request:
Add top locations chart 
Issues:

- [ ] State and county name is abbrev
- [ ] Offshore data needs to be added to view

-
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@mojobnichols Can you add "bbl" to the numbers in the table.

**Comment by jennmalcolm** [comment]
The units on the chart and the table need to change depending on the commodity. E.g., coal should be tons.

**Comment by lpgoldstein** [comment]
County name instead of FIPS code in table?

**Comment by mcharg** [comment]
We should add the name of the selected commodity to the label above the trendlines to make it clear, it's only showing production for one commodity.
image

**Comment by mcharg** [comment]
Maybe we should put the name of the selected commodity in the Production page header to make it super clear that everything below is only for that commodity. 
image

**Comment by mojobnichols** [comment]
I agree but right now oil and units are combined in product and commodity is even worse with  Oil Prod Vol... so I have some database work.. but that works well because we need to get up to date with data on new site.


Also I merged the #190 progress here.   I'm hoping some of the styling issues goes away when Jeromes branch merges with me.   So I think the sort of it is that its a rough draft at the moment.  I would spend a lot of time on details like year labels being to squished etc.

**Comment by jennmalcolm** [comment]
@Maroyafaied can you review the data?

**Comment by Maroyafaied** [comment]
@jennmalcolm yes, I'll check now

**Comment by Maroyafaied** [comment]
The numbers are slightly different but could be a rounding thing. 
image
image

**Comment by jennmalcolm** [comment]
also included detailed cards for production

**Pull request merged**
