### PR TITLE
Mobile line chart updates

### LINKED ISSUE #690: Text cutoff on production line graph axis - Also, should axis be smarter?
Looks like its going out to 3 decimals in cases of small numbers, and it's being cut off.

While this probably won't help with the overlapping text, I don't see why we would have numbers like these in the millions. That seems confusing.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #690, #818, #819, #808

[:sunglasses: PREVIEW](https://380-linechartmobile.app.cloud.gov/explore/)

Changes proposed in this pull request:

- update production line chart axis labels and make smarter
- homepage toogle updates, selected toggle uses default link blue instead of gray in mobile
- update breakpoints for location links
- update production location circle chart labels

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr No route.

**Comment by mcharg** [comment]
@jlouis-onrr The preview link was missing the branch name.

**Comment by mcharg** [comment]
@jlouis-onrr The disbursements by location link is no longer splitting, but it's now doing it for production.
image

**Comment by mcharg** [comment]
@jlouis-onrr Capitalization is off on the revenue circle charts on the detail cards.
image
image

**Comment by mcharg** [comment]
@jlouis-onrr Capitalization is also off for the disbursements circle chart.
image

**Review by mcharg — APPROVED** [review]

**Review by jennmalcolm — APPROVED** [review]

**Pull request merged**
