### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- Update fixes to query tool
- Blog post about Q/A process
- Remove arrows and % from trends
- Added September and October to revenue monthly
 Check Homepage
- [x]  Revenue trends line chart
- [x]  CY bar charts
- [x]  FY bar charts
- [x]  Monthly bar charts
- [x]  Source links
Check Download Page
- [x] xls and csv files updated with correct dates and file size

- Added September and October to disbursement monthly
Check Homepage
- [x] disbursement trends line charts
- [x]  monthly bar charts
- [x]  FY bar charts
- [x]  Source file links
Check Download
- [x] xls and csv files updated with correct dates and file size

- Added FY 20 to disbursement yearly
Check Explore data 
- [x] Switch between state and county
- [x]  Fiscal Year Period
- [x]  Add Nationwide federal card
- [x]  Add Native American Card
- [x]  Select different years
- [x]  Data displaying correct FY
- [x]  Summary Cards: correct state title, correct county & state title, trendline, accurate year, top recipient data
- [x]  Nationwide Federal Card: % of federal land, total disbursements for specified year, trendline, accurate year, disbursement by recipient data
- [x]  Detailed state cards: % of federal land, total disbursements for specified year, correct state title, trendline, total disbursement for specified year, disbursement by recipient data
- [x]  Detailed county cards: correct county & state title, total disbursement for specified year, trendline, accurate year
- [x]  Native American card: total disbursement for specified year, trendline, accurate year
- [x]  Check cards for states with no data
- [x]  Disbursements over time trend line data
- [x]  Nationwide disbursement summary bar chart data
- [x]  Top Nationwide recipients data
Check Query Data
- [x]  Recipient Filter
- [x]  Source Filter
- [x]  State/offshore region filter
- [x]  Grouping
- [x]  Download matches selected data

### CODE REVIEW

**Comment by mcharg** [comment]
The disbursements sparklines are starting at FY19. 
image

**Comment by mcharg** [comment]
And the disbursements bar chart isn't building. 
image

**Comment by mcharg** [comment]
On Explore Data, disbursements is defaulting to 2019, but it should default to 2020, since that is the most recent year available.
image

**Comment by mcharg** [comment]
In the query tool, the slider is showing 2020, but the data doesn't display when it's selected.  It should show 2016-2020 by default.
image

**Comment by mcharg** [comment]
I'm seeing a bunch of white space below the footer on the homepage and Query Data page.  Explore Data, Download Data, and How Revenue Works are fine.
image

**Review by mcharg — APPROVED** [review]

**Comment by mcharg** [comment]
The query tool changes look good.

**Review by master12 — APPROVED** [review]

**Comment by jennmalcolm** [comment]
I noticed that the first column in the query tool is still labeled "group by" under production data while it's been changed to "column 1" under all the other data sets. @master12 can you change that under production so it's consistent? 

image

**Review by jennmalcolm — APPROVED** [review]

**Review by lpgoldstein — APPROVED** [review]

**Comment by mcharg** [comment]
@mojobnichols I just noticed it says the trends for both revenue and disbursements include data through October 2021, but it's actually October 2020.
image

**Pull request merged**
