### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- [Blog post about Tree Testing](https://dev-blog-nrrd.app.cloud.gov/treetest/)

- Added monthly production & disbursement data to query tool

- Added FY 20 to revenue annually files
Explore data filters 
- [x] Switch between state and county 
- [ ] Show offshore 
- [x] Choose different commodities 
- [x] Switch between FY and CY 
- [x] Add Nationwide federal card 
- [x] Add Native American Card 
- [x] Explore data accuracy 
- [x] Select different commodities  
- [x] Select different years, correct FY or CY displaying 
- [x] Summary Cards: correct state title, correct county & state title, trendline, accurate year, commodities data, total # of commodities 
- [x] Nationwide Federal Card:  % of federal land, total revenue for specified year,  trendline, accurate year, commodities data, revenue type data 
- [x] Detailed state cards: % of federal land, total revenue for specified year, correct state title, trendline, total revenue for specified year, county map 
- [x] Detailed county cards: correct county & state title, total revenue for specified year, trendline, accurate year, commodities data, revenue type data 
- [x] Native American card: total revenue for specified year, trendline, accurate year, commodities data, revenue type data 
- [x] Offshore card: total revenue for specified year, trendline, accurate year, commodities data, revenue type data 
- [x] Check cards for states with no data 
- [x] Revenue over time trend line data 
- [x] Nationwide revenue summary bar chart data 
- [x] Top Nationwide locations data 
Query Data 
- [x] Land type filter 
- [x] Revenue type filter 
- [x] State/Offshore region filter 
- [x] Commodity filter 
- [x] Grouping 
- [x] Change between fiscal and calendar year and change years 
- [x] Download matches selected data  

- Added November 2020 to revenue monthly
Homepage 
- [x] Revenue trends line chart 
- [x] CY bar charts 
- [x] FY bar charts 
- [x] Monthly bar charts 
- [x] Source links 
Download Page 
- [x] xls and csv files updated with correct dates and file size
- Added disbursement monthly data to query tool 
- [x] Recipient Filter 
- [x] Source Filter 
- [x] State/offshore region filter 
- [x] Grouping 
- [x] Download matches selected data 

 Download Page 
- [ ] xls and csv files updated with correct dates and file size

- Added August 2020 to production monthly
Homepage
- [x] Monthly bar charts
- [x] CY bar charts
- [x] FY bar charts
- [x] Source file links
Query Data 
- [x] Land type filter 
- [x] Commodity filter 
- [x] Grouping 
- [x] Change between fiscal and calendar year and change years 
- [x] Download matches selected data 
Download
- [x] xls and csv files updated with correct dates and file size

- Enhanced zooming features on explore data map (lazy loading)

### CODE REVIEW

**Review by jennmalcolm — APPROVED** [review]
I only reviewed monthly data since the FY 2020 revenue data isn't in there yet.

**Comment by jennmalcolm** [comment]
There seems to be a problem with the query tool monthly data. It's not showing up by month. 
image

**Comment by mcharg** [comment]
I can't get to Explore Data in IE.  I get this error.  I got the same error the first two times I tried on Safari on my phone, but now it's working.
image

**Comment by mcharg** [comment]
I reviewed functionality in Chrome, IE, Firefox, Edge, iPhone Safari, and Android Chrome and the only issue is the IE issue noted above.  I think we need to fix that because you can't even open the page.

**Comment by Maroyafaied** [comment]
@mojobnichols the offshore in the map doesn't have any color 
image

**Review by mcharg — APPROVED** [review]

**Review by lpgoldstein — APPROVED** [review]

**Review by master12 — APPROVED** [review]

**Pull request merged**
