### PR TITLE
Updated Content - Federal Reforms Page

### LINKED ISSUE #1264: Review federal reforms page
Is this page within our vision and something we should continue to maintain?

If so, we need to research other reforms or updates that we should add to the page.

Currently we're at grade 14, which we should work on.

### PR DESCRIPTION
**Pull request by daniel-coleman-1**
Fixes #1264

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Content-Structure/how-revenue-works/federal-reforms/)

Changes proposed in this pull request:

Simplified text to lower reading level

-
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@daniel-coleman-1 When I put the whole page into Hemingway, it's still at grade 14.

**Comment by Maroyafaied** [comment]
@mcharg I get grade 12.

**Comment by mcharg** [comment]
@Maroyafaied I'm getting 12 now.  The content was different when I was getting 14.  Maybe it hadn't finished building.

**Comment by mcharg** [comment]
@daniel-coleman-1 This A should be lowercase.  Only H1s use title case for the NRRD site.
image

**Comment by mcharg** [comment]
@daniel-coleman-1 Can you make the OIG and GAO headings H3, so they nest under Oversight organizations?  Also, not sure we need "reports" in those titles. Also, we should be consistent with introducing acronyms.  We're defining them both under Oversight Organizations, but then redefine for OIG in the following paragraph, but use GAO without defining in that paragraph.
image

**Comment by mcharg** [comment]
@daniel-coleman-1 Is Dodd Frank also an example of reform in action?  If so, should we make that a heading to nest both that and Deepwater Horizon under?

**Comment by mcharg** [comment]
@daniel-coleman-1 Add a `<br>` tag here.
image

**Comment by mcharg** [comment]
@daniel-coleman-1 This sentence doesn't quite make sense.  I think it should just describe what BOEM does. 
image

**Comment by mcharg** [comment]
@daniel-coleman-1 I'm getting a 404 when I click on the GAO reports link.  @Maroyafaied Do we need to find a replacement for this link or can we remove it?
image

**Comment by mcharg** [comment]
Should we link out to BSEE and ONRR.gov, since we're linking out to BOEM?
image

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Please address @mcharg comments above. Also , you can remove the GAO oil and gas reports link, I couldn't find a working link for it. I can try to help with spacing the paragraphs if you'd like?

**Comment by Maroyafaied** [comment]
@mcharg did you review this page as well?

**Comment by mcharg** [comment]
@Maroyafaied I reviewed federal reforms, but not federal laws.

**Comment by mcharg** [comment]
Federal laws:

- [ ] Federal Oil and Gas Royalty Management Act (FOGRMA) of 1982 is linking to a doc we are archiving on onrr.gov, so should be replaced with this link: https://uscode.house.gov/view.xhtml?path=/prelim@title30/chapter29&edition=prelim
- [ ] Federal Oil and Gas Royalty Simplification and Fairness Act (RSFA) of 1996 - The regulations team told us to remove this link on onrr.gov because it's included in the FOGRMA link above.  We should also remove here.

Make the following changes to get it down to reduce reading level and remove passive voice.
- [ ] Intro paragraph: There are many laws that govern natural resource extraction on federal lands.
- [ ] Fiscal regime intro: The laws in this section provide the backbone of the fiscal regime for the extractive industries.
- [ ] General Mining Law description: Provides the right to transfer federal lands and natural resources to private ownership. This right is a mineral patent. Since October 1, 1994, Congress has imposed a budget moratorium on any new mineral patent applications. 
- [ ] Leasing of Allotted Lands for Mining Purposes Act of 1909 description: Allows leasing of lands allotted to Indians for mining purposes for up to ten years as determined by the Secretary of the Interior. Excludes Indian lands allotted to members of the Five Civilized Tribes and Osage.
- [ ] Indian Mineral Leasing Act of 1938 description: Opens unallotted lands within any Indian reservation for leasing for mining purposes. This is by authority of the tribal council and approval of the Secretary of the Interior.
- [ ] Mineral Leasing Act for Acquired Lands of 1947 description: Extends the Mineral Leasing Act of 1920. Extends authority of the Secretary of the Interior to govern mineral leasing on federal acquired lands.
- [ ] Mineral Materials Act of 1947 description: Also known as the Common Varieties Act. Regulates the sale and permitting of the most common hardrock minerals in place of the General Mining Law of 1872.
- [ ] Submerged Lands Act of 1953description: Recognizes states’ rights to the submerged navigable lands within their boundaries. These include things like lakes and rivers. Also recognizes states' rights to the marine waters within three geographical miles from the coastline.
- [ ] Mining and Minerals Policy Act of 1970 description: Amends the Mining Act of 1920. Establishes the national interest to develop a mining industry. Also addresses adverse environmental impacts.
- [ ] Federal Coal Leasing Amendments Act (FCLAA) of 1976 description: Amends Section 2 of the Mineral Leasing Act of 1920. Requires competitive leasing for all public lands available for coal leasing. Allows the government to only accept lease bids equal to or greater than fair market value. Consolidates leasing into logical mining units. Requires lease holders to operate continually and other measures.
- [ ] Surface Mining Control and Reclamation Act (SMCRA) of 1977 description: Creates the Office of Surface Mining, Reclamation, and Enforcement (OSMRE). The program balances the need for domestic coal production while protecting the environment. Requires coal mine owners to post bonds as insurance for reclaiming the land after current mining operations. They are also required to pay into the Abandoned Mine Reclamation Fund, a fund intended to address mines abandoned before 1977.
- [ ] Federal Oil and Gas Royalty Management Act (FOGRMA) of 1982 description: Grants the Secretary of the Interior authority to manage and collect oil and gas royalties from leases on federal and Indian lands.
- [ ] Federal Onshore Oil and Gas Leasing Reform Act (FOOGLRA) of 1987 description: Amendment to the Mineral Leasing Act of 1920. Gives the US Forest Service the authority to offer leases for oil and gas on National Forest System lands. They must meet environmental and other land-use regulations. BLM administers most leasing on these lands.
- [ ] Energy Policy Act (EPAct) of 2005 description: Addresses energy production in the United States. This includes the production, transportation, and transmission of energy on the Outer Continental Shelf from sources other than oil and gas (e.g., wind energy). Includes incentives for oil and gas development and provisions to access oil and gas resources on federal lands.
- [ ] Clean Air Act (CAA) of 1970 description: Outlines steps to decrease air pollution. Applies to federal agencies, state and local governments, and industry. Oil and gas wells are exempt from legal aggregation. This means the emissions from small sites that are connected, in close proximity, or under shared ownership, are added together. They are regulated as “stationary sources” if they emit or could emit 100 tons per year of a pollutant.
- [ ] Comprehensive Environmental Response, Compensation, and Liability Act (CERCLA) of 1980 description: Provides a federal ‘superfund’ to clean up uncontrolled or abandoned hazardous-waste sites. Also covers clean up from accidents, spills, and other emergency releases of pollutants and contaminants into the environment. Gives EPA the power to seek out parties responsible for any release and assure their cooperation in the cleanup.
- [ ] Regulations section intro: Federal agencies implement laws by developing and enforcing regulations. The regulations below relate to natural resource extraction on federal and Indian lands.

**Comment by daniel-coleman-1** [comment]
> Federal laws:
> 
> * [ ]  Federal Oil and Gas Royalty Management Act (FOGRMA) of 1982 is linking to a doc we are archiving on onrr.gov, so should be replaced with this link: https://uscode.house.gov/view.xhtml?path=/prelim@title30/chapter29&edition=prelim
> * [ ]  Federal Oil and Gas Royalty Simplification and Fairness Act (RSFA) of 1996 - The regulations team told us to remove this link on onrr.gov because it's included in the FOGRMA link above.  We should also remove here.
> 
> Make the following changes to reduce reading level and remove passive voice.
> 
> * [ ]  Intro paragraph: There are many laws that govern natural resource extraction on federal lands.
> * [ ]  Fiscal regime intro: The laws in this section provide the backbone of the fiscal regime for the extractive industries.
> * [ ]  General Mining Law description: Provides the right to transfer federal lands and natural resources to private ownership. This right is a mineral patent. Since October 1, 1994, Congress has imposed a budget moratorium on any new mineral patent applications.
> * [ ]  Leasing of Allotted Lands for Mining Purposes Act of 1909 description: Allows leasing of lands allotted to Indians for mining purposes for up to ten years as determined by the Secretary of the Interior. Excludes Indian lands allotted to members of the Five Civilized Tribes and Osage.
> * [ ]  Indian Mineral Leasing Act of 1938 description: Opens unallotted lands within any Indian reservation for leasing for mining purposes. This is by authority of the tribal council and approval of the Secretary of the Interior.
> * [ ]  Mineral Leasing Act for Acquired Lands of 1947 description: Extends the Mineral Leasing Act of 1920. Extends authority of the Secretary of the Interior to govern mineral leasing on federal acquired lands.
> * [ ]  Mineral Materials Act of 1947 description: Also known as the Common Varieties Act. Regulates the sale and permitting of the most common hardrock minerals in place of the General Mining Law of 1872.
> * [ ]  Submerged Lands Act of 1953description: Recognizes states’ rights to the submerged navigable lands within their boundaries. These include things like lakes and rivers. Also recognizes states' rights to the marine waters within three geographical miles from the coastline.
> * [ ]  Mining and Minerals Policy Act of 1970 description: Amends the Mining Act of 1920. Establishes the national interest to develop a mining industry. Also addresses adverse environmental impacts.
> * [ ]  Federal Coal Leasing Amendments Act (FCLAA) of 1976 description: Amends Section 2 of the Mineral Leasing Act of 1920. Requires competitive leasing for all public lands available for coal leasing. Allows the government to only accept lease bids equal to or greater than fair market value. Consolidates leasing into logical mining units. Requires lease holders to operate continually and other measures.
> * [ ]  Surface Mining Control and Reclamation Act (SMCRA) of 1977 description: Creates the Office of Surface Mining, Reclamation, and Enforcement (OSMRE). The program balances the need for domestic coal production while protecting the environment. Requires coal mine owners to post bonds as insurance for reclaiming the land after current mining operations. They are also required to pay into the Abandoned Mine Reclamation Fund, a fund intended to address mines abandoned before 1977.
> * [ ]  Federal Oil and Gas Royalty Management Act (FOGRMA) of 1982 description: Grants the Secretary of the Interior authority to manage and collect oil and gas royalties from leases on federal and Indian lands.
> * [ ]  Federal Onshore Oil and Gas Leasing Reform Act (FOOGLRA) of 1987 description: Amendment to the Mineral Leasing Act of 1920. Gives the US Forest Service the authority to offer leases for oil and gas on National Forest System lands. They must meet environmental and other land-use regulations. BLM administers most leasing on these lands.
> * [ ]  Energy Policy Act (EPAct) of 2005 description: Addresses energy production in the United States. This includes the production, transportation, and transmission of energy on the Outer Continental Shelf from sources other than oil and gas (e.g., wind energy). Includes incentives for oil and gas development and provisions to access oil and gas resources on federal lands.
> * [ ]  Clean Air Act (CAA) of 1970 description: Outlines steps to decrease air pollution. Applies to federal agencies, state and local governments, and industry. Oil and gas wells are exempt from legal aggregation. This means the emissions from small sites that are connected, in close proximity, or under shared ownership, are added together. They are regulated as “stationary sources” if they emit or could emit 100 tons per year of a pollutant.
> * [ ]  Comprehensive Environmental Response, Compensation, and Liability Act (CERCLA) of 1980 description: Provides a federal ‘superfund’ to clean up uncontrolled or abandoned hazardous-waste sites. Also covers clean up from accidents, spills, and other emergency releases of pollutants and contaminants into the environment. Gives EPA the power to seek out parties responsible for any release and assure their cooperation in the cleanup.
> * [ ]  Regulations section intro: Federal agencies implement laws by developing and enforcing regulations. The regulations below relate to natural resource extraction on federal and Indian lands.

I think these are for the federal laws page.

Also: can we monitor content changes with the Tracking feature in Microsoft Word? I think it would be easier to follow.

**Comment by mcharg** [comment]
@daniel-coleman-1 It looked like you pushed changes to the federal laws page in this PR and @Maroyafaied asked if I reviewed both pages.  Is there a Word doc for the federal laws page to put comments in?

**Comment by mcharg** [comment]
@daniel-coleman-1 

This A still needs to be lowercase.  Only H1s use title case.
image

This should be an H4, since it's related to the Deepwater Horizon section.
image

Broken links:
image

These should also be H4s.
image

All these words should start with lowercase:
image

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 @mcharg Yes, it looks like this PR has changes to both the Federal reforms page and Federal laws page. This is the word doc that Dan has his original changes https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B2D2B4D41-0F5D-43A8-B640-E2367289D55C%7D&file=Language%20Revisions%20-%20Laws%20%26%20Fees.docx&action=default&mobileredirect=true

**Comment by mcharg** [comment]
@daniel-coleman-1 I put my edits for federal laws in the doc.

**Comment by mcharg** [comment]
@daniel-coleman-1 

On federal reforms:

The link to BOEM is looking to link to an internal page.
image

**Comment by daniel-coleman-1** [comment]
Federal Laws - 
Implemented @mcharg's changes in dev; coming back as a grade 12 reading level for me in Hemingway.

**Comment by daniel-coleman-1** [comment]
For the BOEM link on Federal Reforms

I changed the link from
<a href="https.boem.gov"> to
<a href="https://www.boem.gov">

I then committed and pushed, but I'm not seeing the updated link on this preview page:
https://nrrd-preview.app.cloud.gov/sites/Content-Structure/how-revenue-works/federal-reforms/

@mcharg  Am I just on the wrong preview page here, and the updates would show on the right page?  Am I doing something else wrong here?

**Comment by daniel-coleman-1** [comment]
All changes implemented.

**Comment by mcharg** [comment]
@daniel-coleman-1 We don't close PRs unless we're not merging them for some reason.  The process is to wait for approval and then @Maroyafaied merges after all approvals are received.

**Comment by mcharg** [comment]
Federal Reforms looks good.

**Comment by mcharg** [comment]
@daniel-coleman-1 Federal Laws

The FOGRMA link is still linking to a doc we're removing on onrr.gov. Please replace it with this link: https://uscode.house.gov/view.xhtml?path=/prelim@title30/chapter29&edition=prelim
image

We're also removing this doc on onrr.gov.  The regs team told us to remove the link on the Public Laws page.  @Maroyafaied Do you want to remove it here or find a different link?
image

@daniel-coleman-1 I put updated text into the doc for the page intro and the intros to the Fiscal regime and Regulations sections that reduce reading level.

**Comment by mcharg** [comment]
@daniel-coleman-1 I get a grade 13 when I copy and past the whole page into Hemingway, but putting in a line break between each table column reduces it to grade 8.

**Review by mcharg — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 

1. Please replace the RSFA link with this link https://www.congress.gov/104/plaws/publ185/PLAW-104publ185.pdf
image

2. Please replace the FOGRMA link with this link https://uscode.house.gov/view.xhtml?path=/prelim@title30/chapter29&edition=prelim
image

**Comment by mcharg** [comment]
@daniel-coleman-1 Are you going to put the RSFA act back in with the link Maroya provided?

**Comment by daniel-coleman-1** [comment]
@mcharg @Maroyafaied Could one of you post a preview link for the Federal Laws page?   I'm trying to find a way to access it and struggling.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 this is the preview link from your branch to the federal law page https://revenuedata.doi.gov/how-revenue-works/federal-laws/, also it looks like RSFA is still there, you just have to change the link.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied both changes have been implemented

**Comment by daniel-coleman-1** [comment]
> @daniel-coleman-1 this is the preview link from your branch to the federal law page https://revenuedata.doi.gov/how-revenue-works/federal-laws/, also it looks like RSFA is still there, you just have to change the link.

@Maroyafaied is that a preview link?  It doesn't look like one to me (but still figuring things out).

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 yes it's a preview link, unless you mean something different by referring to a preview link? If there's any confusion , you can bring it up during sync up and I'll do my best to clarify.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied Yes I think I've confused myself, I'll bring it up at sync.  That being said, changes are implemented and this page should be good to go!

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 both RSFA and FOGRMA links are not updated for me, @mcharg can you check?

**Comment by mcharg** [comment]
@Maroyafaied They're updated for me.

**Review by mcharg — APPROVED** [review]

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
