### PR TITLE
Generalize all chart styling

### LINKED ISSUE #197: Create state county map from filters

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #197, #295, #313

[:sunglasses: PREVIEW](https://313-stylemapstobegeneralized.app.cloud.gov/explore)

Changes proposed in this pull request:

- Updates explore data map to have more generalized styling 
- adds overlay on scroll for full screen map
- adds revenue by county map zoomed into state
- truncates long circle chart labels
- refactors explore data page design
- removes console errors

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr I think we still need to add a button CTA to scroll down.

**Comment by mcharg** [comment]
@jlouis-onrr I like the explore more button.

I do think we need to add labels to the plus and 3 dot buttons because users aren't getting what they do in testing.

**Comment by jlouis-onrr** [comment]
@mcharg this branch now has the explore more data button to take you down into the content.  For the add locations and explore menu buttons, I've move them to the top for now and have added some tooltips.  I think labels would be better and more helpful by styling the theme look similar to the other toolbar selections.

**Comment by mcharg** [comment]
@jlouis-onrr We can watch in user testing to see if the tooltips are enough.

**Comment by jlouis-onrr** [comment]
@mojobnichols, if you are good with this PR, I'd like to merge into dev?

**Pull request merged**
