### PR TITLE
Update coal-excise-tax.mdx

### PR DESCRIPTION
**Pull request by Baymatt**
Fixes #<1266>

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/coal-excise-tax/)

Changes proposed in this pull request:

- Updated BLDTF link with FY21 information
- Updated table with information for 2018 and 2019
- Added line breaks to improve formatting of page

### CODE REVIEW

**Comment by jennmalcolm** [comment]
@Baymatt you, just need to change your preview link to include your branch name, i.e.:

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/coal-excise-tax/)

**Comment by Baymatt** [comment]
Thanks for the heads up @jennmalcolm!

**Comment by jennmalcolm** [comment]
@Baymatt, this is looking really good. There is just one more update that we need to make. It looks like the tax rates changed again at the beginning of 2020, so we need to update that section. Here is the new info: https://www.irs.gov/businesses/small-businesses-self-employed/change-in-rate-for-coal-excise-tax#:~:text=From%20January%201%2C%202019%2C%20to,4.4%25%20of%20the%20sale%20price.

I can work on that update if you would like, but I want to check with you first before I edit your branch. Thanks!

**Comment by Baymatt** [comment]
@jennmalcolm I can work on that right now really quickly. If I'm reading the information correctly, it seems like the rates went back to the previous amounts?

**Comment by jennmalcolm** [comment]
Yes @Baymatt that's what it looks like to me. It would probably still be worthwhile to explain that rates were lower (and what they were) during 2019.

**Comment by Baymatt** [comment]
@jennmalcolm I made the changes by editing the rates, % and also the date. The preview isn't working but it should be good to go.

**Review by jennmalcolm — APPROVED** [review]

**Pull request merged**
