### PR TITLE
Updates ONRR logo

### LINKED ISSUE #1842: Update ONRR logo on NRRD site
It's on this page.
https://revenuedata.doi.gov/about/

### PR DESCRIPTION
**Pull request by mcharg**
Fixes #1842

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/logo/about/)

Changes proposed in this pull request:

- Updates the ONRR logo on the about page
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr Can you take a look at this?  It's doing weird things with the SVG.

**Comment by mcharg** [comment]
@jlouis-onrr I also couldn't figure out how to change it to a different file and just use the PNG.

**Comment by mcharg** [comment]
@jlouis-onrr The preview failed and the rerun function is grayed out for me in CircleCI.

**Comment by mcharg** [comment]
The logo is displaying better for me now.  It's a little fuzzy, but at least all the pieces are there.
image

**Comment by mcharg** [comment]
@jlouis-onrr It's pulling in a different font.  It should be Arial.
image

**Comment by jlouis-onrr** [comment]
@mcharg, Most likely due to the way I exported the svg in illustrator.  Let me double check those settings.

**Comment by mcharg** [comment]
@jlouis-onrr This looks good.

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
