### PR TITLE
Upload Oct Revenue and July Prd

### LINKED ISSUE #1833: Upload July 21 Production & Oct 21 Revenue

### PR DESCRIPTION
**Pull request by cthomasONRR**
Fixes #1833 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Data-Uploads)

Changes proposed in this pull request:

-Upload October 2021 Revenue
-Upload July 2021 Production
-Upload October 2021 Disbursements

### CODE REVIEW

**Comment by cthomasONRR** [comment]
**Production Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved [here](https://teams.microsoft.com/l/file/205D1AD9-19F9-477D-B13F-CAB02147ACCC?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=csv&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FProduction%2FFY%202021%2FProduction%20Volumes%20as%20of%2011-8-2021_CSV_DO%20NOT%20EDIT.csv&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Source File
- [ ] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Land Type filter
- [ ] One to three Products
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
**Revenue Monthly** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved [here](https://teams.microsoft.com/l/file/68B14464-2E2C-495F-B258-6ADCD269CCF1?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=csv&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FRevenue%2FFY%202022%2FOctober%202021%20Revenue%20for%20Portal_CSV_DO%20NOT%20EDIT.csv&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout Commodity
 
Homepage - Source File
- [ ] Check source file links are correct.
 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [ ] One Land Type filter
   - [ ] One Revenue Type filter
   - [ ] One State (for Yearly data only)
   - [ ] One Offshore Region
   - [ ] One to three Commodities
   - [ ] Clear All and change grouping
   - [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by lpgoldstein** [comment]
@cthomasONRR revenue and production look good to me. I'll wait to approve until after we get disbursements added.

**Comment by Baymatt** [comment]
**Disbursements Monthly** 

- [ ] Make sure the downloaded data matches the raw data. 

- [ ] Check Treasury Fund column is deleted
- [ ] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [ ] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
  - [ ] Breakout - Source 
  - [ ] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Recipient
- [ ] One Source
- [ ] One State
- [ ] One to three Commodities if applicable
- [ ] Clear All and change grouping
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by Baymatt** [comment]
@cthomasONRR @lpgoldstein  I found a difference in the query tool when the column contains Commodity and the Source is Offshore, the values for Not Tied to a Commodity and Wind match but values for Oil and Gas Pre Production, Oil and Gas do not match. Could one of you help me double check and see if you get the same values or if I'm looking at the data incorrectly. Otherwise, everything else looks good.

Screen Shot 2021-11-24 at 12 45 10 PM

<b>Not Tied to A Commodity has correct values.</b>

Screen Shot 2021-11-24 at 12 45 21 PM

Screen Shot 2021-11-24 at 12 45 31 PM

**Comment by lpgoldstein** [comment]
@Baymatt I'll take a look - thanks for spotting

**Comment by lpgoldstein** [comment]
@Baymatt when the source is selected as just offshore in the query tool - it doesn't take 8(g) and GOMESA offshore into account as well. That's why it looks wrong. This first image is from the download of the query tool. image The second image is from the download file. The download file considers offshore to be one category and you have to further pivot for "disbursement type" to get to the more granular numbers. 
image Thanks for bringing up that question - it's always good to dig and make sure the database is doing the correct roll ups.

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein is data looking good in this PR? I merged dev into this branch so the unit update that @jlouis-onrr fixed can show in here.

**Comment by lpgoldstein** [comment]
@Maroyafaied I need to finish checking disbursements data but everything is looking good so far.

**Review by lpgoldstein — APPROVED** [review]

**Comment by cthomasONRR** [comment]
@Maroyafaied I checked revenue and production last week (I think Lindsay did too), and everything matched exactly! :)

**Pull request merged**
