### PR TITLE
Update monthly_disbursements.csv

### LINKED ISSUE #1729: upload disbursement Fy18 data

### PR DESCRIPTION
**Pull request by lpgoldstein**
Fixes #1729 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/septdata/)

Changes proposed in this pull request:

- added monthly data from October 2017-September 2018

### CODE REVIEW

**Comment by cthomasONRR** [comment]
I added monthly production to this PR. Here is the checklist:

**Production Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Source File
- [ ] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Land Type filter
- [ ] One State
- [ ] One Offshore Region
- [ ] One to three Products
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by lpgoldstein** [comment]
@cthomasONRR Production looks good to me too.

**Comment by cthomasONRR** [comment]
@lpgoldstein Great! I will review revenue for you!

**Comment by lpgoldstein** [comment]
- [ ] Make sure the downloaded data matches the raw data. Raw data saved [here](https://teams.microsoft.com/l/file/448C5F07-3D45-484E-BD19-386E795642BD?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=csv&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FRevenue%2FFY%202021%2FAugust%202021%20Revenue%20for%20Portal.csv&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Homepage - Yearly Breakdown

- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.

    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout Commodity
 
Homepage - Source File
- [ ] Check source file links are correct.

Query Data

- With a selected fiscal or calendar year range, verify the data is correct and then for the conditions below. 
- [ ] One Land Type filter
- [ ] One Revenue Type filter
- [ ] One State
- [ ] One Offshore Region
- [ ] One to three Commodities
- [ ] Clear All and change grouping
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by cthomasONRR** [comment]
@lpgoldstein I checked the revenue data. One thing that looks odd in the visualizations but it likely correct (since it matches the excel) is December 2020 O&G (pre-production) revenue of -268,130,891... it makes the 'other commodities' section very negative. It just looks odd that this is such a large negative number. Is there any explanation for it?

image

**Comment by lpgoldstein** [comment]
@cthomasONRR There is an explanation and I don't remember what it is exactly but I believe it was some kind of correction to reporting from a previous month. @Maroyafaied might remember exactly what it was.

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein A company misreported that month and made the correction the next month.  This month's negative number was brought up in a few meetings with upper management and verified by DORC that it was a misreporting with the adjustment made in January.

**Review by cthomasONRR — APPROVED** [review]
@Maroyafaied @lpgoldstein Thanks for the explanation!!! Both the revenue and production data look good. I am approving this PR.

**Review by Baymatt — APPROVED** [review]
Didn't create a separate checklist but I double checked the revenue data. Everything looks good, approving the PR.

**Comment by rawaaziz1** [comment]
Everything looks good as far as I can tell.

**Comment by Maroyafaied** [comment]
@lpgoldstein @cthomasONRR does this PR have FY18 disbursement data as well? I'm not seeing it in the preview link.

**Comment by lpgoldstein** [comment]
@Maroyafaied there will be disbursements data. @mojobnichols and I need to go over tomorrow.

**Comment by cthomasONRR** [comment]
@mojobnichols @lpgoldstein Is it ok if I add in the August disbursements to this PR as well?

**Comment by lpgoldstein** [comment]
> @mojobnichols @lpgoldstein Is it ok if I add in the August disbursements to this PR as well?

I will defer to @mojobnichols on this one. It would be okay with me.

**Comment by cthomasONRR** [comment]
**Checklist for August Disbursements** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [ ] Check Treasury Fund column is deleted
- [ ] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [ ] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- [ ] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [ ] Breakout - Source 
- [ ] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Recipient
- [ ] One Source
- [ ] One State
- [ ] One to three Commodities if applicable
- [ ] Clear All and change grouping
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
August Disbursement data looks good!
@lpgoldstein - I will start looking at the new monthly 2018 data

**Comment by cthomasONRR** [comment]
**Disbursements Fiscal Year 2018** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Explore Data - Map and Detail Card
- With a fiscal year selected, verify the detail card and Disbursements Over Time are correct for the conditions below. Repeat with the current fiscal year.
    - [ ] State with data
    - [ ] State without data
    - [ ] County with data
    - [ ] County without data
    - [ ] Offshore Region
    - [ ] Nationwide Federal Card
    - [ ] Native American Card

Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- Verify breakdowns by disbursement recipient and source are correct as well nationwide recipients for the conditions below.
    - [ ] Not current Fiscal Year
    - [ ] Current Fiscal Year

Query Data - In the 'Period' category, filter to 'Fiscal Year' and check the following:
- [ ] One Recipient
- [ ] One Source
- [ ] One State
- [ ] One to three Commodities if applicable
- [ ] Clear All and change grouping
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by cthomasONRR** [comment]
The only issue I see with the FY 2018 disbursement data is the $100 discrepancy between the summed monthly data and the FY 2018 download: 

image

**Comment by Maroyafaied** [comment]
@lpgoldstein @cthomasONRR it looks like the difference is coming from U.S Treasury. I will email the disbursement team and let them know.  
image

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein @mojobnichols 
I'm looking at the newly downloaded FY 18 disbursements data from the Preview link. I'm doing the same comparisons as I did last week, and all the values are approx 2x what they should be, but still does not exactly match up with 2018 monthly raw data:
image
image

**Comment by lpgoldstein** [comment]
> @Maroyafaied @lpgoldstein @mojobnichols
> I'm looking at the newly downloaded FY 18 disbursements data from the Preview link. I'm doing the same comparisons as I did last week, and all the values are approx 2x what they should be, but still does not exactly match up with 2018 monthly raw data:
> image
> image

@cthomasONRR @mojobnichols @Maroyafaied I'm seeing the same thing for fy18, 19 and 20 in the fy download file. The monthly download file looks okay though. It must be a database issue.

**Comment by cthomasONRR** [comment]
@mojobnichols @lpgoldstein @Maroyafaied 
With Mojo's recent fix, we're back to all the data matching the monthly raw except for the $100 difference in the Treasury. The FY 2018 rolled data should have U.S. Treasure at 3,510,314,248.58
image
image

**Comment by Maroyafaied** [comment]
@mojobnichols shouldn't the FY file match exactly the monthly file for FY18? The $100 difference in Treasury shouldn't be there.

**Comment by lpgoldstein** [comment]
@mojobnichols @cthomas @Maroyafaied ONRR 2019 and 2020 look good

**Comment by Maroyafaied** [comment]
@cthomasONRR @mojobnichols I thin it should be combined with other funds, that's how it was combined before and if we combine it with Native American tribes and individuals , it makes it seem as the fund is not matching what it is in the monthly file.

**Comment by Maroyafaied** [comment]
@lpgoldstein I'll check with Darrel if he agrees with rolling up TreasuryAI with Native American Tribes & Allottees since it looks like prior to doing it manually, it was rolled up with 'other' for previous fiscal years.

**Comment by lpgoldstein** [comment]
@Maroyafaied Thank you!

**Comment by lpgoldstein** [comment]
@mojobnichols @Maroyafaied @cthomasONRR August query tool matches the monthly download file now.

**Pull request merged**
