### PR TITLE
Card title detail updates

### LINKED ISSUE #650: Add the state the county belongs to on the summary cards, like it is on the detailed cards.
Summary card:

Detail card:

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #650, #572, #652, #638, #667, #392

[:sunglasses: PREVIEW](https://650-addstatetocountysummarycards.app.cloud.gov/explore)

Changes proposed in this pull request:

- [x] Adds state to summary card header
- [ ] Adds query production link for Native American production
- [x] Add "land" to % federal on detail cards 
- [x] Updates all instances of How it works to "How revenue works"
- [x] Remove top locations for production from Offshore region cards 
- [x] Adds change copy for revenue and disbursements and fix for production

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr On the links to the query tool for both production and revenue, it should select Native American as the land type.

**Comment by mcharg** [comment]
And can you add the query tool icon before the links? 
image

**Comment by jlouis-onrr** [comment]
> @jlouis-onrr On the links to the query tool for both production and revenue, it should select Native American as the land type.

@mcharg, I believe @master12 is working on getting the url params to set the appropriate selections within the query tool. Ill need to coordinate to see which params are needed for each instance.

**Comment by mcharg** [comment]
I thought the params were put in last sprint.  That's why we had taken the links out before and thought we could bring this change in now.

**Comment by mcharg** [comment]
@jlouis-onrr The icon looks good on production, can you also add it to the revenue link?
image

If the params aren't ready to be used yet, I think it's okay to go ahead and push with the links as is, until they're setup.

**Comment by mcharg** [comment]
I added #684 to add the parameter to the url for the Native American links.

**Comment by jennmalcolm** [comment]
@jlouis-onrr on this branch, the summary cards are showing zeros. I also got a "something went wrong" error when I switched from production to disbursements.

image

I also got "something went wrong" when I try to open a card under revenue.

**Comment by mcharg** [comment]
@jlouis-onrr - @master12 has the parameters working in a PR.

The urls you need will look like this:
https://664-update-drop-downs.app.cloud.gov/query-data/?dataType=Production&landType=Native%20American
https://664-update-drop-downs.app.cloud.gov/query-data/?dataType=Revenue&landType=Native%20American

**Comment by mcharg** [comment]
@jlouis-onrr I'm seeing the same thing as Jennifer with the production summary cards showing 0 and then when I tried switching from Production to Revenue, the cards showed a graphql error, but then it switched to the something went wrong page before I could get a screenshot.

**Comment by lpgoldstein** [comment]
@jlouis-onrr I'm getting an error when I try to look at revenue data by clicking on anything in the map.
image

**Comment by lpgoldstein** [comment]
@jlouis-onrr Now getting this error when I try to look at the production summary cards 
image

**Comment by jlouis-onrr** [comment]
@lpgoldstein, @mcharg, currently trying to resolve all conflicts with dev

**Comment by lpgoldstein** [comment]
@jlouis-onrr something wonky is still going on 
image

**Comment by mcharg** [comment]
@jlouis-onrr I'm able to pull up cards and the production ones are no longer 0s, but I'm seeing the graph ql error on the production intro.
image


And revenue over time isn't populating:
image

Production over time section is completely missing:
image

Disbursements over time is working correctly.

**Comment by jlouis-onrr** [comment]
@mcharg, @lpgoldstein, the issues you experienced yesterday should be resolved now.

**Comment by mcharg** [comment]
@jlouis-onrr The production over time line chart is still missing and I just noticed it's missing from dev, but it's in beta.

**Comment by mcharg** [comment]
@jlouis-onrr Should we merge this and address the line chart in dev?

**Comment by jlouis-onrr** [comment]
@mcharg, maybe we should have @mojobnichols review as well as there were a lot of conflicts with dev before merging.

**Comment by jlouis-onrr** [comment]
@mcharg, shouldn't summary cards have CY/FY for the trend year, based on period?  Not seeing that in dev either.

**Comment by mcharg** [comment]
@jlouis-onrr They should.

**Comment by jlouis-onrr** [comment]
@mcharg, @mojobnichols, should now be seeing production over time in this PR

**Comment by mcharg** [comment]
Looks good!

**Pull request merged**
