### PR TITLE
Different visual for query data sort label

### LINKED ISSUE #1057: Consider different visual for sort arrow
A couple participants didn't understand what it was for. Consider using a different icon or having arrows visible on all columns.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #1057
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1057-VisualSortArrow/query-data/)

Changes proposed in this pull request:

- Adds new component CustomTableHeaderSortLabel to manage sort label
- Update MUI icons
- Updated stylgin

### CODE REVIEW

**Review by mcharg — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@jlouis-onrr I keep getting this message when I try to open the preview link, my internet is working with everything else. I'll try again later today or tomorrow.
image

**Comment by Maroyafaied** [comment]
@jlouis-onrr I tried a few times and I'm getting the same error as above.

**Comment by mcharg** [comment]
@Maroyafaied I'm thinking there's an issue with the database. I'm getting the same error on the homepage in dev.

**Comment by jlouis-onrr** [comment]
looks like there is a 404 connecting to the db:

Access to fetch at 'https://hasura-nrrd-b.app.cloud.gov/v1/graphql' from origin 'https://dev-nrrd.app.cloud.gov' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
