### PR TITLE
Update disbursements page under how-revenue-works

### LINKED ISSUE #1261: Thorough audit and update of disbursements page
Notes from content audit:

Grade level up; spacing issues; same glossary question as 2020; check on sequestration to see if 49% is still accurate; should we add anything to this page about NPPLLRF?

Manually curated data: percentages

### PR DESCRIPTION
**Pull request by Baymatt**
Fixes #1261

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/update-disbursements-page/how-revenue-works/disbursements)

Changes proposed in this pull request:

- Made updates to the percentages that states receive
- Added spacing
- Added small paragraph for state and county level disbursements (GOMESA & geothermal)

### CODE REVIEW

**Comment by mcharg** [comment]
@Baymatt The preview link isn't working.

**Comment by mcharg** [comment]
@Baymatt The link is working now.

**Comment by mcharg** [comment]
@Baymatt @Maroyafaied I made some edits to get the reading level down to grade 10.

**Review by mcharg — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@mentastc can you please review this disbursement page especially this new paragraph. Thanks 
image

**Comment by Maroyafaied** [comment]
@Baymatt where did you verify these percentage changes? I just want to be sure before I approve it. Thanks 
image

**Comment by Baymatt** [comment]
@Maroyafaied I found the information here, https://fas.org/sgp/crs/misc/R46537.pdf

"Some key provisions in the MLA include a 12.5% minimum royalty rate; 40% of revenues arising from oil and gas leasing on federal lands in states other than Alaska are deposited into the Reclamation Fund; and that states other than Alaska receive 50% of revenues from extraction operations in those states (Alaska receives 90%). Disbursements to states are assessed a 2% administration fee, which is deposited in the Treasury."

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
