### PR TITLE
Color card headers

### LINKED ISSUE #329: Consider coloring the card headers to match the line chart
This is something we've talked about and should revisit at some point.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #329
[:sunglasses: PREVIEW](https://preview-nrrd.app.cloud.gov/explore?dataType=Revenue&location=NF%2CNA%2CMT%2CCA&mapLevel=State&offshoreRegions=false&period=Fiscal%20Year&year=2019)

Changes proposed in this pull request:

- adds color to card headers to match line chart
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
My one concern is that the colors aren't very contrasted from each other without the patterns we have on the line chart.  This is what they look like in B&W.
image

Maybe we should consider pulling colors from this palette I did for the circle chart issue.
image

Which is more differentiated in B&W.
image

**Comment by jlouis-onrr** [comment]
@mcharg, the updated palette and header colors are now out in preview

**Comment by mcharg** [comment]
@jlouis-onrr Removing cards isn't quite working right.  I tried removing Nationwide and Native American to see if the colors on the line chart are differentiated enough, but the lines are staying and the remaining detail cards are spacing out weird.
image

**Comment by mcharg** [comment]
@jlouis-onrr The line chart still isn't removing the line when I remove Nationwide.
image

**Comment by mcharg** [comment]
@jlouis-onrr In dev after merging, adding cards doesn't add all the lines on the line chart. 
image

**Pull request merged**
