### PR TITLE
453 production offshore data

### LINKED ISSUE #453: offshore data not working
@mojobnichols offshore data for production and revenue is not working for Jennifer and I. 
image

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #453

[:sunglasses: PREVIEW](https://453-ProductionOffshoreData.app.cloud.gov/explore/)

Changes proposed in this pull request:
WIP still trying to get Alaska to merge offshore, but the database is the sandbox so data can be reviewed for accuracy here.

This PR involves moving the sandbox database to the production database, so we need to do a pretty thorough review of the data. I'm copying the data check boxes from our QA issue to help us mark what we've reviewed using this PR.

Explore data - Revenue
 - [x] Check all summary cards and spark lines for nationwide, Native American, and sample of states/offshore areas/counties
 - [ ] Check all detailed cards and line charts for nationwide, Native American, and sample of states/offshore areas/counties
 - [x] Check data on map hover for sample of states/offshore areas/counties/commodities
 - [ ] Check all nationwide summary data on charts
 - [x] Check all of the above for sample set of 3-4 years including at least 1 before 2009 

Explore data - Production
 - [ ] Check all summary cards and spark lines for nationwide, Native American, and sample of states/offshore areas/counties
 - [ ] Check all detailed cards and line charts for nationwide, Native American, and sample of states/offshore areas/counties
 - [ ] Check data on map hover for sample of states/offshore areas/counties
 - [ ] Check all nationwide summary data on charts
 - [ ] Check all of the above for sample set of commodities
- [ ] Check all of the above for sample set of 3-4 years including at least 1 before 2009 including at least 1 before 2009

'Explore data - Disbursements
 - [ ] Check all summary cards and spark lines for nationwide, Native American, and sample of states/counties
 - [ ] Check all detailed cards and line charts for nationwide, Native American, and sample of states/counties
 - [ ] Check data on map hover for sample of states/offshore areas/counties
 - [ ] Check all nationwide summary data on charts
- [ ] Check all of the above for sample set of 3-4 years including at least 1 before 2009 including at least 1 before 2009

Homepage charts
- [ ] Hover behavior is working 
- [ ] Data displayed is correct - revenue
- [ ] Data displayed is correct - production
- [ ] Data displayed is correct - disbursements
- [ ] Chart changes if you select yearly or monthly

Homepage trends
- [ ] spark lines trend appears correct - revenue 
- [ ] FY 20 data displayed is correct - revenue
- [ ] spark lines trend appears correct - disbursements
- [ ] FY 20 data displayed is correct - disbursements

-
-
-

### CODE REVIEW

**Comment by Maroyafaied** [comment]
I get an error message "something went wrong" when I click on an offshore area.

**Comment by mojobnichols** [comment]
I fixed the onclick  by disabling it for now. Let me know if that is not acceptable for soft launch and I'll get cracken... but I'd recommend disabled for the soft launch and we address it soon after.

**Comment by Maroyafaied** [comment]
@mojobnichols I'm not able to get a card displayed when I click on an offshore region, but I checked the data by hovering over it and checking that number and it looks correct. I checked a few years.

**Comment by mojobnichols** [comment]
I got it to stop bombin by disabling cards for offshore for now.  I'm not sure how much will be involved in reenabling them but I felt like it was more then a day.  We'll see what I have on my plate tomorrow.
I think my next priority is the  top locations for production.

**Comment by jennmalcolm** [comment]
@Maroyafaied did you review some of the data for accuracy? If so, could you note what you looked at in here?

**Comment by Maroyafaied** [comment]
@jennmalcolm yes, I looked at production offshore data for oil and gas , I checked a few years by hovering over the offshore region and verifying the data.

**Comment by jennmalcolm** [comment]
This PR involves moving the sandbox database to the production database, so we need to do a pretty thorough review of the data. I'm copying the data check boxes from our QA issue to help us mark what we've reviewed using this PR. Explore data - Revenue
 - [ ] Check all cards and line charts for nationwide, Native American, and sample of states/offshore areas/counties
 - [ ] Check data on map hover for for sample of states/offshore areas/counties
 - [ ] Check all nationwide summary data on charts
 - [ ] Check all of the above for sample set of commodities
 - [ ] Check all of the above for sample set of 3-4 years including at least 1 before 2009 

Explore data - Production
 - [ ] Check all cards and line charts for nationwide, Native American, and sample of states/offshore areas/counties
 - [ ] Check data on map hover for for sample of states/offshore areas/counties
 - [ ] Check all nationwide summary data on charts
 - [ ] Check all of the above for sample set of commodities
- [ ] Check all of the above for sample set of 3-4 years including at least 1 before 2009 including at least 1 before 2009

'Explore data - Disbursements
 - [ ] Check all cards and line charts for nationwide, Native American, and sample of states/offshore areas/counties
 - [ ] Check data on map hover for sample of states/offshore areas/counties
 - [ ] Check all nationwide summary data on charts
- [ ] Check all of the above for sample set of 3-4 years including at least 1 before 2009 including at least 1 before 2009

Homepage charts
- [ ] Hover behavior is working 
- [ ] Data displayed is correct - revenue
- [ ] Data displayed is correct - production
- [ ] Data displayed is correct - disbursements
- [ ] Chart changes if you select yearly or monthly

Homepage trends
- [ ] spark lines trend appears correct - revenue 
- [ ] FY 20 data displayed is correct - revenue
- [ ] spark lines trend appears correct - disbursements
- [ ] FY 20 data displayed is correct - disbursements

**Comment by lpgoldstein** [comment]
@jennmalcolm The production data is slightly off - is this because we replace the entire monthly production data on a monthly basis and there are slight changes to past years on a monthly basis?

**Comment by jennmalcolm** [comment]
@lpgoldstein are you talking about the home page data or the explore data production data?

**Comment by lpgoldstein** [comment]
@jennmalcolm explore data production nationwide cards

**Comment by jennmalcolm** [comment]
That data should be coming from the FY file, right @mojobnichols?

**Comment by lpgoldstein** [comment]
I'll post a picture of what I'm seeing.

**Comment by jennmalcolm** [comment]
I'm working on reviewing revenue, just so we don't duplicate each other.

**Comment by Maroyafaied** [comment]
I'm working on production

**Comment by lpgoldstein** [comment]
@Maroyafaied I was working on production and comparing to current website homepage and query tool but only got through nationwide

**Comment by mojobnichols** [comment]
I moved your check list up to top of the pr for convenience.

**Comment by mojobnichols** [comment]
I merged 450 into this for everyone's convenience plus the underlying view for circles may have impact on other things in the the above checklist

**Comment by Maroyafaied** [comment]
The production numbers on the cards don't match the data. For example, oil production in CO in FY 10 is 6,0671,213 bbl, the card is showing 30,415 then shows unmatched wrong number on the bar chart. . 
The county data is correct except for the "other" calculation, also for production in CO oil, I match all the counties but for other I get the sum of 182,109 and the card shows 22,525.  Also, county map is not showing color. 
image
image

**Comment by Maroyafaied** [comment]
Data for production nationwide summary is not matching, this example is FY 19 Gas 
image

**Comment by jennmalcolm** [comment]
@Maroyafaied I was on production and noticed that the tool tip amounts are also looking weird. For example, CO has 367 bbls of oil for 2019. I don't know if something changed when @mojobnichols merged in #450, but will you take a look to see if we should uncheck the items that you checked off the list for production?

**Comment by jennmalcolm** [comment]
Oh I was in Jerome's PR wen I saw 367 bbl for CO, but in this one it is 30,415, which is also wrong 
According to my numbers, it should be 6,057,213

**Comment by Maroyafaied** [comment]
@jennmalcolm yes the tool tip amount is also wrong as well as the comparison cards number.

**Comment by jennmalcolm** [comment]
Strangely the detailed cards are showing up ok on desktop, but the states seemed mixed up when I looked on mobile. The commodity NM numbers are on the NV card on mobile...
image

image

**Comment by jennmalcolm** [comment]
The other detail card numbers I've checked have been good, but other commodities CA 2016 is off. 
image

**Comment by mojobnichols** [comment]
@jennmalcolm, 

I'm unable to reproduce other being off.... I didn't do anyhing to fix it. unless some fix for something else corrected it.

**Pull request merged**
