### PR TITLE
upload revenue by company CY 20

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/data-update-august/)

Changes proposed in this pull request:

- Upload revenue by company CY 20, raw data 
-
-

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein it looks like the data loaded just fine , I'm seeing it in the download page, in explore data and query tool!

**Review by cthomasONRR — COMMENTED** [review]
I made the following checklist, and just used it to check the data. Everything I checked looks good, but I will hold off with approving until someone ok's the checklist. Please let me know if something should be added. Thanks!

**Revenue by Company** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved [here](https://teams.microsoft.com/l/file/BCAFFDD4-557B-4C74-8405-30E9884403B4?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FRevenue%20by%20company%2FCY20%20Federal%20Revenues%20by%20Company%20Final.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Explore Data - Click on the "Federal revenue by company" link below the map
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
   - [ ] One to three Companies
   - [ ] Revenue Types within a Company
   - [ ] One to three Commodities
   - [ ] Clear All and change grouping
   - [ ] Download matches filtered data

Query Data - In the "Data Type" category, filter to "Federal revenue by company"
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
   - [ ] One to three Companies
   - [ ] One to three Revenue Types
   - [ ] One to three Commodities
   - [ ] Clear All and change grouping
   - [ ] Download matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by Maroyafaied** [comment]
@mojobnichols it looks like the negative number issue is not fixed based on @cthomasONRR findings.

**Review by cthomasONRR — APPROVED** [review]
I reviewed the most recent data preview with the fixes to the negative numbers. I used the checklist I created and didn't find any issues. All the data matches and filtering is working well!
 
@lpgoldstein and @Maroyafaied please let me know if you want me to add/change anything in the checklist.

Approving this PR.

**Comment by lpgoldstein** [comment]
@cthomasONRR and @Maroyafaied Everything looks good to me now too! @cthomasONRR I think the checklist covers everything. Thanks !

**Review by lpgoldstein — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@cthomasONRR for the explore data checklist, you can take out the last two items since there's no "clear all" button in explore data and you can't download data filtered in explore data. I'd also like to add to that list to ensure the top 10 companies data are correct including amount and %,  and to check the "Other Companies" data is displayed correctly as well.
image

image

**Comment by cthomasONRR** [comment]
@Maroyafaied and @Baymatt here's the most updated checklist. 

Revenue by Company

- [ ] Make sure the downloaded data matches the raw data. Raw data saved [here]

Explore Data - Click on the "Federal revenue by company" link below the map
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
   - [ ]  One to three Companies
   - [ ]  Revenue Types within a Company
   - [ ]  One to three Commodities
   - [ ]  Check the Top 10 Companies (highest revenue) to ensure revenue sums and their percent of total is correct
   - [ ]  Check "Other Companies" to ensure that the revenue sum and percent of total is correct

Query Data - In the "Data Type" category, filter to "Federal revenue by company"
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
   - [ ]  One to three Companies
   - [ ]  One to three Revenue Types
   - [ ]  One to three Commodities
   - [ ]  Clear All and change grouping
   - [ ]  Download matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Review by Baymatt — APPROVED** [review]
Data looks good

**Comment by Baymatt** [comment]
@cthomasONRR I used the updated checklist to look over the data and it looks good on my end. One small suggestion is to have the Download Page portion of the checklist at the top and to include the "Make sure the downloaded data matches the raw data. Raw data saved [here]" check under that section to keep consistency with the other checklists.

**Comment by cthomasONRR** [comment]
@Baymatt Thanks for your suggestions! I incorporated your proposed changes to the checklist on the [wiki page](https://github.com/ONRR/nrrd/wiki/Releasing-changes-to-production#updating-data-files).

**Comment by Maroyafaied** [comment]
@mojobnichols can you combine "Calcasieu Paris" to just "Calcasieu" in the database? I tried to fix it within the spreadsheet but it didn't work. 
image

**Comment by mojobnichols** [comment]
> @mojobnichols can you combine "Calcasieu Paris" to just "Calcasieu" in the database? I tried to fix it within the spreadsheet but it didn't work.
> image

It should parse out parish, county and borough  and put them in another field in case we want to use them.   The reasoning was Taos County,  NM is wrong like wise Calcasieu Parish, Louisiana   should just be  Calcasieu,  Louisiana  again we do retain the district type in a field County, Parish or Borough.     Correcting spread sheet to Parish should correct the issue.

**Comment by cthomasONRR** [comment]
@mojobnichols - I'm looking in the spreadsheet (C:\Users\thomasc\Documents\GitHub\nrrd\database\static\csv\disbursements), and they are all spelled "Parish" in this spreadsheet. It's in the downloaded spreadsheet where the issue is occurring.

**Comment by Maroyafaied** [comment]
@cthomasONRR @mojobnichols I went in the PR yesterday and fixed the spelling to "Calcaseiu Parish " in the csv disbursement monthly file but the download generated is still showing both "Calcaseiu" and "Calcaseiu Paris".  Should I take out the word "Parish" in the spreadsheet  in the PR and see if that fixes the issue?

**Comment by cthomasONRR** [comment]
@Maroyafaied @mojobnichols - I'll go in and remove the word "parish" for all the Calcaseiu entries, and see if that fixes anything....

**Comment by mojobnichols** [comment]
> @Maroyafaied @mojobnichols - I'll go in and remove the word "parish" for all the Calcaseiu entries, and see if that fixes anything....

No I need to figure out why the download is getting truncated.   Removing parish might fix but you'll be fixing it for a long time.   Clearly there is some field size issue and it is getting truncated when loaded.   Do we want to the words county, parish and borough to be in download?  I assume yes because they are in original file.

**Comment by cthomasONRR** [comment]
> No I need to figure out why the download is getting truncated. Removing parish might fix but you'll be fixing it for a long time. Clearly there is some field size issue and it is getting truncated when loaded. Do we want to the words county, parish and borough to be in download? I assume yes because they are in original file

@mojobnichols OK- I just went through with that deletion (sorry!). Since we are removing the words 'county', 'parish', and 'borough' from the user-facing website-downloaded data, maybe we can just get rid of those terms? @Maroyafaied what do you think?

**Comment by Maroyafaied** [comment]
@mojobnichols the words "county" and "parish" don't need to be in the download file. There are instances where for example there is "Cameron County" and Cameron Parish" but there are differentiated by the State name.

**Comment by Maroyafaied** [comment]
@cthomasONRR it looks like taking Parish out did fix it but it would be best if @mojobnichols can fix it in the database so we don't have to make this change manually again.

**Comment by cthomasONRR** [comment]
> @cthomasONRR it looks like taking Parish out did fix it but it would be best if @mojobnichols can fix it in the database so we don't have to make this change manually again.

@mojobnichols @Maroyafaied Absolutely agree!

**Comment by Maroyafaied** [comment]
@mojobnichols is it ok to merge this or do you want it open to make the disbursement county fix in the database?

**Pull request merged**
