### PR TITLE
Chart updates and location search fix

### LINKED ISSUE #365: Revenue over time chart - change scale
When comparing two states with one having much higher revenue, the other state just shows as a straight line. Maybe changing the scale would make it less confusing. Here is an example of Texas and Wyoming. 
image

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #365, #318, #373

[:sunglasses: PREVIEW](https://365-revenueovertimechart.app.cloud.gov/)

Changes proposed in this pull request:

- resolves mui tooltip errors
- fix for search location error
- should resolve all homepage anchor links
- line chart styling
- add month to stacked bar charts

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr The homepage anchor links aren't quite right.  See the issue for that for where they should go.

**Comment by mcharg** [comment]
@jlouis-onrr I still can't add an offshore region from the search.

**Comment by jlouis-onrr** [comment]
@mcharg, Im working on tapping into the new locations table which will add the ability to choose offshore regions.  should be out today

**Comment by jlouis-onrr** [comment]
@jennmalcolm this reveiw seems to be available, however this branch is currently connected to the sandbox database for the new location updates.  So, i wont be able to merge this into dev until the sandbox db gets promoted to prod.

https://365-revenueovertimechart.app.cloud.gov/explore/

**Pull request merged**
