### PR TITLE
Summary updates and line chart fixes

### LINKED ISSUE #702: Disbursements nationwide summary issues
The descriptions for LWCF and other funds are switched, and the "How this fund works" links aren't there.

image

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #702, #691

[:sunglasses: PREVIEW](https://702-disbursementsnationwidesummaryissues.app.cloud.gov/explore)

Changes proposed in this pull request:

- [x] fixes disbursements nationwide summary issues
- [x] fixes issues with production line graph on detail chart
- [x] fixes issues with all line charts, adds zero to the years with no data

### CODE REVIEW

**Comment by mcharg** [comment]
This also fixes #703

**Comment by mcharg** [comment]
Production over time isn't taking into account commodity.  

It's only showing numbers for oil:
image

What the numbers should be:
image

**Comment by mcharg** [comment]
@jlouis-onrr Looks like you got the line chart fixed.  Is there anything we should check for analytics?

**Comment by jlouis-onrr** [comment]
@mcharg, no, i just had an update with the legacy counties url parameter, which was updated to mapLevel

**Comment by jlouis-onrr** [comment]
@mcharg, @jennmalcolm  also working on #396, which i think could easily be added to this PR

**Comment by mcharg** [comment]
@jlouis-onrr @mojobnichols is working on the revenue summary in another branch.  You may want to check with him before working on that.

**Comment by mcharg** [comment]
@jlouis-onrr The nationwide summary looks good.

**Comment by mcharg** [comment]
The no data text looks good for production, except the county cards reference the state instead of the county. (I created #715 to refine the copy.)
image


Disbursements still says "No disbursements"
image

**Comment by mcharg** [comment]
@jlouis-onrr Top locations are still showing up for Native American card.
image

**Comment by mcharg** [comment]
@jlouis-onrr Did you fix #667 is this branch?  I thought you did, but now thinking maybe you didn't.

**Comment by mcharg** [comment]
@jlouis-onrr The footer is now doing weird things.
image

**Comment by jlouis-onrr** [comment]
> @jlouis-onrr The footer is now doing weird things.
> image

trying to recreate, I did just push out an update

**Comment by mcharg** [comment]
@jlouis-onrr If you have a state card for a commodity with no production, it's still showing top locations.
image

**Comment by jlouis-onrr** [comment]
> @jlouis-onrr Did you fix #667 is this branch? I thought you did, but now thinking maybe you didn't.

yes, #667 is now added to this branch

**Comment by jlouis-onrr** [comment]
@mcharg, looking into the production top locations labels missing

**Comment by mcharg** [comment]
@jlouis-onrr The footer is still weird after the fixes.
image

**Comment by mcharg** [comment]
On the no data wording for production, offshore is missing the location and Native American reads weird.
image

**Comment by mcharg** [comment]
@jlouis-onrr The footer is now working normally on my machine.

**Comment by mcharg** [comment]
@jlouis-onrr Can you add "land" after Native American on that card when there's no data?  It reads weird without it.
image

The Top Locations section is looking good for all instances I came across.

Also, are you planning on updating the disbursements cards when there's no data to match production and revenue instead of just saying "no data" or do we need a separate issue for that?

image

**Comment by mcharg** [comment]
@jlouis-onrr The production card for Native American looks good.

The summary card for disbursements looks good.  Can you put the same message on the detail card for disbursements to be consistent with the other data types?
image

**Pull request merged**
