### PR TITLE
 Fixes for missing text/duplicating

### LINKED ISSUE #713: Missing text/duplicating text? on production detail cards and top locations circle charts
For salt 2003. There were only 4 producers that year so should only be 4 circles. It's repeating LA for some reason. 
image
image

image

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #713

[:sunglasses: PREVIEW](https://713-duplicatingtextproductiondetailcards.app.cloud.gov/explore)

Changes proposed in this pull request:

- fixes for missing text/duplicating text on production detail cards and top locations circle charts
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr I get an error when trying to open the Louisiana card after picking Production, Salt, 2003, and nationwide card.
image

**Comment by mcharg** [comment]
@jlouis-onrr Also tried a different order.  Added Louisiana, nationwide, picked Production, Salt, error came up when picking 2003.

**Comment by mcharg** [comment]
The top locations issue appears to be fixed.

**Comment by mcharg** [comment]
@jlouis-onrr The issue seems to be specific to Louisiana.  I can add all the other cards for state with production in 2003.  I can have Louisiana open for 2019, but when I slide to other years it crahses on some of them.

**Comment by mcharg** [comment]
The Louisiana issue is also an issue in dev, so I created #745 to fix that.

**Comment by lpgoldstein** [comment]
@jlouis-onrr I'm getting the same issues as Shannon. So weird that it's just Louisiana.

**Comment by jlouis-onrr** [comment]
I'll try and recreate this issue and get a fix out to this branch.

**Comment by jlouis-onrr** [comment]
@mcharg, just put a fix to this branch for the issue you guys encountered.  this should resolve #745

**Comment by lpgoldstein** [comment]
@jlouis-onrr Louisiana works now! Thanks!

**Comment by mcharg** [comment]
Working for me, too!

**Pull request merged**
