### PR TITLE
added monthly data for prod and disb

### LINKED ISSUE #96: Add monthly data to query tool

### PR DESCRIPTION
**Pull request by master12**
Fixes #96 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/96-add-monthly-disbursements-production/)

Changes proposed in this pull request:

- added monthly period for production and disbursements
-
-

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@master12 I'm getting this error message 
image

**Comment by mcharg** [comment]
@master12 When you have monthly data, the columns should be for months instead of years and the users should be able to pick a start and end month instead of year.  We may need to use drop-downs instead of the slider for that.  Like in this old prototype: 
image

**Comment by mcharg** [comment]
@master12 Can you make the product expand and collapse like when there's more than one column in the yearly view?
image

**Comment by mcharg** [comment]
@master12 disbursements aren't grouping by recipient.
image

**Comment by mcharg** [comment]
And can you left align the label for the month column to match the data in the column?

**Comment by Maroyafaied** [comment]
@master12 the disbursement year slider should start at 2018 since we have monthly data starting from October 2018. And the month title still needs to be aligned with its column. 
image

**Comment by Maroyafaied** [comment]
@mojobnichols can you look into why disbursement monthly is not there from October 2018 and why 2021 is showing up?

**Comment by Maroyafaied** [comment]
@master12 can we remove the state/offshore region as an option in column 2 since that information is not available for monthly.  l did a quick data check and the data is not matching. 
image
image

**Comment by mcharg** [comment]
@master12 The filters are all disabled for production.
image

**Comment by mcharg** [comment]
Also disabled for disbursements. 
image

**Comment by master12** [comment]
@mcharg Please clear cache and check again. queries have been updated

**Comment by mcharg** [comment]
@master12 The filters are working now. I agree with Maroya that we should get rid of state/offshore region for production, since there aren't any in the data.

**Comment by mcharg** [comment]
@master12 In some scenarios, like this one, it's not grouping by the first column.  I think it might be any time you use the filters.  I tried going back to all commodities and it is no longer grouping.
image

**Comment by Maroyafaied** [comment]
@master12 please remove state/offshore region options off the production monthly. Thanks! 
image

**Comment by Maroyafaied** [comment]
@master12 looks like something went wrong, can you look into it please?

**Comment by master12** [comment]
@Maroyafaied Are you referring to the lint tests? I can clean those up. Is there something else you see as an error?

**Comment by Maroyafaied** [comment]
@master12 the state/offshore filter still is showing up for me.

**Comment by mcharg** [comment]
@Maroyafaied The state/offshore was showing up for me when I first looked at the updates, but it's gone now.

**Review by mcharg — APPROVED** [review]

**Comment by master12** [comment]
@Maroyafaied For Production Monthly?

image

image

**Comment by Maroyafaied** [comment]
@master12 I was seeing it at first but it doesn't show now. Thanks!

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
