### PR TITLE
OGOR B download page and data

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/OGOR-B/downloads)

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@cthomasONRR here is the PR where I added the OGOR B download page, I believe I added everything except the tables displaying the disposition codes, also I believe the download links won't work in this preview and will work once we merge to dev. Feel free to start reviewing until I figure out how to add tables.

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks, I can edit some formatting/spacing/bullets right now.

**Review by cthomasONRR — COMMENTED** [review]
@Maroyafaied  I edited some spacing, bullets, heading, and punctuation issues. I found a webpage that shows how to make tables in markdown (https://www.markdownguide.org/extended-syntax/). Should I try to create the disposition code tables before approving?

**Comment by Maroyafaied** [comment]
@cthomasONRR I also just did a table in a github issue and it's simpler than I thought, yes please go ahead and put the tables. Thanks!

**Comment by cthomasONRR** [comment]
test tables before rebuilding the preview.

Dispositions associated with oil:

| Disposition Code     | Disposition Description |
| ----------- | ----------- |
| 01      | Sales-Royalty Due-Measured       |
| 03   | Load Oil        |
| 04   | Sales-Royalty Due-Not Measured       |
| 05  | Sales-Royalty Not Due, Recovered Injection-Measured      |
| 07   | Condensate Sales-Royalty Due-Measured       |
| 08  | Spilled and/or Lost-Avoidable-Royalty Due      |
| 09  | Sales-Royalty Not Due-Measured       |
| 10   | Produced into Inventory Prior to Sales      |
| 11  | Transferred to Facility    |
| 13  | Transferred from Facility     |
| 14   | Injected on L/A      |
| 15   | Sales-Buy-Back-Measured-Royalty Not Due    |
| 16   | Pipeline Drip/Retrograde Scrubber Production    |
| 20   | Used on L/A-Native Production Only    |
| 23   | Spilled and/or Lost-Unavoidable-Royalty Not Due    |
| 24   | Theft    |
| 25   | Buy-Back Purchased for L/A Use    |
| 26  | Buy-Back-Used on L/A    |
| 29  | Waste Oil/Slop Oil    |
| 33  | Flared Gas - Royalty Due    |
| 42 | Differences/Adjustments   |
| 43  | Sales-Royalty Not Due-FMP Not Assigned    |

Dispositions associated with gas:
| Disposition Code     | Disposition Description |
| ----------- | ----------- |
| 01      | Sales-Royalty Due-Measured       |
| 04   | Sales-Royalty Due-Not Measured       |
| 05  | Sales-Royalty Not Due, Recovered Injection-Measured      |
| 06   | Sales-Non-Hydrocarbon Gas      |
| 08  | Spilled and/or Lost-Avoidable-Royalty Due      |
| 09  | Sales-Royalty Not Due-Measured       |
| 11  | Transferred to Facility    |
| 12  | Transferred to Facility-Returned to L/A   |
| 13  | Transferred from Facility     |
| 14   | Injected on L/A      |
| 15   | Sales-Buy-Back-Measured-Royalty Not Due    |
| 20   | Used on L/A-Native Production Only    |
| 21   | Flared Oil-Well Gas  |
| 22   | Flared Gas-Well Gas    |
| 23   | Spilled and/or Lost-Unavoidable-Royalty Not Due    |
| 24   | Theft    |
| 25   | Buy-Back Purchased for L/A Use    |
| 26  | Buy-Back-Used on L/A    |
| 33  | Flared Gas - Royalty Due    |
| 42 | Differences/Adjustments   |
| 43  | Sales-Royalty Not Due-FMP Not Assigned    |
| 61  | Vented Oil-Well Gas    |
| 62  | Vented Gas-Well Gas   |
| 63  | Vented Gas - Royalty Due    |

**Comment by mcharg** [comment]
There's this tool that makes it easy to convert tables to markdown. https://jakebathman.github.io/Markdown-Table-Generator/

**Comment by cthomasONRR** [comment]
Tables worked in GitHub, but somehow did not translate in Atom Markdown :( In training, will try to troubleshoot soon.

**Pull request closed without merging**
