### PR TITLE
updates June 2020 data

### LINKED ISSUE #642: Update revenue monthly data
upload June 2020 data.

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #642 

[:sunglasses: PREVIEW](https://updaterevenuemonthly.app.cloud.gov/downloads/revenue-by-month/)

Changes proposed in this pull request:

- update June 2020 data, dates and file size

### CODE REVIEW

**Comment by lpgoldstein** [comment]
@Maroyafaied the preview link doesn't work for me.

**Comment by Maroyafaied** [comment]
@lpgoldstein I just checked it and it's working for me. 
https://updaterevenuemonthly.app.cloud.gov/downloads/revenue-by-month/

**Comment by lpgoldstein** [comment]
image
It still doesn't work for me.

**Comment by jennmalcolm** [comment]
@lpgoldstein the preview is working now.

**Pull request merged**
