### PR TITLE
912 collapsable legend

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://preview-nrrd.app.cloud.gov/explore/)

Changes proposed in this pull request:

Hide and show legend added. 

-
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
"Source" column header should say "Revenue type".
image

**Comment by mcharg** [comment]
Nav item is showing up for years where we don't have company data.
image

**Comment by mojobnichols** [comment]
> Nav item is showing up for years where we don't have company data.
> image

I think this is a new issue.   These navigation are not dynmic ... @jlouis-onrr I don't think.   So it's there for fiscal data too.   I could remove it and it will be an easter egg down there.

**Comment by mcharg** [comment]
Created #1005 for the nav issue.

**Review by mcharg — APPROVED** [review]

**Comment by mcharg** [comment]
I could go either way on whether the nav link displays always or never, so I'll leave it to @lpgoldstein or @jennmalcolm to decide whether to hide it.

**Comment by mcharg** [comment]
@jlouis-onrr Can you get the default to CY in before the release?  If we do that, it isn't as big a deal if we show revenue by company always, since it exists for CY.  Defaulting to FY, I think we may need to remove the revenue by company link.

**Pull request merged**
