### PR TITLE
January 2022 Data Uploads

### LINKED ISSUE #1910: Upload & Review September 2021 monthly Production Data

### PR DESCRIPTION
**Pull request by cthomasONRR**
Fixes #1910 #1911 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Jan-22-data-uploads/)

Changes proposed in this pull request:

- December 2021 monthly Revenue
- September 2021 monthly Production
-

### CODE REVIEW

**Comment by cthomasONRR** [comment]
**Revenue Monthly** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout Commodity
 
Homepage - Source File
- [ ] Check source file links are correct.
 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [ ] One Land Type filter
   - [ ] One Revenue Type filter
   - [ ] One State (for Yearly data only)
   - [ ] One Offshore Region
   - [ ] One to three Commodities
   - [ ] Clear All and change grouping
   - [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
**Production Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Source File
- [ ] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Land Type filter
- [ ] One to three Products
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
**Production Calendar Year or Fiscal Year**
	
- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Explore Data - Map and Detail Card 
- Select a year and select a state with data, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected
 
- Select a year and select a county with data, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected.
 
- Select a year and select an offshore area, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected.
 
- [ ] Select a state and county without data and verify the expected information is displayed.
- [ ] Add Nationwide Federal Card and verify the expected information is displayed.
- [ ] Add Native American Card and verify the expected information is displayed.

Explore Data - Nationwide Production Summary and Top Nationwide Locations
- Verify breakdowns by production type and source are correct as well nationwide locations for the conditions below.
    - [ ] Not current Calendar Year
    - [ ] Current Calendar Year
    - [ ] Not current Fiscal Year
    - [ ] Current Fiscal Year

Query Data, in the 'Period' category, filter to either 'Calendar Year' or 'Fiscal Year' and check the following:
- [ ] One Land Type filter
- [ ] One State
- [ ] One Offshore Region
- [ ] One to three Product
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by cthomasONRR** [comment]
@Maroyafaied @mojobnichols 

For the NRRD Homepage, Production - Monthly - Fiscal Year did NOT update from FY 2020 to FY 2021:
image

Interestingly, Production - Yearly - Fiscal Year DID update for FY 2021:
image

**Comment by cthomasONRR** [comment]
@Maroyafaied @mojobnichols 

The Fiscal Year Production Excel also did not update to include FY 2021:
image

**Comment by cthomasONRR** [comment]
@Maroyafaied @mojobnichols 

Explore Data also did not update to include Fiscal Year 2021:
image

**Comment by cthomasONRR** [comment]
@lpgoldstein There are issues with Production FY 2021 not updating, but Revenue looks good to me! If you have time, could you do a second look over Revenue, both monthly and CY 2021? Thanks!

**Comment by lpgoldstein** [comment]
@cthomasONRR revenue looks good for both month and calendar year

**Comment by Maroyafaied** [comment]
@cthomasONRR @mojobnichols This is the monthly production file, so the only graphics on the site that should update is the homepage graphics. Everything on explore data and query tool updates from the annual files not monthly since monthly only has 3 commodities.

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein @Baymatt @kjgdata
Mojo fixed the bug in the Production homepage visualization! I completed my check and everything looks good, but would love some extra eyes on it. Please review! Thanks!

**Comment by Maroyafaied** [comment]
@cthomasONRR can you update this to 2021 for CY revenue in the download page. Otherwise data looks good. 
image

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
