### PR TITLE
1778 download pages

### LINKED ISSUE #1778: Update fields & definitions for all the data sets download pages
Make sure the fields are still relevant and matching the download file. For example, in the production monthly download page we have a field for Month and Calendar Year but those fields now are consolidated into "Date".

### PR DESCRIPTION
**Pull request by rawaaziz1**
Fixes #1778

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1778-DownloadPages/downloads/revenue/)

Changes proposed in this pull request:

-Updated definitions page and download page for disbursements and monthly production and revenue.

### CODE REVIEW

**Comment by Baymatt** [comment]
Fixed some of the inconsistencies on both of the production pages. For the yearly production page, I left the Mixed Exploratory definition there because it occurs in the yearly data but I couldn't find any instances of it in the monthly file so I didn't include it on the monthly page. Please let me know if I should also add it to the monthly page for consistency. 

Will take a look at the revenue pages and the respective comments tonight.

**Comment by Maroyafaied** [comment]
I get an error when I try to use the preview link. 
image

**Comment by lpgoldstein** [comment]
@jlouis-onrr Can you help figure out why the preview link doesn't work anymore?

**Comment by Maroyafaied** [comment]
@Baymatt "Not tied to a lease" is not in the monthly file and should be taken out. And you don't need to add mixed exploratory in the monthly production download file since it's not in the data. Let me know when revenue and disbursement pages are ready for review. Thanks
image

**Comment by Baymatt** [comment]
Added Offshore Region to the revenue page and removed "Not Tied to a Lease" from the monthly production page. @Maroyafaied @lpgoldstein Revenue is ready for review.

**Comment by lpgoldstein** [comment]
@Maroyafaied This is ready for your review

**Review by lpgoldstein — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@lpgoldstein in the monthly disbursement can you take out "dollar" and for the fiscal year disbursement can you change "Total" to "Disbursement". Also in fiscal year disbursement, can you take off "GOMESA" under source and change "Offshore-GOMESA" to "GOMESA-Offshore".  The rest of the pages look good, Thanks.

image
image
image

**Comment by lpgoldstein** [comment]
@Maroyafaied I fixed those last few items and it's ready for your review.

**Comment by Maroyafaied** [comment]
@lpgoldstein looks good, thanks.

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
