### PR TITLE
What's new and version 

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release-change6.5.0/)

Changes proposed in this pull request:

- updated what's new and version
- fixed historical revenue and disbursement links

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@mcharg @cthomasONRR please check the what's new section and I also fixed the links for historical revenue and disbursements in this PR.

**Comment by cthomasONRR** [comment]
@Maroyafaied December 2021 Disbursements are not included in this yet, correct?

**Comment by cthomasONRR** [comment]
@Maroyafaied Historical Disbursements CSV file gives me a 404 error.

**Comment by Maroyafaied** [comment]
@cthomasONRR I corrected the csv disbursement file but it's not done building yet.

**Comment by Maroyafaied** [comment]
@cthomasONRR when it's done building the database should also update and show the Dec disbursements data.

**Comment by Maroyafaied** [comment]
@mojobnichols why doesn't the dec disbursements data show in this PR, I merged it with dev. I'm afraid when I merge this PR it'll override the dec data in dev.

**Comment by mcharg** [comment]
@Maroyafaied The link to the disbursements download file isn't scrolling to the disbursements section.  I think you might need to remove the / at the end of the url.

**Comment by mcharg** [comment]
The rest of what's new looks good.

**Comment by cthomasONRR** [comment]
@Maroyafaied Historical links work, but I'm not seeing Dec 21 Disbursements

**Pull request closed without merging**
