### PR TITLE
Explore data url param state management

### LINKED ISSUE #173: SEO For state links in ExploreData component
Make SEO work on state links

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #173, #584, #613, #617, #633, #592, #410, #444  - - 
[:sunglasses: PREVIEW](https://173-seoforstatelinks.app.cloud.gov/explore)

Changes proposed in this pull request:

- merges in #561 to integrate with explore data toolbar
- adds gatsby-plugin-use-query-params
- adds url params for explore data state management
- uses fips_codes for location lookup via params
- small styling enhancements to toolbar
- SEO updates for all state redirects
- adds explore data toolbar styling to base toolbar component
- resolves silent errors in RevenueTrends and DisbursementTrends components that were preventing IE to render gatsby build
- adds BrowserBanner component for showing IE message to users to warn them to stop using that crappy browser
- adds styling to make query tool year slider similar to explore data

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr What should be working on the query tool from merging in #561?  The drop-downs still aren't using the select all/none pattern from Explore Data and the county drop-down label is overlapping the control.
image

**Comment by mcharg** [comment]
@jlouis-onrr What things should work with the url?  Should we be able to pick some states and then copy and paste the url into a new browser and have the states appear?

**Comment by jlouis-onrr** [comment]
@mcharg, It should be dataType, location, mapLevel, commodities and counties.  For each dataType the state of explore data should reload to what the url params are set to, like(the following link is commodity gas, for CO and NM, wtih offshore selected): 
https://173-seoforstatelinks.app.cloud.gov/explore?commodity=Gas&counties=state&dataType=Revenue&location=35%2C08&offshoreRegions=1&period=Fiscal%20year

**Comment by mcharg** [comment]
@jlouis-onrr I liked the way we had select all/none before better.

**Comment by mcharg** [comment]
@jlouis-onrr The url isn't quite working as expected.  I copied and pasted the url after picking some cards and it didn't match.

First window:
image

Second window (nationwide card is missing and it turned on offshore regions):
image

**Comment by mcharg** [comment]
@jlouis-onrr I tested adding the Native American card and that didn't come over the the new window either, so I think you need to add both that and nationwide to the parameters.

**Comment by mcharg** [comment]
It's working the same for Production and Disbursements and the commodity selection is working.

**Comment by mcharg** [comment]
On How It Works, can you add redirects when you have the year (2013-2018) appended for revenue by company?  The link from the main page had the year, so we need redirects for those.
https://revenuedata.doi.gov/how-it-works/federal-revenue-by-company/2018/

**Comment by mcharg** [comment]
@jlouis-onrr I'm getting a graphql error in place of the revenue type circle charts.
image

**Comment by mcharg** [comment]
On Explore More, revenue by company is going to a 404 error page.  We should remove it until we get that data on the site. 
image

**Comment by mcharg** [comment]
Not sure if this will be moot after merging with @master12's PR, but when I click on the query disbursements link from explore data, it brings up the query tool filtered to disbursements, but the data type drop-down is missing.
image

**Comment by mcharg** [comment]
The How Revenue Works link should go to this page: https://173-seoforstatelinks.app.cloud.gov/how-revenue-works/revenues

**Comment by mcharg** [comment]
The tabs should probably be sentence case to be consistent with our primary nav tabs.
image

**Comment by jlouis-onrr** [comment]
> @jlouis-onrr I'm getting a graphql error in place of the revenue type circle charts.
> image

@mcharg, I believe this is happening because im connecting to the sandbox env, going to check this out and switch the branch to dev

**Comment by jennmalcolm** [comment]
@jlouis-onrr when I changed commodities a couple times and then went to none and clicked on the map, the commodity label overlaps the "none selected."
image


Also, can you look at all the conflicts so that we can merge today hopefully.

**Pull request merged**
