### PR TITLE
1519 query tool aggregation

### LINKED ISSUE #1519: Query tool aggregation

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #1519
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1519-QueryToolAggregation/query-data)

Changes proposed in this pull request:

Modified query tool to use server side aggregation for revenue

Put production into materialized view. 

-
-
-

### CODE REVIEW

**Comment by mojobnichols** [comment]
@jlouis-onrr I addded you because maybe this can be the start of how to get good timings - The query tool is definitely faster for revenue, but being able to measure it would be good.

@Maroyafaied and @daniel-coleman-1  - The data includes the monthly data but aggregation if not done right could double or even triple numbers so a thorough check that data is the same as the new monthly data would be good.

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@mojobnichols the data is accurate but it's not doing subtotal anymore, is that intentional ? 
image

**Comment by mojobnichols** [comment]
> @mojobnichols the data is accurate but it's not doing subtotal anymore, is that intentional ?
> image


I am so thoroughly confused.   I see subtotals  in my PR but I don't see sub totals on revenuedata
 
image

**Review by Maroyafaied — APPROVED** [review]

**Comment by mojobnichols** [comment]
@jlouis-onrr I found the issues with add column dropdown.  You can review at this point.

**Pull request merged**
