### PR TITLE
1318 loading status

### LINKED ISSUE #1318: Fix Loading status indicator

### PR DESCRIPTION
**Pull request by master12**
Fixes #1318 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1318-loading-status/)

Changes proposed in this pull request:

- Added skeleton for Query tool table
- Added skeleton for Drop downs and Year slider
-

### CODE REVIEW

**Review by jlouis-onrr — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@master12 why is month showing up in column 1 for production? 
image

**Comment by Maroyafaied** [comment]
@master12 it's showing up for disbursements as well. 
image

**Comment by master12** [comment]
@Maroyafaied I will fix this issue in the other PR for the commodity. If there are no other issues with this please approve and merge and I will address the month in the drop downs in the other PR

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@master12 Thanks, looks good.

**Pull request merged**
