### PR TITLE
OGOR B publication Jan 2003 - June 2022

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/DispOGORB/downloads)

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@cthomasONRR Please review the OGOR B download page, I think the files won't download until I merge them to dev.

**Comment by Maroyafaied** [comment]
@cthomasONRR Thanks for catching that, I realized that the branch is not pulling June's production data so I'll have to see why before I merge to dev.

**Comment by cthomasONRR** [comment]
@Maroyafaied Since the June data is only in dev, I think once you merge OGOR in dev, we should be able to see both together.

**Comment by Maroyafaied** [comment]
@cthomasONRR if I merge this it'll override what's in dev now so I have to make this match what's in dev before merging.

**Comment by Maroyafaied** [comment]
@cthomasONRR The branch should be updated now with June's production data, and I've added a period where you noted,  please review again. Thanks

**Comment by cthomasONRR** [comment]
@Maroyafaied 

Looks good! I see the June production data (all looks good with it) and see the text update in the OGOR section.

**Review by cthomasONRR — APPROVED** [review]

**Pull request merged**
