### PR TITLE
fixed county map scale in production

### LINKED ISSUE #1189: Production county map scale problem
Sizes are vastly different. This is CO and OK cards next to each other in production.

image

They look ok in revenue

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #1189
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1189-ProductionCountyMapScale/explore?dataType=Production&location=NF%2CCO%2COK&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2019)

Changes proposed in this pull request:

Fixed scale of county maps.

-
-
-

### CODE REVIEW

**Comment by mojobnichols** [comment]
Jerome please review the main thing that fixed the scale was adding height: 250px to ExploreData/Production/CountyProductionMap.js    As was done for Revenue County map.   Is there a better way then adding fixed height?

**Review by jennmalcolm — APPROVED** [review]
Looks good to me.

**Comment by jlouis-onrr** [comment]
@mojobnichols, the controls are not being suppressed by the map in the cards.  I'm seeing them appear at the bottom of the screen.  Other than that it looks good.

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@mojobnichols do you need to address what Jerome mentioned in his comment above before I merge?

**Pull request merged**
