### PR TITLE
National Parks and Public Land Restoration Fund

### LINKED ISSUE #919: Add more context around Great American Outdoors Act
Aside from LWCF funding, the Great American Outdoors Act specifies that 50% (up to $1.9B) now going to General Treasury from energy development will be going to the National Parks and Public Land Legacy Restoration Fund starting in FY21.

We should consider adding more context around this law in How revenues work/disbursements.

image

Here's the link to the Act:

https://www.congress.gov/bill/116th-congress/house-bill/1957

### PR DESCRIPTION
**Pull request by jennmalcolm**
Fixes #919 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/NPPLLRF/how-revenue-works)

Changes proposed in this pull request:

- adds page for NPPLLRF in how revenue works
- adds NPPLLRF to how revenue works index page

This is a start for the NPPLLRF page. I want to add a list of 2021 projects, but I haven't found it yet. It's not due to congress until 90 days after the bill was signed, so that was this week. I haven't found the list yet, but I will do more looking, and if I don't find it, I might link to this list of eligible projects from NPS https://npgallery.nps.gov/GetAsset/589145f1-b816-483f-983f-676296f8f8a1/original.

### CODE REVIEW

**Review by Maroyafaied — APPROVED** [review]

**Review by lpgoldstein — APPROVED** [review]

**Comment by jennmalcolm** [comment]
@lpgoldstein and @Maroyafaied I made a couple updates to clarify how the funding works and add the NPS link. Could one of you take a quick look before merging?

**Comment by lpgoldstein** [comment]
image

Just found a typo - otherwise it looks good

**Comment by Maroyafaied** [comment]
@jennmalcolm sorry just saw another typo 
image

**Comment by jennmalcolm** [comment]
@Maroyafaied I think that sentence sounds ok without the "of". What if I just added a comma like "the maximum, $1.9 billion" or reordered and said "$1.9 billion, the maximum"?

Do you like either of those better?

**Comment by Maroyafaied** [comment]
@jennmalcolm I trust your English grammar more than mine , just leave it as it is.

**Pull request merged**
