### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- Added cents to query tool
- Added query tool links under county maps & offshore production query links to production overtime
- Fixed county map scaled in explore data production
- Fixed query tool sort arrows and added sort arrows for grouping & breakout
- HPF content updated
- Fixed links from content audit
- Fixed how it works revenue background images and tab navigations

**- Updated monthly revenue data December 2020**
 _**Homepage**_ 
- [x] Revenue trends line chart 
- [x] CY bar charts 
- [x] FY bar charts 
- [x] Monthly bar charts 
- [x] Source links 
_**Download Page**_ 
- [x] xls and csv files updated with correct dates and file size

**- Updated monthly production data September 2020**
_**Homepage**_
- [x] Monthly bar charts
- [x] CY bar charts
- [x] FY bar charts
- [x] Source file links
_**Query Data**_ 
- [x] Land type filter 
- [x] State/Offshore region filter 
- [x] County filter 
- [x] Commodity filter 
- [x] Grouping 
- [x] Change between fiscal and calendar year and change years 
- [x] Download matches selected data 
_**Download**_
- [x] xls and csv files updated with correct dates and file size

**- Updated monthly disbursements data November 2020**
_**Homepage**_	
- [x] disbursement trends line charts 
- [x] monthly bar charts 
- [x] FY bar charts 
- [x] Source file links
_**Query Data**_
- [x] Recipient Filter 
- [x] Source Filter 
- [x] State/offshore region filter 
- [x] Grouping 
- [x] Download matches selected data 
_**Download**_
- [x] xls and csv files updated with correct dates and file size

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@lpgoldstein @jennmalcolm I added the query tool on the checklist for monthly production and disbursements.

**Comment by mcharg** [comment]
Are there not supposed to be cents in the query tool for production?

**Comment by jennmalcolm** [comment]
@mcharg production files only have whole units--no decimals.

**Review by mcharg — APPROVED** [review]

**Comment by lpgoldstein** [comment]
state offshore filter in production query tool changed from previous version - location is now lower case and there is a period at the end. 
image

**Review by jennmalcolm — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@lpgoldstein that change was due to this issue for Native American https://github.com/ONRR/nrrd/issues/860

**Comment by jennmalcolm** [comment]
I do agree with Lindsay that "location" should be capitalized and the period should be removed.

**Comment by Maroyafaied** [comment]
@lpgoldstein looks like Mojo fixed it.

**Review by lpgoldstein — APPROVED** [review]

**Review by master12 — APPROVED** [review]

**Comment by jlouis-onrr** [comment]
@master12, @Maroyafaied  looks good to me.  I did notice the following.  Don't think its a show stopper, but should be addressed at some point. See attached.
extra_margin_spacing_issues_on_how_revenue_works_bg_pages

**Review by jlouis-onrr — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@jlouis-onrr I'm not seeing that issue on my computer, but can you make an issue for it incase others are seeing it? Thanks

**Pull request merged**
