### PR TITLE
Optimize Revenue By Company for mobile

### LINKED ISSUE #1081: Optimize Revenue by Company for mobile
It's currently horizontally scrolling.  We should do what we did with the other horizontal bar charts where it turns into stacked cards.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #1081, #1082

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1081-OptimizeRevenueByCompany/explore)

Changes proposed in this pull request:

- optimizes RevenueByCompany component for mobile
- styles cleanup
-

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr Can you please right align the dollar amount and percent for the company?
image

**Comment by mcharg** [comment]
And for the totals:
image

**Comment by mcharg** [comment]
Is it possible to switch to the cards sooner, so we don't ever end up with horizontal scrolling?  This is 600 px.
image

**Comment by mcharg** [comment]
@jlouis-onrr Can you add an underline on the show/hide details link, so we have an indicator other than color that it's clickable?
image

**Comment by mcharg** [comment]
The link to the query tool is missing in the mobile view.
image

**Review by mcharg — APPROVED** [review]

**Review by lpgoldstein — APPROVED** [review]

**Pull request merged**
