### PR TITLE
Fixed sort arrows and added for grouping and breakout

### LINKED ISSUE #1217: Sort arrows aren't working in the query tool
When I click on them nothing happens both on the live site and in dev.

### PR DESCRIPTION
**Pull request by master12**
Fixes #1217 #892

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1217-sort-arrows/query-data/)

Changes proposed in this pull request:

- Fixed sort buttons
- Added sort for grouping and breakout columns
-

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@master12 I'm a bit confused on what the month sort is doing, is it supposed to list months in order or is it sorting months by value?

**Comment by master12** [comment]
@Maroyafaied sorting months Alphabetically not my calendar order. I can try and add a custom sort for that column.

**Comment by Maroyafaied** [comment]
@master12 ya I was expecting it to sort by calendar year order not alphabetically. @mcharg do you know if there is a user preference?

**Comment by mcharg** [comment]
I would guess by calendar year order is probably more expected.

**Comment by Maroyafaied** [comment]
@master12 If you can try to do a custom sort for the column that would be great, if it's too complicated then we can wait and ask about it in user interviews.

**Comment by Maroyafaied** [comment]
@master12 looks like the monthly sort build failed.

**Comment by master12** [comment]
@Maroyafaied the build is good now

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
