### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

- **Added blog post (Sarah's onboarding)**
- **Updated coloring/patterns for charts**
- **Streamline site header**
- **Accessible legend swatches, sliders, toggles and switch controls**
- **Bug fixes**
- **Removed download link from footer**
- **Enhancements to explore data** (tooltips to bar charts, nationwide card open by default, clarify difference between compare & nationwide, etc.
- **Page about National Parks and Public Land Restoration Fund**
- **Updated monthly production (June & July 2020)**
- [x] Homepage
- [x] Monthly bar charts
- [x] CY bar charts
- [x] FY bar charts
- [x] Source file links
- [x] Download Page
- [x] xls and csv files updated with correct dates and file size

### CODE REVIEW

**Comment by mcharg** [comment]
Blog post isn't showing up.
image

**Comment by jennmalcolm** [comment]
spark lines should go through FY2020 
image

**Comment by lpgoldstein** [comment]
csv file size is off in monthly revenue file - says 506 - should be 530

**Comment by lpgoldstein** [comment]
Nationwide Federal card shouldn't display Native American data 
image

**Comment by Maroyafaied** [comment]
@master12 @mojobnichols disbursement data for FY 20 doesn't show data in the query tool. 
image

**Comment by Maroyafaied** [comment]
disbursement overtime trend line is not displaying FY20 data and time line is not displaying correctly as you hover over. 
image

**Comment by jennmalcolm** [comment]
In line with what @lpgoldstein mentioned, the onshore numbers on the detailed cards have Native American numbers in there. This is problem on the live site already. 
image

**Comment by mcharg** [comment]
@jennmalcolm Do we normally link directly to the blog post instead of the blog homepage from What's New?

**Comment by jennmalcolm** [comment]
I usually do link to the blog post @mcharg, but I didn't think it was a big deal when I reviewed the release changes PR.

**Review by mcharg — APPROVED** [review]
All functionality is working.  I checked Chrome, iPhone Safari, Edge, Firefox, and IE and looked at several breakpoints in Chrome.

**Comment by Maroyafaied** [comment]
Here's another checklist for disbursement data @lpgoldstein @jennmalcolm 
hanges proposed in this pull request:
- **Added FY 20 annual disbursement data**
- [ ] Explore data Page
- [ ] Switch between state and county 
- [ ] Fiscal Year Period 
- [ ] Add Nationwide federal card 
- [ ] Add Native American Card 
- [ ] Select different years 
- [ ] Data displaying correct FY  
- [ ] Summary Cards: correct state title, correct county & state title, trendline, accurate year, top recipient data 
- [ ] Nationwide Federal Card:  % of federal land, total disbursements for specified year, trendline, accurate year, disbursement by recipient data 
- [ ] Detailed state cards: % of federal land, total disbursements for specified year, correct state title, trendline, total disbursement for specified year, disbursement by recipient data 
- [ ] Detailed county cards: correct county & state title, total disbursement for specified year, trendline, accurate year 
- [ ] Native American card: total disbursement for specified year, trendline, accurate year 
- [ ] Check cards for states with no data 
- [ ] Disbursements over time trend line data 
- [ ] Nationwide disbursement summary bar chart data 
- [ ] Top Nationwide recipients data 
- [ ] Query Data 
- [ ] Recipient Filter 
- [ ] Source Filter 
- [ ] State/offshore region filter 
- [ ] Grouping 
- [ ] Download matches selected data 

- **Updated monthly disbursement (Sept 2020)**
- [ ] Homepage	
- [ ] disbursement trends line charts 
- [ ] monthly bar charts 
- [ ] FY bar charts 
- [ ] Source file links
- [ ] Download Page
- [ ] xls and csv files updated with correct dates and file size

**Comment by Maroyafaied** [comment]
@mojobnichols Native American tribes and individuals is missing in the top nationwide recipients 
image

**Comment by Maroyafaied** [comment]
@mojobnichols the LWCF is not adding the GOMESA portion in disbursements by recipient for the nationwide federal card. 
image

**Comment by Maroyafaied** [comment]
@mojobnichols @jlouis-onrr cards with no data are showing up with $0 and a trendline. 
image

**Comment by jennmalcolm** [comment]
@Maroyafaied the trend line you mentioned is the way it was designed when there was data during the period. Tennessee did have $99 in disbursements during some years, but during 2020 it was $0.

**Comment by lpgoldstein** [comment]
California state card for 2020 is missing 8(g)offshore....but not in previous years. Louisiana looks okay though. image
image
image

**Comment by mcharg** [comment]
I'm getting an error when I switch to disbursements on Explore Data.
image

**Comment by mcharg** [comment]
I'm also not seeing the link to the page about the new act on the How Revenue Works page.

**Comment by mcharg** [comment]
Just realized what's happening with the link to the new act page.  The link from what's new is going to the live site instead of the page on the dev site.

**Comment by Maroyafaied** [comment]
@mcharg ya I had it set up that way so when we release , the link should show on the live site. I'm not sure if normally the links that are set to the dev site will automatically change to the live site once we release?

**Comment by mcharg** [comment]
You should be able to put in a relative path, so it always goes to the site you're in.

**Comment by Maroyafaied** [comment]
Query tool is showing a column for FY20 disbursements with blank values. 
image

**Review by mcharg — APPROVED** [review]

**Review by lpgoldstein — APPROVED** [review]

**Review by master12 — APPROVED** [review]

**Review by jlouis-onrr — APPROVED** [review]

**Comment by mojobnichols** [comment]
I ran end to end tests and it explore data failed miserablly but looking into it I think some selector names changed when Jerome update the look and feel.   I checked all the tests there I didn't see anything jump out at me.   I'll have to update the end to end tests to match new selectors. 

etermining test suites to run...Setup Puppeteer
Setup Test Environment.
Setup Test Environment.
Setup Test Environment.
Setup Test Environment.
 PASS  __tests__/homepage.disbursements.e2e.js (10.06s)
  Home Page Disbursements: 
    ✓ Yearly Fiscal Disbursements (3380ms)
    ✓ Monthly Most Recent Disbursements (860ms)
    ✓ Monthly Fiscal Disbursements (992ms)
    ✓ Monthly Calendar Disbursements (979ms)
    ✓ Disbursement Trends (631ms)

Teardown Test Environment.
 PASS  __tests__/homepage.revenue.e2e.js (10.988s)
  Home Page Revenue: 
    ✓ Yearly Fiscal Revenue (4245ms)
    ✓ Yearly Calendar Revenue (904ms)
    ✓ Monthly Most Recent Revenue (814ms)
    ✓ Monthly Fiscal Revenue (894ms)
    ✓ Monthly Calendar Revenue (909ms)

Teardown Test Environment.
 PASS  __tests__/homepage.production.e2e.js (18.434s)
  Home Page Disbursements: 
    ✓ Yearly Fiscal Production (10958ms)
    ✓ Yearly Calendar Production (1068ms)
    ✓ Monthly Most Recent Production (1028ms)
    ✓ Monthly Fiscal Production (1096ms)
    ✓ Monthly Calendar Production (1060ms)

Teardown Test Environment.
 FAIL  __tests__/explore_data.e2e.js (394.047s)
  Home Page Revenue: 
    ✕ Explore Data Fiscal Revenue Map (356ms)
    ✕ Explore Data Fiscal Revenue Nationwide Summary (30005ms)
    ✕ Explore Data Fiscal Revenue Top Locations (30030ms)
    ✕ Explore Data Fiscal Revenue Federal Card (6ms)
    ✕ Explore Data Fiscal Revenue Over Time (30022ms)
    ✕ Explore Data Calendar Revenue Over Time (7ms)
    ✕ Explore Data Calendar Revenue Federal Card (30025ms)
    ✕ Explore Data Calendar Revenue Map (30008ms)
    ✕ Explore Data Calendar Revenue Nationwide Summary (30032ms)
    ✕ Explore Data Calendar Revenue Top Locations (30032ms)
    ✕ Explore Data Calendar Revenue By company (30032ms)
    ✕ Explore Data Fiscal Disbursement Nationwide Summary (7ms)
    ✕ Explore Data Fiscal Disbursement Top Nationwide recipients (30026ms)
    ✕ Explore Data Fiscal Disbursement Federal Cards (30030ms)
    ✕ Explore Data Fiscal Disbursement Over Time (30031ms)
    ✕ Explore Data Fiscal Production Top Nationwide Locations (5ms)
    ✕ Explore Data Fiscal Production Federal Cards (30024ms)
    ✕ Explore Data Fiscal Production Over Time (30031ms)

**Review by mojobnichols — APPROVED** [review]

**Pull request merged**
