### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

New homepage trends & comparison design

Updated monthly revenue data January 2021
Homepage 
- [ ] Monthly bar charts (most recent 12 months, FY & CY)
- [ ] CY bar charts
- [ ] FY bar charts
- [ ] Check Breakouts (Source & Revenue type, commodity)
- [ ] Check year over year comparison
- [ ] Check month over month comparison
- [ ] Source file links
Download 
- [x] xls and csv files updated with correct dates and file size

Updated monthly production data October 2020
Homepage
- [ ] Monthly bar charts (most recent 12 months, FY & CY)
- [ ] CY bar charts
- [ ] FY bar charts
- [ ] Check all commodities
- [ ] Check year over year comparison
- [ ] Check month over month comparison
- [ ] Source file links
Query Data 
- [ ] Land type filter 
- [ ] State/Offshore region filter 
- [ ] County filter 
- [ ] Commodity filter 
- [ ] Grouping 
- [ ] Change between fiscal and calendar year and change years 
- [ ] Download matches selected data 
Download 
- [x] xls and csv files updated with correct dates and file size

Updated monthly disbursements data December 2020

Homepage	
- [ ] Monthly bar charts (most recent 12 months, FY & CY)
- [ ] CY bar charts
- [ ] FY bar charts
- [ ] Check Breakouts (Source & Recipient)
- [ ] Check year over year comparison
- [ ] Check month over month comparison
- [ ] Source file links
Query Data 
- [ ] Recipient Filter 
- [ ] Source Filter 
- [ ] State/offshore region filter 
- [ ] Grouping 
- [ ] Download matches selected data 
Download 
- [x] xls and csv files updated with correct dates and file size 

Updated annual production data FY 2020
Explore Data  
- [x] Switch between state and county 
- [ ] Show offshore 
- [x] Switch between FY and CY 
- [x] Choose different commodities 
- [x] Add Nationwide federal card 
- [x] Add Native American Card 
- [x] Select different commodities 
- [x] Select different years, correct FY or CY displaying 
- [x] Summary Cards: correct state title, correct county & state title, trendline, accurate year, correct abbreviation for commodity selected 
- [ ] Nationwide Federal Card:  % of federal land, total production for specified year,  trendline, accurate year, production over time trendline data, top locations data 
- [ ] Detailed state cards: % of federal land, total production for specified year, correct state title, trendline, total production for specified year, top county data, counties map 
- [ ] Detailed county cards: correct county & state title, total production for specified year, trendline, accurate year, production overtimes trendline 
- [ ] Native American card: total production for specified year, trendline, accurate year, production overtime trendline 
- [ ] Offshore card: total production for specified year, trendline, accurate year, production overtime trendline 
- [ ] Check cards for states with no data 
- [ ] Production over time trend line data 
- [ ] Top Nationwide locations data 
Query Data 
- [x] Land type filter 
- [ ] State/Offshore region filter 
- [x] County filter 
- [ ] Commodity filter 
- [x] Grouping 
- [x] Change between fiscal and calendar year and change years 
- [x] Download matches selected data 
Download  
- [x] xls and csv files updated with correct dates and file size

Updated Coal Excise Tax

Blog post about trends design studio

Added commodity for monthly disbursement query

Enhancements to query tool

Enhancement to pattern library

Enhanced loading status

Fixed horizontal nav menu

### CODE REVIEW

**Comment by lpgoldstein** [comment]
@jennmalcolm I'll start with disbursements data

**Comment by jennmalcolm** [comment]
Ok @lpgoldstein but I don't think we should review the homepage yet since the trends PR isn't merged yet. I will review the FY production data.

**Comment by lpgoldstein** [comment]
@jennmalcolm seeing that now. Will check download pages then.

**Comment by Maroyafaied** [comment]
Yes, please wait on reviewing the homepage. You can review the query tool and explore data.

**Comment by jennmalcolm** [comment]
FY2020 production data is coming through on the query tool, but giving an error on explore data. 
image

**Comment by Maroyafaied** [comment]
@jennmalcolm I just tried and it's working for me. 
image

**Comment by lpgoldstein** [comment]
@jennmalcolm It's working for me too.

**Comment by lpgoldstein** [comment]
image
 Confirming that the summary cards don't have product/commodity name listed on them - just units? The live site doesn't have it either.

**Comment by jennmalcolm** [comment]
@lpgoldstein that's correct. We do have #751 to address more labels for applied filters.

**Comment by jennmalcolm** [comment]
The production data is now coming through for me. Can we default to 2020? It's going to 2019 when it loads now.

**Comment by mcharg** [comment]
Is there a reason why there are no cents on the production data in the query tool?

**Comment by mcharg** [comment]
Nevermind, just remembered it's not dollars...

**Comment by lpgoldstein** [comment]
fy production data not coming through for me now in explore data
image

**Comment by jennmalcolm** [comment]
@mojobnichols FY2020 production filters don't have our offshore regions--only one thing saying "offshore offshore gulf undefined."

image

Since old data had separate offshore planning area field, that's probably where the issue came in loading this new data, but there is a offshore region field, so we still should have those.

**Comment by Maroyafaied** [comment]
I set this up wrong so I'm closing it and creating another one.

**Pull request closed without merging**
