### PR TITLE
Fix for line charts

### LINKED ISSUE #998: Line chart is broken in dev
It broke when the card color PR was merged.  Adding multiple cards doesn't add them all to the line chart.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #998

[:sunglasses: PREVIEW](https://preview-nrrd.app.cloud.gov/explore/)

Changes proposed in this pull request:

- fixes bug introduced with line chart color updates
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr Still broken.
image

**Comment by jlouis-onrr** [comment]
@mcharg, still working on it...

**Comment by jlouis-onrr** [comment]
@mcharg, try it now

**Review by mcharg — APPROVED** [review]
It's working now!

**Review by jennmalcolm — APPROVED** [review]
Looks good

**Review by mojobnichols — APPROVED** [review]
Looks good - I don't know if this was part of this or not but the summary cards sitll don't keep there order.   I think they should.

**Pull request merged**
