### PR TITLE
update what's new and version

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<PUT ISSUE NUM HERE>

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release6.7.0/)

Changes proposed in this pull request:

- Update what's new section
- Update version

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@cthomasONRR @eelzi-ONRR This PR is ready for your review. Just FYI, I changed the version to 6.7.0 instead of 6.6.10 because we are releasing new "features" such as the OGOR B data sets and adding the new VDP webpage.

**Comment by cthomasONRR** [comment]
@Maroyafaied I tested the OGOR-B download links here, and I got the 404 error... the monthly production link works.

**Comment by eelzi-ONRR** [comment]
Looks good - no errors or bad links found on this preview page.

**Comment by Maroyafaied** [comment]
@cthomasONRR those links won't work in preview, they will work in dev.

**Comment by Maroyafaied** [comment]
@cthomasONRR @eelzi-ONRR Thanks for reviewing, please mark as approved and I will merge it to the development site. Thanks

**Review by eelzi-ONRR — APPROVED** [review]
Looks good - no errors or bad links found on this preview page.

**Review by cthomasONRR — APPROVED** [review]
Looks good- I'll be sure to double-check dev!

**Pull request merged**
