### PR TITLE
595 cy production data

### LINKED ISSUE #595: Add CY production data to Explore Data page

### PR DESCRIPTION
**Pull request by mojobnichols**
Fixes #595 

[:sunglasses: PREVIEW](https://595-CyProductionData.app.cloud.gov/explore/)

Changes proposed in this pull request:

Explore data production has option for CY data

-
-
-

### CODE REVIEW

**Comment by lpgoldstein** [comment]
@mojobnichols The data looks good - I checked several states and years for coal, gas and oil and was able to switch easily between all of those options, but then the cards get stuck on coal after about 20 switches between states, counties, years, and commodities after I added the Native American Card

**Comment by lpgoldstein** [comment]
image

**Comment by lpgoldstein** [comment]
We should note that we don't have the data in this data set not that Native American doesn't have any production
image

**Comment by jennmalcolm** [comment]
@mojobnichols do you want separate issues for the items @lpgoldstein noted above?

**Comment by Maroyafaied** [comment]
@mojobnichols the number on the detailed state card and the trendline don't match. Also, I'm getting different numbers for some of the data. And counties are not listed under the state card, it seems like it's listing what the nationwide card is supposed to have.  And there's a few areas where units are missing. I took screen shots of the things I've mentioned. Thanks

image
image
image

**Comment by Maroyafaied** [comment]
@mojobnichols I checked this again, the data is correct but there is still the issues I mentioned above ( trendline not matching, counties not listed under state cards, and units missing in some places) Thanks!

**Comment by mojobnichols** [comment]
@Maroyafaied I belive I have corrected all the issues you have above in PR https://github.com/ONRR/nrrd/pull/637

Thanks

Mojo

**Comment by Maroyafaied** [comment]
@mojobnichols Here are the issues I found;
1. Production trend charts shows the wrong data, it was showing data for oil when gas data is supposed to be displayed,
2. Production trend chart does not show up for counties.
image

**Comment by jennmalcolm** [comment]
I see that the San Juan County, CO line graph is there, but it doesn't look correct. Its just a straight line, when all of the years were zero except 2018 and 2019. 
image

**Comment by jennmalcolm** [comment]
Here's another example of a line graph looking weird. 2006-2010 are all zeros, but they don't look like it. 
image

**Comment by Maroyafaied** [comment]
@mojobnichols there's an error message on the bottom of the offshore cards 
image

**Comment by mojobnichols** [comment]
@Maroyafaied I fixed the graphql error in offshore.  I also resloved conflicts.   Hopefully that is the last thing thank you for the very thorough testing.

**Comment by jennmalcolm** [comment]
@mojobnichols the Native American card says that there was no oil produced since 2003. We do actually have CY Native American production data. It didn't come in the same file as the federal, but we have it now. I'm attaching the data, and I'll create a separate issue to get the files updated. Do you want me to create a separate issue to get this in the database? Also, do you have a lookup table for the units, or should we correct the file to have the units for all of the products? It is missing a lot.
[CY Native American Production Volumes.xlsx](https://github.com/ONRR/nrrd/files/4961243/CY.Native.American.Production.Volumes.xlsx)

If it's best to create a separate issue to update the Native American data, could you at least change the wording for the Native American cards to "no data" because what's on there now is technically inaccurate?

image

**Comment by Maroyafaied** [comment]
@mojobnichols for the nationwide card , there is a production by county map icon that shows up.
image

**Comment by Maroyafaied** [comment]
@mojobnichols I just finished reviewing and here's the issues I found, I labeled my picture according to the numbers below.

1. The colors on the circle charts and the table labels don't match for counties. It seems like this happens where there is 2 or less counties with productions. 
2. When a state has no production for a commodity, top locations shouldn't show up but they do and it looks weird.
3. There is a production by county map icon at the bottom of the nationwide card.  

image

**Comment by mojobnichols** [comment]
I fixed 2 and 3.   1 looks like a bug in current circle chart when it has two items.   Let's open p1 ticket  for that.

**Comment by Maroyafaied** [comment]
@mojobnichols looks like items 2&3 are fixed but it seems like top locations don't show up on the nationwide card anymore. 
image

**Pull request merged**
