### PR TITLE
Stylizes Explore Data

### LINKED ISSUE #158: Stylize explore data features
Hey can I get you to style explore data?  Get county moved to right.   I think it needs a little border.  Then I think we need zoom and pan buttons... but that might be easier in d3.   But the pan and zoom prop will come in from url so it will be a prop so maybe just something mui in data-vis/Map is sufficient.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #158

[:sunglasses: PREVIEW](https://158-stylizeexploredata.app.cloud.gov/explore/)

Changes proposed in this pull request:

- Styled explore data page and map
- Map controls
- Legend updates
- Mobile styles
- Good amount of pomade added

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr The map is super zoomed in when I first go to the page. Is it possible to have it fit the whole country in the frame by default?
image

**Comment by mcharg** [comment]
@jlouis-onrr We should use the gray we're using on the homepage for the dot on the trendlines, so we have orange available to use in charts below without having to worry that people will think they're tied together.
image

**Comment by mcharg** [comment]
@jlouis-onrr Can we not use the lighter gray for years after the one selected?  They look disabled.
image

**Comment by mcharg** [comment]
@jlouis-onrr I assume you're still working on mobile, since the cards are still scrolling horizontally and it doesn't let you get down to 320 px  - it stops resizing somewhere above that.  I do think it might be better to switch from the slider to a drop-down than to not have labels on the options on the slider on mobile.

**Comment by jlouis-onrr** [comment]
> @jlouis-onrr I assume you're still working on mobile, since the cards are still scrolling horizontally and it doesn't let you get down to 320 px - it stops resizing somewhere above that. I do think it might be better to switch from the slider to a drop-down than to not have labels on the options on the slider on mobile.

It would be great to try something similar to the following slider, which is a one component solution vs a two component idea you are suggesting.  Any thoughts on a one component solution?

mobile_slider_example

**Comment by jlouis-onrr** [comment]
Heres some more slider inspiration we might be able to gather ideas from?
https://uimovement.com/tag/slider/

**Comment by mcharg** [comment]
@jlouis-onrr I like the slider in your screenshot above.

**Comment by jlouis-onrr** [comment]
@mcharg I do too!  I'll try going that direction with the slider.

**Comment by mcharg** [comment]
@jlouis-onrr The default map sizing and slider are looking good.

**Comment by mcharg** [comment]
@jlouis-onrr I like what you did with the state/county and offshore and the add Native American button.  

I'm not sure the other ways to explore revenue belongs with the other options, since it doesn't control the map.  It feels like it should be treated separately.

**Comment by jlouis-onrr** [comment]
@mcharg I agree...  its up top for now, as that was a quick and easy fix for now.  Ideally it should go somewhere else.  I was thinking maybe to the right above the cards?

**Comment by mcharg** [comment]
@jlouis-onrr I was thinking the same thing.

**Comment by mcharg** [comment]
@jlouis-onrr I like the change to the toggle.  

We may need some sort of label on the speed dial for users to discover what it is.  I'm not sure people will figure out what it does without having to click on it.

**Pull request merged**
