### PR TITLE
Adding components notes

### LINKED ISSUE #1222: Write notes for components in the pattern library

### PR DESCRIPTION
**Pull request by master12**
Fixes #1222 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1222-components-notes/patterns)

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 @arcasarana Links to sample pages aren't coming through.  Do they need to be formatted as html instead of markdown?
image

**Comment by master12** [comment]
> @master12 @arcasarana Links to sample pages aren't coming through. Do they need to be formatted as html instead of markdown?
> image

The links work like markdown. the syntax above is wrong.
[<insert text in brackets>](<insert link/url in parentheses>)

The above only has brackets you need the parentheses

**Comment by mcharg** [comment]
@master12 I added in the parentheses, but my changes appear to be missing.

**Comment by mcharg** [comment]
After several refreshes, my changes showed up.

**Comment by mcharg** [comment]
@master12 Can you please resolve the conflicts?

**Review by arcasarana — APPROVED** [review]
Looks good

**Comment by Maroyafaied** [comment]
@master12  I'm not able to merge this, it has conflicts.

**Pull request merged**
