### PR TITLE
Removed 2020 and default to fewer years

### LINKED ISSUE #357: Don't include incomplete years when the user is viewing yearly data
Right now we're showing 2020, which isn't a full year, so it's not apples to apples.

### PR DESCRIPTION
**Pull request by master12**
Fixes #357 #347

[:sunglasses: PREVIEW](https://357-incomplete-years.app.cloud.gov/query-data)

Changes proposed in this pull request:

- Only show 3 years by default
- Dont show 2020
-

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 The preview link isn't working.

**Comment by mcharg** [comment]
@master12 The link is working now.  Revenue and production look good.  Disbursements is still showing all the years by default.

**Comment by mcharg** [comment]
@master12 The group by drop-downs are now there for disbursements, but they aren't reflected in the table.  This says it's grouped by revenue type and commodity, but those aren't even visible columns. 
image

**Comment by master12** [comment]
Created issue #462 to fix disbursements drop down

**Pull request merged**
