### PR TITLE
Mobile updates and fixes, offshore label and map zoom

### LINKED ISSUE #506: Legend is fixed in the middle of the map on iPhone
It makes it hard to select a state.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #506, #717, #812

[:sunglasses: PREVIEW](https://506-legendfixedinmiddleofmapmobile.app.cloud.gov/explore?dataType=Revenue&mapLevel=State&offshoreRegions=false&period=Fiscal%20Year&year=2019)

Changes proposed in this pull request:

- fixes legend being fixed in middle of map in mobile
- updates minWidth prop for select inputs overflowing each other
- adds glossary icon when offshore is disabled
- adds useWindow custom hook to help resize map zoom for different viewport sizes

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr Is it possible to get the questionmark inline with the text?
image

**Comment by mcharg** [comment]
@jlouis-onrr This is what the map looks like on an iPhone SE.  It's mostly in view, but a lot of it is covered up by the key.
image

**Comment by mcharg** [comment]
The filter drop-downs look good.

**Comment by lpgoldstein** [comment]
@jlouis-onrr glossary looks good.

**Comment by lpgoldstein** [comment]
The map loaded properly on my iphone the first time but started to get wonky once I tried to add cards. The touch screen features didn't seem to work at all for me other than being able to click on what is shown on the screen. I wasn't able to scroll up or down or resize the map. I have an iPhone 11
Screenshot 2020-08-20 at 8 44 02 AM

**Comment by jlouis-onrr** [comment]
@lpgoldstein, I'm seeing the touch issues as well.  Seems they've gone rogue.

**Comment by mcharg** [comment]
@jlouis-onrr Glossary looks good.

**Comment by jlouis-onrr** [comment]
@lpgoldstein, touch zoom is now back.  @mcharg, there are more legend scale updates, should be a bit better on iphone SE

**Comment by jennmalcolm** [comment]
I added #879 for a separate mobile improvement I think would help the experience.

**Pull request merged**
