### PR TITLE
New glossary page

### LINKED ISSUE #1273: Build new glossary page
Design: https://3qh5zb.axshare.com/

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #1273, #1481

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1273-BuildNewGlossaryPage)

Changes proposed in this pull request:

- adds new terms to glossary content partials
- adds categories to glossary terms
- creates new glossary page and components
- adds glossary terms to search index
- adds Glossary to main menu with new breakpoints

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr Can we get the new not tied to a lease term to show up in the charts on the homepage?
image

**Comment by mcharg** [comment]
@jlouis-onrr Can you do some cleanup on the circle charts with the wrapping of the glossary icon?
image

**Comment by mcharg** [comment]
@jlouis-onrr The unit definitions don't have a home on Explore Data.  We should come up with a good place to put them.

Maybe after this big instance on the detail card?
image

**Comment by mcharg** [comment]
The unit definitions also don't show up in the query tool.

**Comment by mcharg** [comment]
The glossary for Other (disbursements recipient) should display any time we show "other funds" for disbursements.
image

**Comment by mcharg** [comment]
Revenue type glossaries aren't showing up on homepage charts.
image

**Comment by mcharg** [comment]
Not tied to a commodity should have a glossary on the homepage
image

**Comment by mcharg** [comment]
Maybe put the units glossary here on the homepage.
image

**Comment by mcharg** [comment]
The glossary page looks good.

**Review by mcharg — APPROVED** [review]

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@jlouis-onrr are you good with me merging this or are you still working in this branch?

**Pull request merged**
