### PR TITLE
Dev-->Master 

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- [x]  **Added Historical revenue by calendar year data from 1982-2002**

- [x] **Updated definition in excel files to match downloads**

- [x] **Reduced Reading level for the following pages (Federal Reforms, Audits & Assurance, Onshore oil & gas, Offshore oil & gas, Historic Preservation Fund, Nonenergy Minerals)**

- [x] **Updated glossary page (title case, sentence, removed terms)**

- [x]  **Updated monthly revenue data (November 2021)**
- [x] Make sure the downloaded data matches the raw data. Raw data saved [here](https://teams.microsoft.com/l/file/C20F89E4-E0E4-48AC-81A0-4988D8C3E526?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=csv&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FRevenue%2FFY%202022%2FNovember%202021%20Revenue%20for%20Portal_CSV_DO%20NOT%20EDIT.csv&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout Commodity
 
Homepage - Source File
- [x] Check source file links are correct.
 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [x] One Land Type filter
   - [x] One Revenue Type filter
   - [x] One State (for Yearly data only)
   - [x] One Offshore Region
   - [x] One to three Commodities
   - [x] Clear All and change grouping
   - [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

- [x] **Updated monthly production data (August 2021)**
- [x] Make sure the downloaded data matches the raw data. Raw data saved [here](https://teams.microsoft.com/l/file/90340495-0D37-4DAC-9C78-90D130903615?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=csv&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FProduction%2FFY%202021%2FProduction%20Volumes%20as%20of%2012-6-2021_CSV_DO%20NOT%20EDIT.csv&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Source File
- [x] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Land Type filter
- [x] One to three Products
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

### CODE REVIEW

**Comment by cthomasONRR** [comment]
I reviewed the monthly revenue and production data- everything looks good there.

@mojobnichols When I try to download the Historical Revenue xls and csv files, I get a 404 error. Could you help us got those files up and available to download? Thanks!

**Comment by Maroyafaied** [comment]
@cthomasONRR it downloads for me.

**Review by mcharg — APPROVED** [review]
Spot checked pages in Chrome, Firefox, and Safari.  All looks good.

**Comment by lpgoldstein** [comment]
so we apparently only have federal revenue by company data for 1970! And there's no data in the download files ... 
image
image
please help @mojobnichols @jlouis-onrr

**Comment by daniel-coleman-1** [comment]
Made two updates to the Glossary page, the edited reading level pages all look good.
Screenshot 2021-12-16 150930
Screenshot 2021-12-16 150847

**Review by daniel-coleman-1 — APPROVED** [review]

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 Can you please change "a number of" to "several"? This should improve reading level in onshore oil and gas.
image

**Comment by daniel-coleman-1** [comment]
@lpgoldstein I've changed "a number of" to "several"

**Comment by mcharg** [comment]
@daniel-coleman-1 Looks like the period you added to the glossary didn't make it in.  Since we're trying to get the release out, let's push this and any other edits to the glossary typos issue for next sprint.  We generally only edit in dev to fix bugs and changes like this should go in a PR and follow that review process anyway.

image

**Comment by daniel-coleman-1** [comment]
@mcharg I removed the period, that's a fragment

**Comment by mcharg** [comment]
@daniel-coleman-1 Then it needs to be rewritten.  We shouldn't have fragments as definitions.  Let's deal with it in the issue for next sprint.

**Comment by daniel-coleman-1** [comment]
@mcharg we have a lot of definitions that are fragments

**Pull request merged**
