### PR TITLE
Update minerals.mdx

### LINKED ISSUE #1801: Reduce Reading Level: how-revenue-works/ownership/
Currently coming in at grade level 12, Split Ownership paragraph comes in at 11 and Natural Resource Ownership comes in at 15.

https://revenuedata.doi.gov/how-revenue-works/ownership/

### LINKED ISSUE #1802: Reduce Reading Level: /how-revenue-works/minerals/
Overall the page comes to 12.

Nonenergy Minerals section comes back as 16.  Plan - 16.  Claim - 13. Explore - 12.  Develop - 14.  Decommission and Reclaim - 11.

### LINKED ISSUE #1803: Reduce Reading Level: how-revenue-works/hpf/
Historic Preservation Fund - 9.  Funding Priorities - 12.  Authorization and funding - 12.  Distribution of funds - 13.

### LINKED ISSUE #1810: Build NRRD Site Map

### LINKED ISSUE #1811: Reduce Reading Level for /how-revenue-works/onshore-oil-gas/
Onshore Oil & Gas - 13.  Plan - 13.  Lease - 11.  Explore - 14.  Develop - 13.  Decommission and reclaim - 15.

### LINKED ISSUE #1812: Reduce Reading Level for /how-revenue-works/audits-and-assurances/
Audits and Assurances - 13.  Tracking and Verifying Payments - 16.  Company Standards and Oversight - Post-graduate.  Federal standards and audits - 14.  Federal revenue reporting - 12.

### PR DESCRIPTION
**Pull request by daniel-coleman-1**
Fixes #1801
Fixes #1802
Fixes #1803
Fixes #1810
Fixes #1811
Fixes #1812

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Glossary-and-reading-level-edits/)

Changes proposed in this pull request:

- [x] Updates Federal Reforms page
- [x] Updated Audits and Assurances page
- [x] Updates Onshore Oil & Gas page
- [x] Updates Offshore Oil & Gas page
- [x] Updates Historic Preservation Fund (HPF) page
- [x] Updates Nonenergy Minerals page
- [x] Corrects sentence/fragment punctuation agreement in glossary definitions
- [x] Shifts glossary terms to title case from sentence case
- [x] Removes the following terms from the glossary:  Civil Society, Gross Domestic Product (GDP), kWh, Variance Floor

### CODE REVIEW

**Comment by daniel-coleman-1** [comment]
@lpgoldstein @Maroyafaied this is now ready to review.

**Comment by lpgoldstein** [comment]
- [ ] Updates Federal Reforms page
- [ ] Updated Audits and Assurances page
- [ ] Updates Onshore Oil & Gas page
- [ ] Updates Offshore Oil & Gas page
- [ ] Updates Historic Preservation Fund (HPF) page
- [ ] Updates Nonenergy Minerals page
- [ ] Corrects sentence/fragment punctuation agreement in glossary definitions
- [ ] Shifts glossary terms to title case from sentence case
- [ ] Removes the following terms from the glossary: Civil Society, Gross Domestic Product (GDP), kWh, Variance Floor

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 this is currently on the live site in the audit and assurance page, there's two "the". 
image

**Comment by lpgoldstein** [comment]
@Maroyafaied I think it's technically correct with both "the" but it doesn't read well. I think it was done on purpose but I like it better without the first one as well.

**Comment by lpgoldstein** [comment]
This period needs to be removed 
image

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 this should say "Fair Market Value" in the offshore oil and gas page. Also since we have fair market value in the glossary, there should be an icon displaying the definition the first time it's mentioned on this page. 

image

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 @lpgoldstein I checked off the pages I reviewed above, I'll check the rest tomorrow morning.

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 Just a quick question - why did you omit the word "process" here? It's in your word doc - just curious 
image

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 Management is missing the "e" on the federal reforms page 
image

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 I think we can delete this sentence on the offshore oil and gas page. Maybe change the word "develop" to "calculate" in the previous sentence? 
image

**Comment by Maroyafaied** [comment]
This sentence in onshore oil and gas page doesn't match what was updated on the word doc 
image

**Comment by Maroyafaied** [comment]
In the onshore oil and gas page , can we change this word back to operation, BLM refers to this as operation not production. Thanks 
image

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 some of the glossary terms are still not in title case. 
image

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I'm done reviewing all the pages, let me know when you've made the changes to address the comments above and I'll review again. Thanks

**Comment by daniel-coleman-1** [comment]
@Maroyafaied  @lpgoldstein thank you for the edits, they've been implemented - but the build failed a check on CircleCI.  Not sure how to resolve.
Lindsay, I think omitting "process" was just a mistake on my part.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1  I rebuild it and it works now. I'll review again.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 This term is still not title case
image

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 This is not ready for review, none of these comments were addressed in your last update. 

image
image

**Comment by daniel-coleman-1** [comment]
@Maroyafaied I've addressed them all, but when I saved I hit "Save" and not "Save All," so I only sent updates to the page I was viewing at the time.  All should reflect updates when checks complete.

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 thanks, reviewed again and approved. @lpgoldstein please review. Thanks

**Review by lpgoldstein — APPROVED** [review]

**Pull request merged**
