### PR TITLE
Adding glossaries 

### LINKED ISSUE #1581: Add glossaries to How Datasets Fit diagram
We now have glossaries for terms that didn't exist when we built it that need to be linked to the glossaries.

### PR DESCRIPTION
**Pull request by cthomasONRR**
Fixes #1581 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Glossaries/)

Changes proposed in this pull request:

Adding new glossaries to specific terms: Inspection Fees, Civil Penalties, Other Revenues

Adding new glossaries to specific terms: US Treasury, Historic Preservation Fund

### CODE REVIEW

**Comment by cthomasONRR** [comment]
I tried to link the "Historic Preservation Fund" glossary, but it is not working.
I also want to know if (or how) we can link glossary terms that aren't exact word matches... For example adding a glossary card for "Native American Lands" even though the glossary term is "Native American"

**Comment by mcharg** [comment]
@cthomasONRR This is the file to set tags for different wordings of glossary terms.

**Review by mcharg — APPROVED** [review]

**Comment by cthomasONRR** [comment]
@jlouis-onrr and @daniel-coleman-1  

This is ready for you two to review.

Thanks!

**Review by jlouis-onrr — APPROVED** [review]

**Review by daniel-coleman-1 — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@cthomasONRR the glossaries look good on the glossary page. @jlouis-onrr can you help with adding these glossaries to the query tool? If it's something a non developer can do then please let us know how to do it during sync up tomorrow. Thanks

**Comment by Maroyafaied** [comment]
@cthomasONRR @jlouis-onrr never mind, it looks like adding it to the glossary page automatically adds it to the query tool and other places on the site.

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
