### PR TITLE
Homepage fixes

### LINKED ISSUE #277: Fix homepage bugs
- [x] Add "Production by location" link to Explore Data page (defaulted to oil)
- [x] Add source file links
- [x] Add the word "Total" before Revenue , Disbursement and Production data.
- [x] Units are missing for the commodities in the production tab on the horizontal max line and by the year in the table below.

### PR DESCRIPTION
**Pull request by jlouis-onrr**
Fixes #277, #271

[:sunglasses: PREVIEW](https://277-fixhomepagebugs.app.cloud.gov/)

Changes proposed in this pull request:
- adds whats new to top of homepage in larger viewports
- adds  "Production by location" link to Explore Data page (defaulted to oil)
- adds source file links
- adds the word "Total" before Revenue , Disbursement and Production data.
- adds the units that are missing for the commodities in the production tab on the horizontal max line and by the year in the table.
- adds fiscal/calendar year to year slider
- sticky slider element
- sticky sub navigation
- mobile map menu
- mobile menu

### CODE REVIEW

**Comment by mcharg** [comment]
@jlouis-onrr It feels like what's new has more weight than the intro paragraph.  Can you try reducing the font size and removing the extra space between the two bullets to make the box take up less space and feel less prominent?
image

**Comment by mcharg** [comment]
@jlouis-onrr The production by location link is opening the explore data page up to revenue.

**Comment by mcharg** [comment]
@jlouis-onrr The revenue by month source file link is returning a 404 error.

**Comment by mcharg** [comment]
@jlouis-onrr Can you also add production units after the year in the table (but only once)?
image

**Comment by jlouis-onrr** [comment]
@mcharg the updated homepage whats new styling has been pushed, along with the dataType filtering.

**Pull request merged**
