### PR TITLE
1200 data diagram

### LINKED ISSUE #1200: Build how data sets fit diagram
Design: https://vt4ciw.axshare.com

### PR DESCRIPTION
**Pull request by master12**
Fixes #1200

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1200-data-diagram/how-revenue-works)

Changes proposed in this pull request:

- Added data set diagram to how it works
-
-

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 Can the diagram go the full width of the header to allow for less wrapping?
image

**Comment by mcharg** [comment]
@master12 Can you add an extra break between the intro paragraphs?
image

**Comment by mcharg** [comment]
@master12 The unselected tabs look more disabled here than they look on the homepage and we need to figure out a way to not have the labels cut off.  @jlouis-onrr Any ideas?
image

**Comment by mcharg** [comment]
@master12 I edited the copy and added links to the query tool, but the build keeps failing.

**Comment by Maroyafaied** [comment]
@master12 is it possible to widen this so "Data Usage" can be displayed? 
image

**Comment by mcharg** [comment]
@master12 Weren't you going to turn the tabs into accordions?

**Comment by mcharg** [comment]
@master12 Arrows aren't showing up on desktop and revenue and disbursements are squished at the bottom.
image
image

**Comment by mcharg** [comment]
@master12 The left nav is acting wonky.  When I click on an item, the previous one highlights.  

Here, I clicked on Land ownership, but Site data is highlighting.
image

Here, I clicked on resources to revenue.
image

**Comment by mcharg** [comment]
@master12 Arrows are now showing up, but it took a really long time to load.
image

**Comment by mcharg** [comment]
@master12 The revenue by company query tool link is broken.  I didn't know the right format for the data type.

**Comment by mcharg** [comment]
@master12 On mobile, you have to click on the arrow to expand/collapse, which is a small tap target.  Can you make the whole card header clickable?
image

**Review by Maroyafaied — APPROVED** [review]

**Review by mcharg — APPROVED** [review]

**Pull request merged**
