### PR TITLE
159 fed rev by company query tool

### LINKED ISSUE #159: Add Federal Revenue by Company to the query tool
We're going to put this in the query tool as a separate data type instead of building a custom page.

### PR DESCRIPTION
**Pull request by master12**
Fixes #159 

[:sunglasses: PREVIEW](https://159-fed-rev-by-company-query-tool.app.cloud.gov/query-data?dataType=Revenue%20by%20company)

Changes proposed in this pull request:

- Added federal revenue by company data to query tool
- Added compaay name search filter
-

### CODE REVIEW

**Comment by mcharg** [comment]
@master12 Please add a Source file and documentation link to the downloads tab that links to this page.
https://159-fed-rev-by-company-query-tool.app.cloud.gov/downloads/federal-revenue-by-company/

**Comment by mcharg** [comment]
Otherwise, looks good.

**Comment by mcharg** [comment]
@master12 Something wonky happened when you merged in dev.  This is what I'm seeing. 
image

**Comment by jennmalcolm** [comment]
The footer is looking weird for me. I'm in Chrome. 
image

**Comment by jennmalcolm** [comment]
@lpgoldstein I add you to review the data. I will also do some data checks, but I wanted to have a thorough review.

Thanks.

**Comment by master12** [comment]
@lpgoldstein @jennmalcolm I think the footer issue is resolved. Not sure why it was failing but I think it had to do with us moving image files around. Hopefully it is resolved

**Comment by lpgoldstein** [comment]
@master12 The footer issue looks good. Are you ready for us to review the data again yet?

**Comment by master12** [comment]
YES

**Comment by jennmalcolm** [comment]
@mcharg and @master12, should we change the plain "Revenue" to "Revenue by location" so the distinction between the datasets is clearer? Also, how about putting both the revenue datasets together in the dropdown instead of separated by disbursements and production?

I'm also just waiting on the data to get fixed before I review again. Mojo is going to work on that today.

**Comment by mcharg** [comment]
@jennmalcolm The trouble with calling it revenue by location assumes users want it grouped by location.  Putting both in the same option in the drop-down would mess up the filtering, since the two have different filter and group by options.

**Comment by mcharg** [comment]
@jennmalcolm What if we called revenue by company "Company revenue" and revenue "Nationwide revenue"?

**Comment by jennmalcolm** [comment]
It's not really company revenue. It's the government's revenue broken down by submitting company. We can just leave the other revenue as is in the menu if you think adding location will cause confusion.

Also, I wasn't intending to suggest making it the same selection, just moving one so the two revenues are together (one after the other) in the dropdown.

**Comment by mcharg** [comment]
@jennmalcolm It would make sense to group the two revenue options.  

@branic18 @timtom619 Can you please add something to the user interview plan to get at whether we need to relabel either the Revenue or the Revenue by Company option?

**Comment by jennmalcolm** [comment]
@master12 can you group the revenue items together in the dropdown and address the conflicts please?

**Review by jennmalcolm — APPROVED** [review]

**Pull request merged**
